#!/usr/bin/env python3
"""
prepare_data.py

Load and prepare temperature sensor data for maritime-continental analysis.
This script handles data loading, time alignment, deployment masking, and
basic data organization for subsequent analysis.

Author: Generated by Claude Code
Created: 2025-10-01
"""

import pandas as pd
import numpy as np
import xarray as xr
from pathlib import Path
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    """Main data loading and preparation workflow"""

    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "intermediate" / "pendants"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=== Maritime-Continental Analysis: Data Preparation ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("✓ Found deployment periods CSV - using CSV-based masking")
    else:
        print("✗ No deployment periods CSV found - using automatic detection only")

    # Load site elevation data
    print("\n--- Loading Site Metadata ---")
    site_elevations = load_site_elevations(csv_deployment_path)
    print(f"Loaded elevation data for {len(site_elevations)} sites")

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\n--- Loading NetCDF Files ---")
    print(f"Found {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("ERROR: No NetCDF files found!")
        return None

    # Load and organize datasets by site
    site_data = load_site_data(netcdf_files)
    print(f"Loaded data for {len(site_data)} unique sites")

    # Filter sites that have both 1m and 2m sensors
    sites_with_both = filter_sites_with_both_sensors(site_data)

    print(f"\n--- Sites with Both 1m and 2m Sensors ---")
    print(f"Found {len(sites_with_both)} sites:")
    for site_name in sorted(sites_with_both.keys()):
        elevation = site_elevations.get(site_name, "Unknown")
        sensor_1m_id = sites_with_both[site_name]["1m"]["sensor_id"]
        sensor_2m_id = sites_with_both[site_name]["2m"]["sensor_id"]
        print(f"  - {site_name} ({elevation}m): 1m={sensor_1m_id}, 2m={sensor_2m_id}")

    # Create summary of temporal coverage
    print("\n--- Temporal Coverage Summary ---")
    temporal_summary = create_temporal_summary(sites_with_both)

    for site_name, info in sorted(temporal_summary.items()):
        print(f"  {site_name}:")
        print(f"    1m: {info['1m']['start']} to {info['1m']['end']} ({info['1m']['n_obs']} obs)")
        print(f"    2m: {info['2m']['start']} to {info['2m']['end']} ({info['2m']['n_obs']} obs)")
        print(f"    Overlap: {info['overlap_days']:.1f} days")

    # Prepare data structure for analysis
    print("\n--- Preparing Data for Analysis ---")
    prepared_data = {
        "site_data": sites_with_both,
        "site_elevations": site_elevations,
        "temporal_summary": temporal_summary,
        "csv_deployment_path": csv_deployment_path,
        "use_csv_masking": use_csv_masking,
        "output_dir": output_dir,
    }

    print("\n=== Data Preparation Complete ===")
    print(f"Sites ready for analysis: {len(sites_with_both)}")
    print(f"Total elevation range: {min(site_elevations.values()):.0f}m - {max(site_elevations.values()):.0f}m")

    return prepared_data


def load_site_elevations(csv_deployment_path):
    """Load site elevation data from deployment CSV"""
    elevations = {}

    if csv_deployment_path.exists():
        df = pd.read_csv(csv_deployment_path)
        for _, row in df.iterrows():
            site = row["site"]
            elevation = row["site_elevation"]
            if pd.notna(site) and pd.notna(elevation):
                elevations[site] = float(elevation)

    return elevations


def load_site_data(netcdf_files):
    """Load and organize NetCDF datasets by site"""
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)

            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            if site_key not in site_data:
                site_data[site_key] = {}

            if sensor_height in ["1m", "2m"]:
                # Store original CSV filename for deployment masking
                original_csv_filename = None
                if hasattr(ds, "attrs") and "original_filename" in ds.attrs:
                    original_csv_filename = ds.attrs["original_filename"]
                else:
                    original_csv_filename = nc_file.name

                site_data[site_key][sensor_height] = {
                    "dataset": ds,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                    "original_csv_filename": original_csv_filename,
                }

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    return site_data


def filter_sites_with_both_sensors(site_data):
    """Filter sites that have both 1m and 2m sensors"""
    sites_with_both = {}
    required_heights = ["1m", "2m"]

    for site_name, sensors in site_data.items():
        if all(height in sensors for height in required_heights):
            sites_with_both[site_name] = sensors

    return sites_with_both


def create_temporal_summary(sites_with_both):
    """Create summary of temporal coverage for each site"""
    temporal_summary = {}

    for site_name, sensors in sites_with_both.items():
        try:
            ds_1m = sensors["1m"]["dataset"]
            ds_2m = sensors["2m"]["dataset"]

            temp_1m = ds_1m["temp_c"].dropna("datetime")
            temp_2m = ds_2m["temp_c"].dropna("datetime")

            # Get time ranges
            start_1m = pd.Timestamp(temp_1m.datetime.min().values)
            end_1m = pd.Timestamp(temp_1m.datetime.max().values)
            start_2m = pd.Timestamp(temp_2m.datetime.min().values)
            end_2m = pd.Timestamp(temp_2m.datetime.max().values)

            # Calculate overlap
            overlap_start = max(start_1m, start_2m)
            overlap_end = min(end_1m, end_2m)
            overlap_days = (overlap_end - overlap_start).total_seconds() / 86400.0

            temporal_summary[site_name] = {
                "1m": {
                    "start": start_1m.strftime("%Y-%m-%d"),
                    "end": end_1m.strftime("%Y-%m-%d"),
                    "n_obs": len(temp_1m),
                },
                "2m": {
                    "start": start_2m.strftime("%Y-%m-%d"),
                    "end": end_2m.strftime("%Y-%m-%d"),
                    "n_obs": len(temp_2m),
                },
                "overlap_days": overlap_days if overlap_days > 0 else 0,
            }

        except Exception as e:
            print(f"Error creating temporal summary for {site_name}: {e}")
            continue

    return temporal_summary


def align_site_data(site1_sensors, site2_sensors, freq="10min"):
    """
    Align two sites to a common time grid with interpolation.

    Parameters
    ----------
    site1_sensors : dict
        Dictionary containing 1m and 2m sensor data for site 1
    site2_sensors : dict
        Dictionary containing 1m and 2m sensor data for site 2
    freq : str
        Frequency for common time grid (default: "10min")

    Returns
    -------
    dict
        Dictionary containing aligned data with keys:
        - times: common time array
        - site1_1m, site1_2m, site2_1m, site2_2m: temperature arrays
        - valid_mask: boolean mask for non-NaN values
    """

    # Extract datasets
    ds1_1m = site1_sensors["1m"]["dataset"]
    ds1_2m = site1_sensors["2m"]["dataset"]
    ds2_1m = site2_sensors["1m"]["dataset"]
    ds2_2m = site2_sensors["2m"]["dataset"]

    # Get temperature data
    temp1_1m = ds1_1m["temp_c"].dropna("datetime")
    temp1_2m = ds1_2m["temp_c"].dropna("datetime")
    temp2_1m = ds2_1m["temp_c"].dropna("datetime")
    temp2_2m = ds2_2m["temp_c"].dropna("datetime")

    # Find overlapping time period
    start_time = max(
        temp1_1m.datetime.min().values,
        temp1_2m.datetime.min().values,
        temp2_1m.datetime.min().values,
        temp2_2m.datetime.min().values,
    )
    end_time = min(
        temp1_1m.datetime.max().values,
        temp1_2m.datetime.max().values,
        temp2_1m.datetime.max().values,
        temp2_2m.datetime.max().values,
    )

    if start_time >= end_time:
        return None

    # Create common time grid
    common_times = pd.date_range(start_time, end_time, freq=freq)

    # Interpolate all sensors to common time grid
    temp1_1m_interp = temp1_1m.interp(datetime=common_times, method="linear")
    temp1_2m_interp = temp1_2m.interp(datetime=common_times, method="linear")
    temp2_1m_interp = temp2_1m.interp(datetime=common_times, method="linear")
    temp2_2m_interp = temp2_2m.interp(datetime=common_times, method="linear")

    # Create valid mask (no NaN values)
    valid_mask = ~(
        np.isnan(temp1_1m_interp.values)
        | np.isnan(temp1_2m_interp.values)
        | np.isnan(temp2_1m_interp.values)
        | np.isnan(temp2_2m_interp.values)
    )

    return {
        "times": common_times,
        "site1_1m": temp1_1m_interp.values,
        "site1_2m": temp1_2m_interp.values,
        "site2_1m": temp2_1m_interp.values,
        "site2_2m": temp2_2m_interp.values,
        "valid_mask": valid_mask,
    }


def apply_deployment_masking(
    datasets,
    sensor_info_list,
    times,
    csv_deployment_path,
):
    """
    Apply deployment masking to all sensors.

    Parameters
    ----------
    datasets : list of xarray.Dataset
        List of datasets to mask
    sensor_info_list : list of dict
        List of sensor info dictionaries
    times : array-like
        Time array to mask
    csv_deployment_path : Path
        Path to deployment periods CSV

    Returns
    -------
    np.ndarray
        Combined boolean mask (True where all sensors are deployed)
    """

    deployed_masks = []

    for ds, sensor_info in zip(datasets, sensor_info_list):
        site_name = ds.attrs.get("site_name", "Unknown")
        height = ds.attrs.get("sensor_height", "Unknown")
        sensor_id = ds.attrs.get("sensor_id", "Unknown")

        csv_filename = find_matching_csv_filename(
            sensor_id, site_name, height, csv_deployment_path
        )

        if csv_filename:
            # Create dummy temperature array for masking function
            dummy_temp = np.zeros(len(times))
            deployed = mask_from_csv_deployment_periods(
                dummy_temp, times, csv_filename, csv_deployment_path
            )
            deployed_masks.append(deployed)
        else:
            # If no deployment info, assume always deployed
            deployed_masks.append(np.ones(len(times), dtype=bool))

    # Combined mask: all sensors must be deployed
    combined_mask = np.all(deployed_masks, axis=0)
    return combined_mask


if __name__ == "__main__":
    prepared_data = main()

    if prepared_data:
        print("\nData structure ready for analysis:")
        print(f"  - {len(prepared_data['site_data'])} sites loaded")
        print(f"  - Elevation range: {min(prepared_data['site_elevations'].values()):.0f}m - {max(prepared_data['site_elevations'].values()):.0f}m")
        print(f"  - Output directory: {prepared_data['output_dir']}")
