[project]
name = "jiflr"
version = "0.0.0"
description = ""
authors = [
    {name = "Daniel Otto", email = "drotto@uw.edu"}
]
license = {text = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "xarray",
    "tqdm",
    "pandas",
    "dill",
    "dask[complete]",
    "zarr>=2.16.1",
    "cfgrib",
    "jupyter>=1.1.1",
    "pip>=25.0.1",
    "cartopy>=0.21.1",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]

[tool.pytest.ini_options]
pythonpath = "src/"

[tool.uv.workspace]
members = [
    "jiflr",
]
