#!/usr/bin/env python3
"""
autoregression_power_analysis.py

High-frequency noise analysis and sensor response time assessment at 1-minute resolution.
Focus on <6 hour fluctuations and sensor response characteristics using WOSA method
with comparison between sites and sensor heights (2m vs 1m).

Author: Generated by Claude Code
Created: 2025-07-28
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy import signal
from scipy.stats import pearsonr, mannwhitneyu
from statsmodels.tsa.ar_model import AutoReg
from statsmodels.tsa.stattools import acf, pacf
from statsmodels.stats.diagnostic import acorr_ljungbox

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    """Main function to run autoregression and power spectral analysis"""
    
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"
    
    print("=== Autoregression and Power Spectral Analysis ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")
    
    # Create output directory if it doesn't exist
    output_dir.mkdir(exist_ok=True)
    
    # Check if CSV deployment file exists
    use_csv_masking = False  # Temporarily disable CSV masking due to date issues
    if csv_deployment_path.exists():
        print("Found deployment periods CSV - but disabling due to date mismatch")
    else:
        print("No deployment periods CSV found - using automatic detection only")
    
    # Load and organize sensor data
    sensor_data = load_sensor_data(processed_dir, csv_deployment_path, use_csv_masking)
    
    if not sensor_data:
        print("No valid sensor data found!")
        return
    
    print(f"\nLoaded {len(sensor_data)} sensors for analysis")
    
    # Organize data by site and height for comparison
    organized_data = organize_data_by_site_height(sensor_data)
    
    # Perform autoregression analysis
    ar_results = perform_autoregression_analysis(organized_data)
    
    # Perform power spectral analysis using WOSA
    psd_results = perform_power_spectral_analysis(organized_data)
    
    # Create comprehensive visualizations
    create_autoregression_visualizations(ar_results, output_dir)
    create_power_spectrum_visualizations(psd_results, output_dir)
    create_comparison_visualizations(ar_results, psd_results, output_dir)
    
    # Save results to files
    save_analysis_results(ar_results, psd_results, output_dir)
    
    print(f"\nAnalysis complete! Results saved to: {output_dir}")


def load_sensor_data(processed_dir, csv_deployment_path, use_csv_masking):
    """Load and organize sensor data from NetCDF files"""
    
    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")
    
    if not netcdf_files:
        return {}
    
    sensor_data = {}
    
    for nc_file in tqdm(netcdf_files, desc="Loading sensor datasets"):
        try:
            ds = xr.open_dataset(nc_file)
            
            # Extract metadata
            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")
            
            # Create unique sensor identifier
            sensor_key = f"{site_name}_{sensor_height}_{sensor_id}"
            
            # Get temperature data
            temp_data = ds["temp_c"].dropna(dim="datetime")
            
            if len(temp_data) == 0:
                print(f"No valid temperature data for {sensor_key}")
                continue
            
            # Skip data from before 2025
            if temp_data.datetime.min().values < pd.Timestamp("2025-01-01"):
                print(f"Skipping {sensor_key} - data from before 2025")
                continue
            
            # Apply deployment masking if available
            deployed_mask = None
            if use_csv_masking:
                csv_filename = find_matching_csv_filename(
                    sensor_id, site_name, sensor_height, csv_deployment_path
                )
                
                if csv_filename:
                    try:
                        deployed_mask = mask_from_csv_deployment_periods(
                            temp_data.values, 
                            temp_data.datetime.values, 
                            csv_filename, 
                            csv_deployment_path
                        )
                    except Exception as e:
                        print(f"Could not apply CSV masking for {sensor_key}: {e}")
            
            # Store sensor information
            sensor_data[sensor_key] = {
                "temperature": temp_data,
                "site_name": site_name,
                "sensor_height": sensor_height,
                "sensor_id": sensor_id,
                "deployed_mask": deployed_mask,
                "file": nc_file.name
            }
            
        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue
    
    return sensor_data


def organize_data_by_site_height(sensor_data):
    """Organize sensor data by site and height for comparison"""
    
    organized = {}
    
    for sensor_key, data in sensor_data.items():
        site_name = data["site_name"]
        sensor_height = data["sensor_height"]
        
        # Create site key if it doesn't exist
        if site_name not in organized:
            organized[site_name] = {}
        
        # Create height key if it doesn't exist
        if sensor_height not in organized[site_name]:
            organized[site_name][sensor_height] = []
        
        # Add sensor data
        organized[site_name][sensor_height].append({
            "sensor_key": sensor_key,
            "data": data
        })
    
    # Print organization summary
    print("\nData organization summary:")
    for site_name, heights in organized.items():
        print(f"  Site {site_name}:")
        for height, sensors in heights.items():
            print(f"    {height}: {len(sensors)} sensors")
    
    return organized


def perform_autoregression_analysis(organized_data):
    """Perform autoregression analysis on temperature data"""
    
    print("\nPerforming autoregression analysis...")
    
    ar_results = {}
    
    for site_name, heights in organized_data.items():
        ar_results[site_name] = {}
        
        for height, sensors in heights.items():
            ar_results[site_name][height] = []
            
            for sensor_info in sensors:
                sensor_key = sensor_info["sensor_key"]
                temp_data = sensor_info["data"]["temperature"]
                
                try:
                    # Use 1-minute resolution data directly for high-frequency analysis
                    temp_minutely = temp_data.dropna(dim="datetime")
                    
                    # Limit to recent data (last 7 days) for computational efficiency
                    if len(temp_minutely) > 10080:  # 7 days * 24 hours * 60 minutes
                        temp_minutely = temp_minutely.isel(datetime=slice(-10080, None))
                    
                    if len(temp_minutely) < 600:  # Need at least 10 hours of 1-min data
                        print(f"Insufficient data for {sensor_key}: {len(temp_minutely)} points")
                        continue
                    
                    temp_values = temp_minutely.values
                    
                    # Remove longer-term trends but preserve high-frequency content
                    # Use a 6-hour moving average to remove low-frequency trends
                    window_size = min(360, len(temp_values) // 10)  # 6 hours in minutes
                    if window_size >= 3:
                        trend = np.convolve(temp_values, np.ones(window_size)/window_size, mode='same')
                        # Handle edges
                        trend[:window_size//2] = trend[window_size//2]
                        trend[-window_size//2:] = trend[-window_size//2-1]
                    else:
                        trend = np.mean(temp_values)
                    detrended = temp_values - trend
                    
                    # Calculate autocorrelation function for high-frequency analysis
                    # Focus on lags up to 6 hours (360 minutes)
                    max_lags = min(360, len(detrended) // 4)
                    autocorr = acf(detrended, nlags=max_lags, fft=True)
                    partial_autocorr = pacf(detrended, nlags=max_lags)
                    
                    # Fit autoregressive model (AR) for high-frequency dynamics
                    # Use higher order models to capture sensor response characteristics
                    max_order = min(60, len(detrended) // 50)  # Up to 1 hour of memory
                    aic_values = []
                    bic_values = []
                    
                    for order in range(1, max_order + 1):
                        try:
                            ar_model = AutoReg(detrended, lags=order, trend='c')
                            ar_fit = ar_model.fit()
                            aic_values.append(ar_fit.aic)
                            bic_values.append(ar_fit.bic)
                        except Exception:
                            aic_values.append(np.inf)
                            bic_values.append(np.inf)
                    
                    # Select optimal order
                    optimal_order_aic = int(np.argmin(aic_values) + 1)
                    optimal_order_bic = int(np.argmin(bic_values) + 1)
                    
                    # Fit final AR model with optimal order (using AIC)
                    ar_model = AutoReg(detrended, lags=optimal_order_aic, trend='c')
                    ar_fit = ar_model.fit()
                    
                    # Calculate residuals and perform diagnostics
                    residuals = ar_fit.resid
                    
                    # Calculate R-squared manually
                    y_mean = np.mean(detrended)
                    ss_tot = np.sum((detrended - y_mean) ** 2)
                    ss_res = np.sum(residuals ** 2)
                    r_squared = 1 - (ss_res / ss_tot) if ss_tot > 0 else 0
                    
                    # Ljung-Box test for residual autocorrelation
                    lb_test = acorr_ljungbox(residuals, lags=min(10, len(residuals)//5), return_df=True)
                    
                    # Calculate persistence metrics
                    # AR(1) coefficient for persistence measure
                    ar1_coeff = ar_fit.params[1] if len(ar_fit.params) > 1 else 0
                    
                    # Autocorrelation at lag 1
                    lag1_autocorr = autocorr[1] if len(autocorr) > 1 else 0
                    
                    # e-folding time (time for autocorrelation to decay to 1/e)
                    # This gives sensor response time in minutes
                    e_folding_time = calculate_e_folding_time(autocorr)
                    
                    # Calculate additional high-frequency metrics
                    # Time to 50% correlation (sensor half-life)
                    half_life = calculate_half_life_time(autocorr)
                    
                    # High-frequency variance (< 1 hour)
                    if len(detrended) > 60:
                        high_freq_var = np.var(np.diff(detrended))  # Minute-to-minute variance
                    else:
                        high_freq_var = 0
                    
                    ar_results[site_name][height].append({
                        "sensor_key": sensor_key,
                        "optimal_order_aic": optimal_order_aic,
                        "optimal_order_bic": optimal_order_bic,
                        "aic_values": aic_values,
                        "bic_values": bic_values,
                        "ar_coefficients": ar_fit.params,
                        "ar1_coefficient": ar1_coeff,
                        "autocorr": autocorr,
                        "partial_autocorr": partial_autocorr,
                        "lag1_autocorr": lag1_autocorr,
                        "e_folding_time": e_folding_time,
                        "half_life_time": half_life,
                        "high_freq_variance": high_freq_var,
                        "residuals": residuals,
                        "ljung_box_pvalue": lb_test['lb_pvalue'].min(),
                        "r_squared": r_squared,
                        "aic": ar_fit.aic,
                        "bic": ar_fit.bic,
                        "n_obs": len(detrended),
                        "detrended_data": detrended,
                        "datetime": temp_minutely.datetime.values
                    })
                    
                except Exception as e:
                    print(f"Error in AR analysis for {sensor_key}: {e}")
                    continue
    
    return ar_results


def calculate_e_folding_time(autocorr):
    """Calculate e-folding time from autocorrelation function"""
    
    try:
        # Find where autocorrelation drops below 1/e ≈ 0.368
        threshold = 1.0 / np.e
        
        # Start from lag 1 (skip lag 0 which is always 1)
        for i in range(1, len(autocorr)):
            if autocorr[i] < threshold:
                return i
        
        # If never drops below threshold, return length
        return len(autocorr)
    
    except Exception:
        return np.nan


def calculate_half_life_time(autocorr):
    """Calculate half-life time (50% correlation) from autocorrelation function"""
    
    try:
        # Find where autocorrelation drops below 0.5
        threshold = 0.5
        
        # Start from lag 1 (skip lag 0 which is always 1)
        for i in range(1, len(autocorr)):
            if autocorr[i] < threshold:
                return i
        
        # If never drops below threshold, return length
        return len(autocorr)
    
    except Exception:
        return np.nan


def perform_power_spectral_analysis(organized_data):
    """Perform power spectral analysis using WOSA method"""
    
    print("\nPerforming power spectral analysis using WOSA...")
    
    psd_results = {}
    
    for site_name, heights in organized_data.items():
        psd_results[site_name] = {}
        
        for height, sensors in heights.items():
            psd_results[site_name][height] = []
            
            for sensor_info in sensors:
                sensor_key = sensor_info["sensor_key"]
                temp_data = sensor_info["data"]["temperature"]
                
                try:
                    # Use 1-minute resolution data directly for high-frequency analysis
                    temp_minutely = temp_data.dropna(dim="datetime")
                    
                    # Limit to recent data (last 7 days) for computational efficiency
                    if len(temp_minutely) > 10080:  # 7 days * 24 hours * 60 minutes
                        temp_minutely = temp_minutely.isel(datetime=slice(-10080, None))
                    
                    if len(temp_minutely) < 600:  # Need at least 10 hours of 1-min data
                        print(f"Insufficient data for {sensor_key}: {len(temp_minutely)} points")
                        continue
                    
                    temp_values = temp_minutely.values
                    
                    # Remove longer-term trends but preserve high-frequency content
                    # Use a 6-hour moving average to remove low-frequency trends
                    window_size = min(360, len(temp_values) // 10)  # 6 hours in minutes
                    if window_size >= 3:
                        trend = np.convolve(temp_values, np.ones(window_size)/window_size, mode='same')
                        # Handle edges
                        trend[:window_size//2] = trend[window_size//2]
                        trend[-window_size//2:] = trend[-window_size//2-1]
                    else:
                        trend = np.mean(temp_values)
                    detrended = temp_values - trend
                    
                    # Sampling frequency (1 minute = 1/60 Hz, but we work in cycles/minute)
                    fs = 1.0  # 1 sample per minute
                    
                    # WOSA parameters
                    # Window length: aim for ~256 points or 1/8 of data, whichever is smaller
                    nperseg = min(256, len(detrended) // 8)
                    if nperseg < 32:
                        nperseg = min(32, len(detrended) // 4)
                    
                    # 50% overlap as requested
                    noverlap = nperseg // 2
                    
                    # Calculate power spectral density using Welch's method (WOSA)
                    frequencies, psd = signal.welch(
                        detrended,
                        fs=fs,
                        window='hann',
                        nperseg=nperseg,
                        noverlap=noverlap,
                        detrend='linear',
                        return_onesided=True
                    )
                    
                    # Convert frequencies to periods (minutes)
                    # Avoid division by zero
                    periods = np.where(frequencies > 0, 1.0 / frequencies, np.inf)
                    
                    # Calculate integrated power in high-frequency bands (focus on <6 hours)
                    # Very high frequency (< 10 minutes) - sensor noise/response
                    very_highfreq_mask = periods < 10
                    very_highfreq_power = np.trapezoid(psd[very_highfreq_mask], frequencies[very_highfreq_mask]) if np.any(very_highfreq_mask) else 0
                    
                    # High frequency (10 minutes - 1 hour) - rapid fluctuations
                    highfreq_mask = (periods >= 10) & (periods < 60)
                    highfreq_power = np.trapezoid(psd[highfreq_mask], frequencies[highfreq_mask]) if np.any(highfreq_mask) else 0
                    
                    # Medium frequency (1-6 hours) - short-term variations
                    medfreq_mask = (periods >= 60) & (periods < 360)
                    medfreq_power = np.trapezoid(psd[medfreq_mask], frequencies[medfreq_mask]) if np.any(medfreq_mask) else 0
                    
                    # Low frequency (> 6 hours) - long-term variations
                    lowfreq_mask = periods >= 360
                    lowfreq_power = np.trapezoid(psd[lowfreq_mask], frequencies[lowfreq_mask]) if np.any(lowfreq_mask) else 0
                    
                    # Total power
                    total_power = np.trapezoid(psd, frequencies)
                    
                    # Find peak frequencies
                    peak_indices = signal.find_peaks(psd, height=np.percentile(psd, 90))[0]
                    peak_frequencies = frequencies[peak_indices]
                    peak_periods = periods[peak_indices]
                    peak_powers = psd[peak_indices]
                    
                    psd_results[site_name][height].append({
                        "sensor_key": sensor_key,
                        "frequencies": frequencies,
                        "periods": periods,
                        "psd": psd,
                        "nperseg": nperseg,
                        "noverlap": noverlap,
                        "very_highfreq_power": very_highfreq_power,
                        "highfreq_power": highfreq_power,
                        "medfreq_power": medfreq_power,
                        "lowfreq_power": lowfreq_power,
                        "total_power": total_power,
                        "very_highfreq_fraction": float(very_highfreq_power / total_power) if float(total_power) > 0 else 0.0,
                        "highfreq_fraction": float(highfreq_power / total_power) if float(total_power) > 0 else 0.0,
                        "medfreq_fraction": float(medfreq_power / total_power) if float(total_power) > 0 else 0.0,
                        "lowfreq_fraction": float(lowfreq_power / total_power) if float(total_power) > 0 else 0.0,
                        "peak_frequencies": peak_frequencies,
                        "peak_periods": peak_periods,
                        "peak_powers": peak_powers,
                        "n_obs": len(detrended),
                        "detrended_data": detrended,
                        "datetime": temp_minutely.datetime.values
                    })
                    
                except Exception as e:
                    print(f"Error in PSD analysis for {sensor_key}: {e}")
                    continue
    
    return psd_results


def create_autoregression_visualizations(ar_results, output_dir):
    """Create comprehensive autoregression visualizations"""
    
    print("\nCreating autoregression visualizations...")
    
    # Create main AR analysis figure
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    fig.suptitle('Autoregression Analysis Results', fontsize=16)
    
    # Collect data for plotting
    all_ar1_coeffs = []
    all_e_folding_times = []
    all_sites = []
    all_heights = []
    all_orders = []
    all_r_squared = []
    
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                all_ar1_coeffs.append(sensor_result["ar1_coefficient"])
                all_e_folding_times.append(sensor_result["e_folding_time"])
                all_sites.append(site_name)
                all_heights.append(height)
                all_orders.append(sensor_result["optimal_order_aic"])
                all_r_squared.append(sensor_result["r_squared"])
    
    # 1. AR(1) coefficients by site
    site_data = [
        [coeff for coeff, site in zip(all_ar1_coeffs, all_sites) if site == s]
        for s in sorted(set(all_sites))
    ]
    # Filter out empty lists
    site_labels = [s for s in sorted(set(all_sites)) if any(coeff for coeff, site in zip(all_ar1_coeffs, all_sites) if site == s)]
    site_data = [data for data in site_data if data]
    
    if site_data and site_labels:
        axes[0, 0].boxplot(site_data, labels=site_labels)
    axes[0, 0].set_title('AR(1) Coefficients by Site')
    axes[0, 0].set_ylabel('AR(1) Coefficient')
    axes[0, 0].grid(True, alpha=0.3)
    
    # 2. AR(1) coefficients by height
    height_data = [
        [coeff for coeff, height in zip(all_ar1_coeffs, all_heights) if height == h]
        for h in sorted(set(all_heights))
    ]
    height_labels = [h for h in sorted(set(all_heights)) if any(coeff for coeff, height in zip(all_ar1_coeffs, all_heights) if height == h)]
    height_data = [data for data in height_data if data]
    
    if height_data and height_labels:
        axes[0, 1].boxplot(height_data, labels=height_labels)
    axes[0, 1].set_title('AR(1) Coefficients by Height')
    axes[0, 1].set_ylabel('AR(1) Coefficient')
    axes[0, 1].grid(True, alpha=0.3)
    
    # 3. E-folding times by site
    efolding_site_data = [
        [time for time, site in zip(all_e_folding_times, all_sites) if site == s]
        for s in sorted(set(all_sites))
    ]
    efolding_site_labels = [s for s in sorted(set(all_sites)) if any(time for time, site in zip(all_e_folding_times, all_sites) if site == s)]
    efolding_site_data = [data for data in efolding_site_data if data]
    
    if efolding_site_data and efolding_site_labels:
        axes[0, 2].boxplot(efolding_site_data, labels=efolding_site_labels)
    axes[0, 2].set_title('E-folding Times by Site')
    axes[0, 2].set_ylabel('E-folding Time (hours)')
    axes[0, 2].grid(True, alpha=0.3)
    
    # 4. E-folding times by height
    efolding_height_data = [
        [time for time, height in zip(all_e_folding_times, all_heights) if height == h]
        for h in sorted(set(all_heights))
    ]
    efolding_height_labels = [h for h in sorted(set(all_heights)) if any(time for time, height in zip(all_e_folding_times, all_heights) if height == h)]
    efolding_height_data = [data for data in efolding_height_data if data]
    
    if efolding_height_data and efolding_height_labels:
        axes[1, 0].boxplot(efolding_height_data, labels=efolding_height_labels)
    axes[1, 0].set_title('E-folding Times by Height')
    axes[1, 0].set_ylabel('E-folding Time (hours)')
    axes[1, 0].grid(True, alpha=0.3)
    
    # 5. Optimal AR order distribution
    if all_orders:
        axes[1, 1].hist(all_orders, bins=range(1, max(all_orders) + 2), alpha=0.7, edgecolor='black')
    else:
        axes[1, 1].text(0.5, 0.5, 'No data available', ha='center', va='center', transform=axes[1, 1].transAxes)
    axes[1, 1].set_title('Distribution of Optimal AR Orders')
    axes[1, 1].set_xlabel('AR Order')
    axes[1, 1].set_ylabel('Frequency')
    axes[1, 1].grid(True, alpha=0.3)
    
    # 6. R-squared distribution
    if all_r_squared:
        axes[1, 2].hist(all_r_squared, bins=20, alpha=0.7, edgecolor='black')
    else:
        axes[1, 2].text(0.5, 0.5, 'No data available', ha='center', va='center', transform=axes[1, 2].transAxes)
    axes[1, 2].set_title('Distribution of AR Model R²')
    axes[1, 2].set_xlabel('R²')
    axes[1, 2].set_ylabel('Frequency')
    axes[1, 2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_dir / "autoregression_analysis.png", dpi=300, bbox_inches='tight')
    plt.close()
    
    # Create detailed autocorrelation plots
    create_autocorrelation_plots(ar_results, output_dir)


def create_autocorrelation_plots(ar_results, output_dir):
    """Create detailed autocorrelation function plots"""
    
    # Create figure for autocorrelation comparisons
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Autocorrelation Function Analysis', fontsize=16)
    
    colors = plt.cm.Set3(np.linspace(0, 1, 12))
    
    # Plot autocorrelation functions by site
    color_idx = 0
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                autocorr = sensor_result["autocorr"]
                lags = np.arange(len(autocorr))
                
                axes[0, 0].plot(lags, autocorr, color=colors[color_idx % len(colors)], 
                               alpha=0.7, linewidth=1, label=f"{site_name}_{height}")
                color_idx += 1
    
    axes[0, 0].set_title('Autocorrelation Functions by Site/Height')
    axes[0, 0].set_xlabel('Lag (hours)')
    axes[0, 0].set_ylabel('Autocorrelation')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
    
    # Plot partial autocorrelation functions
    color_idx = 0
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                pacf_vals = sensor_result["partial_autocorr"]
                lags = np.arange(len(pacf_vals))
                
                axes[0, 1].plot(lags, pacf_vals, color=colors[color_idx % len(colors)], 
                               alpha=0.7, linewidth=1, label=f"{site_name}_{height}")
                color_idx += 1
    
    axes[0, 1].set_title('Partial Autocorrelation Functions')
    axes[0, 1].set_xlabel('Lag (hours)')
    axes[0, 1].set_ylabel('Partial Autocorrelation')
    axes[0, 1].grid(True, alpha=0.3)
    
    # Plot mean autocorrelation by height
    heights = set()
    for site_name, site_heights in ar_results.items():
        heights.update(site_heights.keys())
    
    height_colors = plt.cm.viridis(np.linspace(0, 1, len(heights)))
    
    for i, height in enumerate(sorted(heights)):
        autocorrs = []
        for site_name, site_heights in ar_results.items():
            if height in site_heights:
                for sensor_result in site_heights[height]:
                    autocorrs.append(sensor_result["autocorr"])
        
        if autocorrs:
            # Pad to same length
            max_len = max(len(ac) for ac in autocorrs)
            padded_autocorrs = []
            for ac in autocorrs:
                padded = np.full(max_len, np.nan)
                padded[:len(ac)] = ac
                padded_autocorrs.append(padded)
            
            mean_autocorr = np.nanmean(padded_autocorrs, axis=0)
            std_autocorr = np.nanstd(padded_autocorrs, axis=0)
            lags = np.arange(len(mean_autocorr))
            
            axes[1, 0].plot(lags, mean_autocorr, color=height_colors[i], 
                           linewidth=2, label=f"{height}")
            axes[1, 0].fill_between(lags, mean_autocorr - std_autocorr, 
                                   mean_autocorr + std_autocorr, 
                                   color=height_colors[i], alpha=0.2)
    
    axes[1, 0].set_title('Mean Autocorrelation by Height')
    axes[1, 0].set_xlabel('Lag (hours)')
    axes[1, 0].set_ylabel('Autocorrelation')
    axes[1, 0].grid(True, alpha=0.3)
    axes[1, 0].legend()
    
    # Plot comparison of AR(1) vs lag-1 autocorrelation
    ar1_coeffs = []
    lag1_autocorrs = []
    
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                ar1_coeffs.append(sensor_result["ar1_coefficient"])
                lag1_autocorrs.append(sensor_result["lag1_autocorr"])
    
    axes[1, 1].scatter(lag1_autocorrs, ar1_coeffs, alpha=0.7)
    axes[1, 1].plot([0, 1], [0, 1], 'r--', alpha=0.5, label='1:1 line')
    axes[1, 1].set_title('AR(1) Coefficient vs Lag-1 Autocorrelation')
    axes[1, 1].set_xlabel('Lag-1 Autocorrelation')
    axes[1, 1].set_ylabel('AR(1) Coefficient')
    axes[1, 1].grid(True, alpha=0.3)
    axes[1, 1].legend()
    
    # Calculate correlation
    if len(ar1_coeffs) > 1:
        corr, p_val = pearsonr(lag1_autocorrs, ar1_coeffs)
        axes[1, 1].text(0.05, 0.95, f'r = {corr:.3f}\np = {p_val:.3f}', 
                       transform=axes[1, 1].transAxes, verticalalignment='top')
    
    plt.tight_layout()
    plt.savefig(output_dir / "autocorrelation_detailed.png", dpi=300, bbox_inches='tight')
    plt.close()


def create_power_spectrum_visualizations(psd_results, output_dir):
    """Create comprehensive power spectrum visualizations"""
    
    print("\nCreating power spectrum visualizations...")
    
    # Create main PSD figure
    fig, axes = plt.subplots(2, 3, figsize=(20, 12))
    fig.suptitle('Power Spectral Density Analysis (WOSA Method, 50% Overlap)', fontsize=16)
    
    # Collect data for summary statistics
    all_very_highfreq_fractions = []
    all_highfreq_fractions = []
    all_medfreq_fractions = []
    all_lowfreq_fractions = []
    all_sites = []
    all_heights = []
    
    # 1. Power spectra by site (log-log plot)
    colors = cm.Set3(np.linspace(0, 1, 12))
    color_idx = 0
    
    for site_name, heights in psd_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                psd = sensor_result["psd"][1:]  # Skip DC component
                periods = sensor_result["periods"][1:]
                
                axes[0, 0].loglog(periods, psd, color=colors[color_idx % len(colors)], 
                                 alpha=0.7, linewidth=1, label=f"{site_name}_{height}")
                
                # Collect statistics
                all_very_highfreq_fractions.append(sensor_result["very_highfreq_fraction"])
                all_highfreq_fractions.append(sensor_result["highfreq_fraction"])
                all_medfreq_fractions.append(sensor_result["medfreq_fraction"])
                all_lowfreq_fractions.append(sensor_result["lowfreq_fraction"])
                all_sites.append(site_name)
                all_heights.append(height)
                
                color_idx += 1
    
    axes[0, 0].set_title('Power Spectral Density by Site/Height')
    axes[0, 0].set_xlabel('Period (minutes)')
    axes[0, 0].set_ylabel('Power Spectral Density')
    axes[0, 0].grid(True, alpha=0.3)
    axes[0, 0].legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize=8)
    
    # Add vertical lines for important periods (in minutes)
    axes[0, 0].axvline(10, color='red', linestyle='--', alpha=0.7, label='10 min')
    axes[0, 0].axvline(60, color='orange', linestyle='--', alpha=0.7, label='1 hour')
    axes[0, 0].axvline(360, color='green', linestyle='--', alpha=0.7, label='6 hours')
    
    # 2. Mean power spectra by height
    heights = sorted(set(all_heights))
    height_colors = cm.viridis(np.linspace(0, 1, len(heights)))
    
    for i, height in enumerate(heights):
        psds_for_height = []
        for site_name, site_heights in psd_results.items():
            if height in site_heights:
                for sensor_result in site_heights[height]:
                    psd = sensor_result["psd"][1:]
                    periods = sensor_result["periods"][1:]
                    psds_for_height.append((periods, psd))
        
        if psds_for_height:
            # Interpolate all PSDs to common frequency grid
            min_period = max(periods.min() for periods, _ in psds_for_height)
            max_period = min(periods.max() for periods, _ in psds_for_height)
            common_periods = np.logspace(np.log10(min_period), np.log10(max_period), 100)
            
            interpolated_psds = []
            for periods, psd in psds_for_height:
                # Interpolate in log space
                log_periods = np.log10(periods)
                log_psd = np.log10(psd)
                log_common_periods = np.log10(common_periods)
                
                interp_log_psd = np.interp(log_common_periods, log_periods, log_psd)
                interpolated_psds.append(10**interp_log_psd)
            
            mean_psd = np.mean(interpolated_psds, axis=0)
            std_psd = np.std(interpolated_psds, axis=0)
            
            axes[0, 1].loglog(common_periods, mean_psd, color=height_colors[i], 
                             linewidth=2, label=f"{height}")
            axes[0, 1].fill_between(common_periods, mean_psd - std_psd, mean_psd + std_psd,
                                   color=height_colors[i], alpha=0.2)
    
    axes[0, 1].set_title('Mean Power Spectra by Height')
    axes[0, 1].set_xlabel('Period (minutes)')
    axes[0, 1].set_ylabel('Power Spectral Density')
    axes[0, 1].grid(True, alpha=0.3)
    axes[0, 1].legend()
    axes[0, 1].axvline(10, color='red', linestyle='--', alpha=0.7)
    axes[0, 1].axvline(60, color='orange', linestyle='--', alpha=0.7)
    axes[0, 1].axvline(360, color='green', linestyle='--', alpha=0.7)
    
    # 3. Very high-frequency power fraction by site (<10 min)
    vhf_site_data = []
    vhf_site_labels = []
    for s in sorted(set(all_sites)):
        site_fractions = [frac for frac, site in zip(all_very_highfreq_fractions, all_sites) if site == s]
        if site_fractions:
            vhf_site_data.append(site_fractions)
            vhf_site_labels.append(s)
    
    if vhf_site_data and vhf_site_labels and len(vhf_site_data) == len(vhf_site_labels):
        axes[0, 2].boxplot(vhf_site_data, labels=vhf_site_labels)
    axes[0, 2].set_title('Very High-Freq Power Fraction by Site (<10 min)')
    axes[0, 2].set_ylabel('Power Fraction')
    axes[0, 2].grid(True, alpha=0.3)
    
    # 4. High-frequency power fraction by height (10 min - 1 hour)
    hf_height_data = []
    hf_height_labels = []
    for h in sorted(set(all_heights)):
        height_fractions = [frac for frac, height in zip(all_highfreq_fractions, all_heights) if height == h]
        if height_fractions:
            hf_height_data.append(height_fractions)
            hf_height_labels.append(h)
    
    if hf_height_data and hf_height_labels and len(hf_height_data) == len(hf_height_labels):
        axes[1, 0].boxplot(hf_height_data, labels=hf_height_labels)
    axes[1, 0].set_title('High-Freq Power Fraction by Height (10min-1hr)')
    axes[1, 0].set_ylabel('Power Fraction')
    axes[1, 0].grid(True, alpha=0.3)
    
    # 5. Frequency band power fractions
    band_names = ['Very HF\n(<10min)', 'High-freq\n(10min-1hr)', 'Med-freq\n(1-6hr)', 'Low-freq\n(>6hr)']
    band_data = [all_very_highfreq_fractions, all_highfreq_fractions, all_medfreq_fractions, all_lowfreq_fractions]
    
    # Filter out empty band data
    valid_bands = [(data, name) for data, name in zip(band_data, band_names) if data]
    if valid_bands:
        valid_band_data, valid_band_names = zip(*valid_bands)
        axes[1, 1].boxplot(valid_band_data, labels=valid_band_names)
    axes[1, 1].set_title('Power Distribution by Frequency Band')
    axes[1, 1].set_ylabel('Power Fraction')
    axes[1, 1].grid(True, alpha=0.3)
    
    # 6. Height comparison for very high-frequency power
    height_data = {}
    for height, vhf_frac in zip(all_heights, all_very_highfreq_fractions):
        if height not in height_data:
            height_data[height] = []
        height_data[height].append(vhf_frac)
    
    height_means = [np.mean(height_data[h]) for h in sorted(height_data.keys())]
    height_stds = [np.std(height_data[h]) for h in sorted(height_data.keys())]
    
    x_pos = np.arange(len(height_means))
    axes[1, 2].bar(x_pos, height_means, yerr=height_stds, capsize=5, alpha=0.7)
    axes[1, 2].set_xticks(x_pos)
    axes[1, 2].set_xticklabels(sorted(height_data.keys()))
    axes[1, 2].set_title('Mean Very High-Freq Power by Height (<10 min)')
    axes[1, 2].set_ylabel('Very High-Freq Power Fraction')
    axes[1, 2].grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_dir / "power_spectrum_analysis.png", dpi=300, bbox_inches='tight')
    plt.close()


def create_comparison_visualizations(ar_results, psd_results, output_dir):
    """Create visualizations comparing sites and heights"""
    
    print("\nCreating comparison visualizations...")
    
    # Create comparison figure
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle('Site and Height Comparisons: 2m vs 1m Sensors', fontsize=16)
    
    # Collect data for height comparison (focus on 1m vs 2m)
    height_1m_ar1 = []
    height_2m_ar1 = []
    height_1m_daily = []
    height_2m_daily = []
    height_1m_efolding = []
    height_2m_efolding = []
    
    # Extract data for each height
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                ar1_coeff = sensor_result["ar1_coefficient"]
                e_folding = sensor_result["e_folding_time"]
                
                if height == "1m":
                    height_1m_ar1.append(ar1_coeff)
                    height_1m_efolding.append(e_folding)
                elif height == "2m":
                    height_2m_ar1.append(ar1_coeff)
                    height_2m_efolding.append(e_folding)
    
    # Extract PSD data for heights
    for site_name, heights in psd_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                very_highfreq_frac = sensor_result["very_highfreq_fraction"]
                
                if height == "1m":
                    height_1m_daily.append(very_highfreq_frac)
                elif height == "2m":
                    height_2m_daily.append(very_highfreq_frac)
    
    # 1. AR(1) coefficient comparison between heights
    if height_1m_ar1 and height_2m_ar1:
        axes[0, 0].boxplot([height_1m_ar1, height_2m_ar1], labels=['1m', '2m'])
    elif height_1m_ar1:
        axes[0, 0].boxplot([height_1m_ar1], labels=['1m'])
    elif height_2m_ar1:
        axes[0, 0].boxplot([height_2m_ar1], labels=['2m'])
        axes[0, 0].set_title('AR(1) Coefficient: 1m vs 2m Sensors')
        axes[0, 0].set_ylabel('AR(1) Coefficient')
        axes[0, 0].grid(True, alpha=0.3)
        
        # Add statistical test
        try:
            _, p_val = mannwhitneyu(height_1m_ar1, height_2m_ar1, alternative='two-sided')
            axes[0, 0].text(0.5, 0.95, f'Mann-Whitney U test\np = {p_val:.4f}', 
                           transform=axes[0, 0].transAxes, ha='center', va='top')
        except Exception:
            pass
    
    # 2. Daily power fraction comparison between heights
    if height_1m_daily and height_2m_daily:
        axes[0, 1].boxplot([height_1m_daily, height_2m_daily], labels=['1m', '2m'])
    elif height_1m_daily:
        axes[0, 1].boxplot([height_1m_daily], labels=['1m'])
    elif height_2m_daily:
        axes[0, 1].boxplot([height_2m_daily], labels=['2m'])
        axes[0, 1].set_title('Very High-Freq Power: 1m vs 2m Sensors (<10 min)')
        axes[0, 1].set_ylabel('Very High-Freq Power Fraction')
        axes[0, 1].grid(True, alpha=0.3)
        
        # Add statistical test
        try:
            _, p_val = mannwhitneyu(height_1m_daily, height_2m_daily, alternative='two-sided')
            axes[0, 1].text(0.5, 0.95, f'Mann-Whitney U test\np = {p_val:.4f}', 
                           transform=axes[0, 1].transAxes, ha='center', va='top')
        except Exception:
            pass
    
    # 3. E-folding time comparison between heights
    if height_1m_efolding and height_2m_efolding:
        axes[1, 0].boxplot([height_1m_efolding, height_2m_efolding], labels=['1m', '2m'])
    elif height_1m_efolding:
        axes[1, 0].boxplot([height_1m_efolding], labels=['1m'])
    elif height_2m_efolding:
        axes[1, 0].boxplot([height_2m_efolding], labels=['2m'])
        axes[1, 0].set_title('E-folding Time: 1m vs 2m Sensors')
        axes[1, 0].set_ylabel('E-folding Time (hours)')
        axes[1, 0].grid(True, alpha=0.3)
        
        # Add statistical test
        try:
            _, p_val = mannwhitneyu(height_1m_efolding, height_2m_efolding, alternative='two-sided')
            axes[1, 0].text(0.5, 0.95, f'Mann-Whitney U test\np = {p_val:.4f}', 
                           transform=axes[1, 0].transAxes, ha='center', va='top')
        except Exception:
            pass
    
    # 4. Site comparison summary
    site_stats = {}
    for site_name, heights in ar_results.items():
        site_ar1 = []
        site_daily = []
        
        for height, sensors in heights.items():
            for sensor_result in sensors:
                site_ar1.append(sensor_result["ar1_coefficient"])
        
        # Get corresponding PSD data
        if site_name in psd_results:
            for height, sensors in psd_results[site_name].items():
                for sensor_result in sensors:
                    site_daily.append(sensor_result["very_highfreq_fraction"])
        
        if site_ar1 and site_daily:
            site_stats[site_name] = {
                'mean_ar1': np.mean(site_ar1),
                'mean_daily': np.mean(site_daily),
                'n_sensors': len(site_ar1)
            }
    
    if site_stats:
        sites = list(site_stats.keys())
        ar1_means = [site_stats[site]['mean_ar1'] for site in sites]
        daily_means = [site_stats[site]['mean_daily'] for site in sites]
        
        axes[1, 1].scatter(ar1_means, daily_means, s=100, alpha=0.7)
        
        # Add site labels
        for i, site in enumerate(sites):
            axes[1, 1].annotate(site, (ar1_means[i], daily_means[i]), 
                               xytext=(5, 5), textcoords='offset points', fontsize=8)
        
        axes[1, 1].set_xlabel('Mean AR(1) Coefficient')
        axes[1, 1].set_ylabel('Mean Very High-Freq Power Fraction')
        axes[1, 1].set_title('Site Characteristics: Persistence vs High-Freq Noise')
        axes[1, 1].grid(True, alpha=0.3)
        
        # Add correlation
        if len(ar1_means) > 2:
            try:
                corr, p_val = pearsonr(ar1_means, daily_means)
                axes[1, 1].text(0.05, 0.95, f'r = {corr:.3f}\np = {p_val:.3f}', 
                               transform=axes[1, 1].transAxes, va='top')
            except Exception:
                pass
    
    plt.tight_layout()
    plt.savefig(output_dir / "site_height_comparison.png", dpi=300, bbox_inches='tight')
    plt.close()


def save_analysis_results(ar_results, psd_results, output_dir):
    """Save analysis results to CSV files"""
    
    print("\nSaving analysis results...")
    
    # Prepare autoregression results
    ar_data = []
    for site_name, heights in ar_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                ar_data.append({
                    'sensor_key': sensor_result['sensor_key'],
                    'site_name': site_name,
                    'sensor_height': height,
                    'optimal_order_aic': sensor_result['optimal_order_aic'],
                    'optimal_order_bic': sensor_result['optimal_order_bic'],
                    'ar1_coefficient': sensor_result['ar1_coefficient'],
                    'lag1_autocorr': sensor_result['lag1_autocorr'],
                    'e_folding_time': sensor_result['e_folding_time'],
                    'half_life_time': sensor_result['half_life_time'],
                    'high_freq_variance': sensor_result['high_freq_variance'],
                    'ljung_box_pvalue': sensor_result['ljung_box_pvalue'],
                    'r_squared': sensor_result['r_squared'],
                    'aic': sensor_result['aic'],
                    'bic': sensor_result['bic'],
                    'n_obs': sensor_result['n_obs']
                })
    
    ar_df = pd.DataFrame(ar_data)
    ar_df.to_csv(output_dir / "autoregression_results.csv", index=False)
    
    # Prepare power spectral density results
    psd_data = []
    for site_name, heights in psd_results.items():
        for height, sensors in heights.items():
            for sensor_result in sensors:
                psd_data.append({
                    'sensor_key': sensor_result['sensor_key'],
                    'site_name': site_name,
                    'sensor_height': height,
                    'total_power': sensor_result['total_power'],
                    'very_highfreq_power': sensor_result['very_highfreq_power'],
                    'highfreq_power': sensor_result['highfreq_power'],
                    'medfreq_power': sensor_result['medfreq_power'],
                    'lowfreq_power': sensor_result['lowfreq_power'],
                    'very_highfreq_fraction': sensor_result['very_highfreq_fraction'],
                    'highfreq_fraction': sensor_result['highfreq_fraction'],
                    'medfreq_fraction': sensor_result['medfreq_fraction'],
                    'lowfreq_fraction': sensor_result['lowfreq_fraction'],
                    'nperseg': sensor_result['nperseg'],
                    'noverlap': sensor_result['noverlap'],
                    'n_obs': sensor_result['n_obs']
                })
    
    psd_df = pd.DataFrame(psd_data)
    psd_df.to_csv(output_dir / "power_spectrum_results.csv", index=False)
    
    # Create summary statistics
    summary_stats = {}
    
    # Height-based statistics
    for height in ['1m', '2m']:
        height_ar = ar_df[ar_df['sensor_height'] == height]
        height_psd = psd_df[psd_df['sensor_height'] == height]
        
        if not height_ar.empty and not height_psd.empty:
            summary_stats[f'{height}_mean_ar1'] = height_ar['ar1_coefficient'].mean()
            summary_stats[f'{height}_std_ar1'] = height_ar['ar1_coefficient'].std()
            summary_stats[f'{height}_mean_very_highfreq_fraction'] = height_psd['very_highfreq_fraction'].mean()
            summary_stats[f'{height}_std_very_highfreq_fraction'] = height_psd['very_highfreq_fraction'].std()
            summary_stats[f'{height}_mean_e_folding'] = height_ar['e_folding_time'].mean()
            summary_stats[f'{height}_std_e_folding'] = height_ar['e_folding_time'].std()
            summary_stats[f'{height}_n_sensors'] = len(height_ar)
    
    # Site-based statistics
    for site in ar_df['site_name'].unique():
        site_ar = ar_df[ar_df['site_name'] == site]
        site_psd = psd_df[psd_df['site_name'] == site]
        
        if not site_ar.empty and not site_psd.empty:
            summary_stats[f'{site}_mean_ar1'] = site_ar['ar1_coefficient'].mean()
            summary_stats[f'{site}_mean_very_highfreq_fraction'] = site_psd['very_highfreq_fraction'].mean()
            summary_stats[f'{site}_n_sensors'] = len(site_ar)
    
    # Overall statistics
    summary_stats['total_sensors'] = len(ar_df)
    summary_stats['overall_mean_ar1'] = ar_df['ar1_coefficient'].mean()
    summary_stats['overall_mean_very_highfreq_fraction'] = psd_df['very_highfreq_fraction'].mean()
    
    summary_df = pd.DataFrame([summary_stats])
    summary_df.to_csv(output_dir / "analysis_summary.csv", index=False)
    
    print("Analysis results saved:")
    print("  - Autoregression results: autoregression_results.csv")
    print("  - Power spectrum results: power_spectrum_results.csv") 
    print("  - Summary statistics: analysis_summary.csv")


if __name__ == "__main__":
    main()