#!/usr/bin/env python3
"""
distribution_shape_comparison.py

Compares temperature distribution shapes between sites, exploring variance, 
skewness, and kurtosis. Includes kernel density estimation plots grouped by 
site name prefix and distinguishes 1m vs 2m sensor heights.

Author: Generated by Claude Code
Created: 2025-07-28
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy.stats import skew, kurtosis
from sklearn.neighbors import KernelDensity

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"
    
    output_dir.mkdir(parents=True, exist_ok=True)

    print("=== Temperature Distribution Shape Comparison ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - using automatic detection only")

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("No NetCDF files found!")
        return

    # Load and organize datasets by site and height
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)

            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            if site_key not in site_data:
                site_data[site_key] = {}

            if sensor_height in ["1m", "2m"]:
                # Get temperature data and apply deployment masking if available
                temp_data = ds["temp_c"].dropna("datetime")
                
                if use_csv_masking:
                    # Apply CSV-based deployment masking
                    csv_filename = find_matching_csv_filename(
                        sensor_id, site_name, sensor_height, csv_deployment_path
                    )
                    
                    if csv_filename:
                        times = pd.to_datetime(temp_data.datetime.values)
                        deployed_mask = mask_from_csv_deployment_periods(
                            temp_data.values, times, csv_filename, csv_deployment_path
                        )
                        temp_data = temp_data.values[deployed_mask]
                    else:
                        temp_data = temp_data.values
                else:
                    temp_data = temp_data.values

                site_data[site_key][sensor_height] = {
                    "data": temp_data,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                }

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    print(f"\nLoaded data for {len(site_data)} sites")
    
    # Calculate distribution statistics for all sites and heights
    stats_data = []
    for site_name, heights in site_data.items():
        for height, info in heights.items():
            temp_data = info["data"]
            if len(temp_data) > 10:  # Need sufficient data
                stats_entry = {
                    "site": site_name,
                    "height": height,
                    "sensor_id": info["sensor_id"],
                    "n_points": len(temp_data),
                    "mean": np.mean(temp_data),
                    "std": np.std(temp_data),
                    "variance": np.var(temp_data),
                    "skewness": skew(temp_data),
                    "kurtosis": kurtosis(temp_data),
                    "min": np.min(temp_data),
                    "max": np.max(temp_data),
                    "range": np.max(temp_data) - np.min(temp_data),
                    "q25": np.percentile(temp_data, 25),
                    "median": np.median(temp_data),
                    "q75": np.percentile(temp_data, 75),
                    "iqr": np.percentile(temp_data, 75) - np.percentile(temp_data, 25),
                }
                stats_data.append(stats_entry)

    stats_df = pd.DataFrame(stats_data)
    print(f"\nCalculated statistics for {len(stats_df)} sensor deployments")

    # Create distribution shape comparison plots
    create_distribution_comparison_plots(stats_df, site_data, output_dir)
    
    # Create KDE plots grouped by site prefix
    create_kde_plots_by_prefix(stats_df, site_data, output_dir)
    
    print(f"\nDistribution analysis plots saved to: {output_dir}")
    print("Analysis complete!")


def create_distribution_comparison_plots(stats_df, site_data, output_dir):
    """Create plots comparing variance, skewness, and kurtosis between sites"""
    
    # Create figure with subplots
    fig = plt.figure(figsize=(20, 16))
    gs = gridspec.GridSpec(3, 3, hspace=0.3, wspace=0.3)
    
    # Add overall title
    fig.suptitle("Temperature Distribution Shape Comparison Across Sites", 
                 fontsize=16, fontweight="bold")
    
    # Define colors for 1m vs 2m
    colors = {"1m": "blue", "2m": "red"}
    markers = {"1m": "o", "2m": "s"}
    
    # Plot 1: Variance comparison
    ax1 = fig.add_subplot(gs[0, 0])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax1.scatter(range(len(height_data)), height_data["variance"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors (n={len(height_data)})")
    
    ax1.set_title("Temperature Variance by Site")
    ax1.set_xlabel("Site Index")
    ax1.set_ylabel("Variance (°C²)")
    ax1.legend()
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Skewness comparison
    ax2 = fig.add_subplot(gs[0, 1])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax2.scatter(range(len(height_data)), height_data["skewness"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax2.axhline(y=0, color="black", linestyle="--", alpha=0.5, label="Normal distribution")
    ax2.set_title("Temperature Skewness by Site")
    ax2.set_xlabel("Site Index")
    ax2.set_ylabel("Skewness")
    ax2.legend()
    ax2.grid(True, alpha=0.3)
    
    # Plot 3: Kurtosis comparison
    ax3 = fig.add_subplot(gs[0, 2])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax3.scatter(range(len(height_data)), height_data["kurtosis"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax3.axhline(y=0, color="black", linestyle="--", alpha=0.5, label="Normal distribution")
    ax3.set_title("Temperature Kurtosis by Site")
    ax3.set_xlabel("Site Index")
    ax3.set_ylabel("Excess Kurtosis")
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Variance vs Standard Deviation
    ax4 = fig.add_subplot(gs[1, 0])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax4.scatter(height_data["std"], height_data["variance"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax4.set_title("Variance vs Standard Deviation")
    ax4.set_xlabel("Standard Deviation (°C)")
    ax4.set_ylabel("Variance (°C²)")
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    
    # Plot 5: Skewness vs Kurtosis
    ax5 = fig.add_subplot(gs[1, 1])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax5.scatter(height_data["skewness"], height_data["kurtosis"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax5.axhline(y=0, color="black", linestyle="--", alpha=0.3)
    ax5.axvline(x=0, color="black", linestyle="--", alpha=0.3)
    ax5.set_title("Skewness vs Kurtosis")
    ax5.set_xlabel("Skewness")
    ax5.set_ylabel("Excess Kurtosis")
    ax5.legend()
    ax5.grid(True, alpha=0.3)
    
    # Plot 6: Range vs IQR
    ax6 = fig.add_subplot(gs[1, 2])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax6.scatter(height_data["iqr"], height_data["range"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax6.set_title("Total Range vs Interquartile Range")
    ax6.set_xlabel("IQR (°C)")
    ax6.set_ylabel("Range (°C)")
    ax6.legend()
    ax6.grid(True, alpha=0.3)
    
    # Plot 7: Box plots comparing 1m vs 2m for each metric
    ax7 = fig.add_subplot(gs[2, 0])
    metrics_for_boxplot = ["variance", "skewness", "kurtosis"]
    box_data = []
    box_labels = []
    box_colors = []
    
    for metric in metrics_for_boxplot:
        for height in ["1m", "2m"]:
            height_data = stats_df[stats_df["height"] == height]
            if len(height_data) > 0:
                box_data.append(height_data[metric].values)
                box_labels.append(f"{metric}\n{height}")
                box_colors.append(colors[height])
    
    if box_data:
        bp = ax7.boxplot(box_data, labels=box_labels, patch_artist=True)
        for patch, color in zip(bp['boxes'], box_colors):
            patch.set_facecolor(color)
            patch.set_alpha(0.7)
    
    ax7.set_title("Distribution Shape Metrics: 1m vs 2m")
    ax7.set_ylabel("Metric Value")
    ax7.grid(True, alpha=0.3)
    ax7.tick_params(axis='x', rotation=45)
    
    # Plot 8: Histogram of sample sizes
    ax8 = fig.add_subplot(gs[2, 1])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax8.hist(height_data["n_points"], bins=20, alpha=0.6, 
                    color=colors[height], label=f"{height} sensors", 
                    edgecolor="black", linewidth=0.5)
    
    ax8.set_title("Distribution of Sample Sizes")
    ax8.set_xlabel("Number of Temperature Measurements")
    ax8.set_ylabel("Frequency")
    ax8.legend()
    ax8.grid(True, alpha=0.3)
    
    # Plot 9: Mean temperature by height
    ax9 = fig.add_subplot(gs[2, 2])
    for height in ["1m", "2m"]:
        height_data = stats_df[stats_df["height"] == height]
        if len(height_data) > 0:
            ax9.scatter(range(len(height_data)), height_data["mean"], 
                       c=colors[height], marker=markers[height], alpha=0.7, 
                       s=60, label=f"{height} sensors")
    
    ax9.set_title("Mean Temperature by Site")
    ax9.set_xlabel("Site Index")
    ax9.set_ylabel("Mean Temperature (°C)")
    ax9.legend()
    ax9.grid(True, alpha=0.3)
    
    # Save the plot
    output_file = output_dir / "distribution_shape_comparison.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()
    
    print(f"Distribution comparison plot saved: {output_file}")


def create_kde_plots_by_prefix(stats_df, site_data, output_dir):
    """Create kernel density estimation plots grouped by site name prefix"""
    
    # Group sites by first letter
    site_prefixes = {}
    for site_name in site_data.keys():
        if site_name != "Unknown" and len(site_name) > 0:
            prefix = site_name[0].upper()
            if prefix not in site_prefixes:
                site_prefixes[prefix] = []
            site_prefixes[prefix].append(site_name)
    
    # Only keep prefixes with multiple sites
    site_prefixes = {k: v for k, v in site_prefixes.items() if len(v) >= 2}
    
    if not site_prefixes:
        print("Not enough sites with common prefixes for KDE analysis")
        return
    
    print(f"Creating KDE plots for {len(site_prefixes)} site prefix groups")
    
    # Create KDE plots for each prefix group
    n_prefixes = len(site_prefixes)
    n_cols = min(3, n_prefixes)
    n_rows = (n_prefixes + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 5*n_rows))
    if n_rows == 1 and n_cols == 1:
        axes = [axes]
    elif n_rows == 1 or n_cols == 1:
        axes = axes.flatten()
    else:
        axes = axes.flatten()
    
    fig.suptitle("Temperature Distribution KDE by Site Prefix", 
                 fontsize=16, fontweight="bold")
    
    linestyles = {"1m": "--", "2m": "-"}
    
    i = 0
    for i, (prefix, sites) in enumerate(site_prefixes.items()):
        if i >= len(axes):
            break
            
        ax = axes[i]
        
        # Collect temperature data for each site separately
        site_temps = {}
        temp_ranges = []
        
        for site_name in sites:
            if site_name in site_data:
                site_temps[site_name] = {}
                for height in ["1m", "2m"]:
                    if height in site_data[site_name]:
                        temp_data = site_data[site_name][height]["data"]
                        if len(temp_data) > 10:  # Need sufficient data
                            site_temps[site_name][height] = temp_data
                            temp_ranges.extend(temp_data)
        
        # Create KDE plots if we have data
        if temp_ranges:
            temp_min, temp_max = np.min(temp_ranges), np.max(temp_ranges)
            temp_grid = np.linspace(temp_min, temp_max, 200)
            
            # Generate distinct colors for each site
            import matplotlib.cm as cm
            n_sites = len(site_temps)
            site_colors = cm.tab10(np.linspace(0, 1, max(n_sites, 3)))
            
            # Plot KDE for each site separately
            for site_idx, (site_name, heights) in enumerate(site_temps.items()):
                base_color = site_colors[site_idx % len(site_colors)]
                
                for height in ["1m", "2m"]:
                    if height in heights:
                        temp_data = np.array(heights[height])
                        
                        # Create KDE
                        kde = KernelDensity(bandwidth=0.5)
                        kde.fit(temp_data.reshape(-1, 1))
                        log_density = kde.score_samples(temp_grid.reshape(-1, 1))
                        density = np.exp(log_density)
                        
                        # Use different line styles for 1m vs 2m
                        alpha = 0.8 if height == "2m" else 0.6
                        linewidth = 2 if height == "2m" else 1.5
                        
                        ax.plot(temp_grid, density, 
                               color=base_color, 
                               linestyle=linestyles[height], 
                               linewidth=linewidth,
                               alpha=alpha,
                               label=f"{site_name} {height} (n={len(temp_data)})")
            
            # Create legend showing line style meanings
            import matplotlib.lines as mlines
            legend_elements = [
                mlines.Line2D([0], [0], color='gray', linestyle='-', 
                             label='2m sensors', linewidth=2, alpha=0.8),
                mlines.Line2D([0], [0], color='gray', linestyle='--', 
                             label='1m sensors', linewidth=1.5, alpha=0.6)
            ]
            
            # Add legend with line style explanation
            ax.legend(handles=legend_elements, loc='upper left', 
                     title='Sensor Heights', fontsize=8)
        
        ax.set_title(f"Sites starting with '{prefix}'\n({', '.join(sites)})")
        ax.set_xlabel("Temperature (°C)")
        ax.set_ylabel("Density")
        ax.grid(True, alpha=0.3)
    
    # Hide unused subplots
    if len(site_prefixes) > 0:
        for j in range(i + 1, len(axes)):
            axes[j].set_visible(False)
    
    plt.tight_layout()
    
    # Save the plot
    output_file = output_dir / "kde_plots_by_prefix.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()
    
    print(f"KDE plots by prefix saved: {output_file}")
    
    # Also create individual site KDE plots
    create_individual_site_kde_plots(site_data, output_dir)


def create_individual_site_kde_plots(site_data, output_dir):
    """Create detailed KDE plots for individual sites with both 1m and 2m sensors"""
    
    # Find sites with both 1m and 2m sensors
    sites_with_both = {}
    for site_name, heights in site_data.items():
        if "1m" in heights and "2m" in heights:
            # Check that both have sufficient data
            temp_1m = heights["1m"]["data"]
            temp_2m = heights["2m"]["data"]
            if len(temp_1m) > 10 and len(temp_2m) > 10:
                sites_with_both[site_name] = heights
    
    if not sites_with_both:
        print("No sites found with both 1m and 2m sensors having sufficient data")
        return
    
    print(f"Creating individual KDE plots for {len(sites_with_both)} sites")
    
    # Create subplot grid
    n_sites = len(sites_with_both)
    n_cols = min(3, n_sites)
    n_rows = (n_sites + n_cols - 1) // n_cols
    
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(6*n_cols, 5*n_rows))
    if n_sites == 1:
        axes = [axes]
    elif n_rows == 1 or n_cols == 1:
        axes = axes.flatten()
    else:
        axes = axes.flatten()
    
    fig.suptitle("Temperature Distribution Comparison: 1m vs 2m Sensors by Site", 
                 fontsize=16, fontweight="bold")
    
    colors = {"1m": "blue", "2m": "red"}
    
    i = 0
    for i, (site_name, heights) in enumerate(sites_with_both.items()):
        if i >= len(axes):
            break
            
        ax = axes[i]
        
        temp_1m = heights["1m"]["data"]
        temp_2m = heights["2m"]["data"]
        
        # Calculate combined temperature range
        all_temps = np.concatenate([temp_1m, temp_2m])
        temp_min, temp_max = np.min(all_temps), np.max(all_temps)
        temp_grid = np.linspace(temp_min, temp_max, 200)
        
        # Create histograms and KDEs
        for height, temps in [("1m", temp_1m), ("2m", temp_2m)]:
            # Histogram
            ax.hist(temps, bins=30, alpha=0.3, color=colors[height], 
                   density=True, label=f"{height} histogram (n={len(temps)})")
            
            # KDE
            if len(temps) > 5:
                kde = KernelDensity(bandwidth=0.5)
                kde.fit(temps.reshape(-1, 1))
                log_density = kde.score_samples(temp_grid.reshape(-1, 1))
                density = np.exp(log_density)
                
                ax.plot(temp_grid, density, color=colors[height], 
                       linewidth=2, label=f"{height} KDE")
        
        # Calculate and display statistics
        stats_1m = {
            "mean": np.mean(temp_1m),
            "std": np.std(temp_1m),
            "skew": skew(temp_1m),
            "kurt": kurtosis(temp_1m)
        }
        stats_2m = {
            "mean": np.mean(temp_2m),
            "std": np.std(temp_2m),
            "skew": skew(temp_2m),
            "kurt": kurtosis(temp_2m)
        }
        
        # Add mean lines
        ax.axvline(stats_1m["mean"], color=colors["1m"], linestyle="--", 
                  alpha=0.8, label=f"1m mean: {stats_1m['mean']:.1f}°C")
        ax.axvline(stats_2m["mean"], color=colors["2m"], linestyle="--", 
                  alpha=0.8, label=f"2m mean: {stats_2m['mean']:.1f}°C")
        
        ax.set_title(f"{site_name}\n"
                    f"1m: σ={stats_1m['std']:.2f}, skew={stats_1m['skew']:.2f}, kurt={stats_1m['kurt']:.2f}\n"
                    f"2m: σ={stats_2m['std']:.2f}, skew={stats_2m['skew']:.2f}, kurt={stats_2m['kurt']:.2f}")
        ax.set_xlabel("Temperature (°C)")
        ax.set_ylabel("Density")
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.3)
    
    # Hide unused subplots
    if len(sites_with_both) > 0:
        for j in range(i + 1, len(axes)):
            if j < len(axes):
                axes[j].set_visible(False)
    
    plt.tight_layout()
    
    # Save the plot
    output_file = output_dir / "individual_site_kde_comparison.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()
    
    print(f"Individual site KDE plots saved: {output_file}")


if __name__ == "__main__":
    main()