#!/usr/bin/env python3
"""
explore_2025_data.py

Script to load all 2025 sensor data, group by site, and create plots.

Author: Generated by Claude Code
Created: 2025-07-27
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.pipeline import clean_hobo_pendants
from jiflr.io import read_pendant_dataset
from jiflr.utils import mask_from_csv_deployment_periods, find_matching_csv_filename


def main():
    # Define paths
    raw_export_dir = Path(ROOT) / "data" / "2025" / "raw_exported"
    processed_dir = Path(ROOT) / "data" / "2025" / "intermediate" / "pendants"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    # Create processed directory if it doesn't exist
    processed_dir.mkdir(parents=True, exist_ok=True)

    print("=== 2025 Data Exploration ===")
    print(f"Raw export directory: {raw_export_dir}")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - showing all data")

    # Get all CSV files from raw_exported directory
    csv_files = list(raw_export_dir.glob("*.csv"))
    print(f"\nFound {len(csv_files)} CSV files to process")

    if not csv_files:
        print("No CSV files found in raw_exported directory!")
        return

    # Process CSV files to NetCDF if not already processed
    netcdf_files = list(processed_dir.glob("*.nc"))

    if not netcdf_files:
        print("No NetCDF files available for analysis!")
        return

    # Load all datasets
    print("\nLoading and analyzing datasets...")
    datasets = []
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)
            datasets.append(ds)

            # Extract site information
            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_config = ds.attrs.get("sensor_config", "")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            # Create a site key for grouping
            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            # Group by site
            if site_key not in site_data:
                site_data[site_key] = []

            site_data[site_key].append(
                {
                    "dataset": ds,
                    "height": sensor_height,
                    "config": sensor_config,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                }
            )

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    print(f"\nLoaded {len(datasets)} datasets")
    print(f"Found {len(site_data)} unique sites: {list(site_data.keys())}")

    # Create plots by site
    print("\nCreating plots by site...")

    for site_name, site_sensors in tqdm(site_data.items(), desc="Creating plots"):
        create_site_plots(
            site_name, site_sensors, output_dir, csv_deployment_path, use_csv_masking
        )

    # Create overview plot
    create_overview_plot(site_data, output_dir, csv_deployment_path, use_csv_masking)

    print(f"\nPlots saved to: {output_dir}")
    print("Analysis complete!")


def create_site_plots(
    site_name, site_sensors, output_dir, csv_deployment_path, use_csv_masking
):
    """Create plots for a specific site"""

    fig, axes = plt.subplots(3, 1, figsize=(16, 12))
    fig.suptitle(f"Site: {site_name}", fontsize=16, fontweight="bold")

    # Colors for different sensors/heights
    colors = plt.cm.Set1(np.linspace(0, 1, len(site_sensors)))

    # Organize sensors by height for temperature difference calculation
    sensors_1m = []
    sensors_2m = []
    other_sensors = []

    for sensor_info in site_sensors:
        height = sensor_info["height"]
        if height == "1m":
            sensors_1m.append(sensor_info)
        elif height == "2m":
            sensors_2m.append(sensor_info)
        else:
            other_sensors.append(sensor_info)

    # Plot all sensors
    for i, sensor_info in enumerate(site_sensors):
        ds = sensor_info["dataset"]
        height = sensor_info["height"]
        config = sensor_info["config"]
        sensor_id = sensor_info["sensor_id"]

        # Create label for legend
        label_parts = [f"ID: {sensor_id}"]
        if height != "Unknown":
            label_parts.append(f"Height: {height}")
        if config:
            label_parts.append(f"Config: {config}")
        label = " | ".join(label_parts)

        color = colors[i]

        # Apply CSV masking if available
        filename = sensor_info["file"]
        csv_filename = filename.replace(".nc", ".csv")

        # Plot 1: Temperature time series
        if "temp_c" in ds.data_vars:
            temp_data = ds["temp_c"].dropna("datetime")
            if len(temp_data) > 0:
                # Apply deployment masking if CSV is available
                if use_csv_masking:
                    deployment_mask = mask_from_csv_deployment_periods(
                        temp_data.values,
                        temp_data.datetime,
                        csv_filename,
                        csv_deployment_path,
                    )
                    # Plot all data in light color
                    axes[0].plot(
                        temp_data.datetime,
                        temp_data.values,
                        color=color,
                        alpha=0.3,
                        linewidth=0.5,
                        label=f"{label} (all)",
                    )
                    # Plot deployed data in full color
                    deployed_data = temp_data.values.copy()
                    deployed_data[~deployment_mask] = np.nan
                    axes[0].plot(
                        temp_data.datetime,
                        deployed_data,
                        color=color,
                        alpha=0.8,
                        linewidth=1,
                        label=f"{label} (deployed)",
                    )
                else:
                    axes[0].plot(
                        temp_data.datetime,
                        temp_data.values,
                        label=label,
                        color=color,
                        alpha=0.7,
                        linewidth=1,
                    )

        # Plot 2: Temperature histogram
        if "temp_c" in ds.data_vars:
            temp_data = ds["temp_c"].dropna("datetime")
            if len(temp_data) > 0:
                if use_csv_masking:
                    deployment_mask = mask_from_csv_deployment_periods(
                        temp_data.values,
                        temp_data.datetime,
                        csv_filename,
                        csv_deployment_path,
                    )
                    # Plot only deployed data
                    deployed_temps = temp_data.values[deployment_mask]
                    if len(deployed_temps) > 0:
                        axes[1].hist(
                            deployed_temps,
                            bins=30,
                            alpha=0.6,
                            label=f"{label} (deployed)",
                            color=color,
                            density=True,
                        )
                else:
                    axes[1].hist(
                        temp_data.values,
                        bins=30,
                        alpha=0.6,
                        label=label,
                        color=color,
                        density=True,
                    )

    # Plot 3: Temperature difference (2m - 1m) if we have both heights
    if sensors_1m and sensors_2m:
        # Find matching sensors by looking for similar time periods
        for sensor_2m in sensors_2m:
            ds_2m = sensor_2m["dataset"]
            temp_2m = ds_2m["temp_c"].dropna("datetime")

            for sensor_1m in sensors_1m:
                ds_1m = sensor_1m["dataset"]
                temp_1m = ds_1m["temp_c"].dropna("datetime")

                # Find overlapping time period
                start_time = max(
                    temp_2m.datetime.min().values, temp_1m.datetime.min().values
                )
                end_time = min(
                    temp_2m.datetime.max().values, temp_1m.datetime.max().values
                )

                if start_time < end_time:
                    # Interpolate both to common time grid
                    common_times = pd.date_range(start_time, end_time, freq="10min")

                    temp_2m_interp = temp_2m.interp(
                        datetime=common_times, method="linear"
                    )
                    temp_1m_interp = temp_1m.interp(
                        datetime=common_times, method="linear"
                    )

                    # Calculate difference (2m - 1m)
                    temp_diff = temp_2m_interp - temp_1m_interp
                    temp_diff = temp_diff.dropna("datetime")

                    if len(temp_diff) > 0:
                        label_diff = f"2m({sensor_2m['sensor_id']}) - 1m({sensor_1m['sensor_id']})"

                        if use_csv_masking:
                            # Apply deployment masking to difference data
                            csv_filename_2m = sensor_2m["file"].replace(".nc", ".csv")
                            csv_filename_1m = sensor_1m["file"].replace(".nc", ".csv")

                            # Get deployment masks for both sensors
                            deployed_2m = mask_from_csv_deployment_periods(
                                temp_2m_interp.values,
                                common_times,
                                csv_filename_2m,
                                csv_deployment_path,
                            )
                            deployed_1m = mask_from_csv_deployment_periods(
                                temp_1m_interp.values,
                                common_times,
                                csv_filename_1m,
                                csv_deployment_path,
                            )

                            # Both sensors must be deployed
                            deployed_both = deployed_2m & deployed_1m

                            # Create masked difference data
                            temp_diff_masked = temp_diff.values.copy()
                            temp_diff_masked[~deployed_both] = np.nan

                            axes[2].plot(
                                temp_diff.datetime,
                                temp_diff_masked,
                                label=f"{label_diff} (deployed)",
                                alpha=0.7,
                                linewidth=1,
                            )
                        else:
                            axes[2].plot(
                                temp_diff.datetime,
                                temp_diff.values,
                                label=label_diff,
                                alpha=0.7,
                                linewidth=1,
                            )

                        # Shade areas where 2m > 1m (inverted lapse rate)
                        inverted_mask = temp_diff.values > 0
                        if np.any(inverted_mask):
                            axes[2].fill_between(
                                temp_diff.datetime,
                                temp_diff.values,
                                0,
                                where=inverted_mask,
                                alpha=0.3,
                                color="red",
                                label="Inverted (2m > 1m)",
                            )
                        break  # Only plot one pair to avoid clutter

        # Add 0-degree reference line for temperature difference
        axes[2].axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)

    # Add 0-degree reference lines to temperature plots
    axes[0].axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)

    # Format subplots
    masking_suffix = " (CSV Deployment Masking)" if use_csv_masking else ""
    axes[0].set_title(f"Temperature Time Series{masking_suffix}")
    axes[0].set_ylabel("Temperature (°C)")
    axes[0].legend(loc="upper right", fontsize=8)
    axes[0].grid(True, alpha=0.3)

    axes[1].set_title(f"Temperature Distribution{masking_suffix}")
    axes[1].set_xlabel("Temperature (°C)")
    axes[1].set_ylabel("Density")
    axes[1].legend(loc="upper right", fontsize=8)
    axes[1].grid(True, alpha=0.3)

    axes[2].set_title(f"Temperature Difference (2m - 1m){masking_suffix}")
    axes[2].set_xlabel("Date")
    axes[2].set_ylabel("Temperature Difference (°C)")
    axes[2].legend(loc="upper right", fontsize=8)
    axes[2].grid(True, alpha=0.3)

    # Format date labels to reduce overlap
    import matplotlib.dates as mdates

    for ax in [axes[0], axes[2]]:
        ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
        ax.tick_params(axis="x", rotation=45)

    # Adjust layout and save
    plt.tight_layout()

    # Save plot
    safe_site_name = "".join(
        c for c in site_name if c.isalnum() or c in (" ", "-", "_")
    ).rstrip()
    output_file = output_dir / f"{safe_site_name}_analysis.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()


def create_overview_plot(site_data, output_dir, csv_deployment_path, use_csv_masking):
    """Create an overview plot showing all sites"""
    import matplotlib.dates as mdates

    # Calculate number of rows and columns for subplots
    n_sites = len(site_data)
    n_cols = min(2, n_sites)
    n_rows = (n_sites + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(20, 4 * n_rows))
    masking_suffix = " (CSV Deployment Masking)" if use_csv_masking else ""
    fig.suptitle(
        f"Temperature Overview - All Sites{masking_suffix}",
        fontsize=16,
        fontweight="bold",
    )

    # Handle case where we have only one subplot
    if n_sites == 1:
        axes = [axes]
    elif n_rows == 1 and n_cols > 1:
        axes = axes.reshape(1, -1)
    elif n_cols == 1:
        axes = axes.reshape(-1, 1)

    site_names = list(site_data.keys())

    for i, site_name in enumerate(site_names):
        if n_rows == 1 and n_cols == 1:
            ax = axes
        elif n_rows == 1:
            ax = axes[i]
        elif n_cols == 1:
            ax = axes[i]
        else:
            row = i // n_cols
            col = i % n_cols
            ax = axes[row, col]

        site_sensors = site_data[site_name]
        colors = plt.cm.Set1(np.linspace(0, 1, len(site_sensors)))

        for j, sensor_info in enumerate(site_sensors):
            ds = sensor_info["dataset"]
            height = sensor_info["height"]
            sensor_id = sensor_info["sensor_id"]

            if "temp_c" in ds.data_vars:
                temp_data = ds["temp_c"].dropna("datetime")
                if len(temp_data) > 0:
                    label = f"{sensor_id}" + (
                        f" ({height})" if height != "Unknown" else ""
                    )

                    if use_csv_masking:
                        # Apply CSV deployment masking
                        filename = sensor_info["file"]
                        csv_filename = filename.replace(".nc", ".csv")
                        deployment_mask = mask_from_csv_deployment_periods(
                            temp_data.values,
                            temp_data.datetime,
                            csv_filename,
                            csv_deployment_path,
                        )

                        # Plot all data in light color
                        ax.plot(
                            temp_data.datetime,
                            temp_data.values,
                            color=colors[j],
                            alpha=0.3,
                            linewidth=0.5,
                            label=f"{label} (all)",
                        )

                        # Plot deployed data in full color
                        deployed_data = temp_data.values.copy()
                        deployed_data[~deployment_mask] = np.nan
                        ax.plot(
                            temp_data.datetime,
                            deployed_data,
                            color=colors[j],
                            alpha=0.8,
                            linewidth=1,
                            label=f"{label} (deployed)",
                        )
                    else:
                        ax.plot(
                            temp_data.datetime,
                            temp_data.values,
                            label=label,
                            color=colors[j],
                            alpha=0.7,
                            linewidth=1,
                        )

        # Add 0-degree reference line
        ax.axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)

        ax.set_title(f"{site_name}")
        ax.set_ylabel("Temperature (°C)")
        ax.grid(True, alpha=0.3)
        ax.legend(fontsize=8, loc="upper right")

        # Format date labels
        ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
        ax.tick_params(axis="x", rotation=45)

    # Hide empty subplots
    if n_sites < n_rows * n_cols:
        for i in range(n_sites, n_rows * n_cols):
            if n_rows == 1 and n_cols > 1:
                axes[i].set_visible(False)
            elif n_cols == 1:
                axes[i].set_visible(False)
            else:
                row = i // n_cols
                col = i % n_cols
                axes[row, col].set_visible(False)

    plt.tight_layout()

    # Save overview plot
    output_file = output_dir / "all_sites_temperature_overview.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()


if __name__ == "__main__":
    main()
