#!/usr/bin/env python3
"""
pca_analysis.py

In-depth Principal Component Analysis of temperature sensor data across sites.
Each sensor becomes a feature, with site_id and height as initial dimensions.

Author: Generated by Claude Code
Created: 2025-07-28
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns
from pathlib import Path
from tqdm import tqdm
import warnings
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    """Main function to run PCA analysis on temperature sensor data"""
    
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"
    
    print("=== Temperature Sensor PCA Analysis ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")
    
    # Create output directory if it doesn't exist
    output_dir.mkdir(exist_ok=True)
    
    # Check if CSV deployment file exists
    use_csv_masking = False  # Temporarily disable CSV masking due to date issues
    if csv_deployment_path.exists():
        print("Found deployment periods CSV - but disabling due to date mismatch")
    else:
        print("No deployment periods CSV found - using automatic detection only")
    
    # Load and organize sensor data
    sensor_data = load_sensor_data(processed_dir, csv_deployment_path, use_csv_masking)
    
    if not sensor_data:
        print("No valid sensor data found!")
        return
    
    print(f"\nLoaded {len(sensor_data)} sensors for PCA analysis")
    
    # Create time-aligned temperature matrix
    temp_matrix, sensor_info, time_index = create_temperature_matrix(sensor_data)
    
    if temp_matrix is None or sensor_info is None or time_index is None:
        print("Could not create temperature matrix!")
        return
    
    print(f"Temperature matrix shape: {temp_matrix.shape}")
    print(f"Time range: {time_index[0]} to {time_index[-1]}")
    
    # Perform PCA analysis
    pca_results = perform_pca_analysis(temp_matrix, sensor_info)
    
    # Create comprehensive visualizations
    create_pca_visualizations(pca_results, sensor_info, time_index, output_dir)
    
    # Save results to files
    save_pca_results(pca_results, sensor_info, time_index, output_dir)
    
    print(f"\nPCA analysis complete! Results saved to: {output_dir}")


def load_sensor_data(processed_dir, csv_deployment_path, use_csv_masking):
    """Load and organize sensor data from NetCDF files"""
    
    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")
    
    if not netcdf_files:
        return {}
    
    sensor_data = {}
    
    for nc_file in tqdm(netcdf_files, desc="Loading sensor datasets"):
        try:
            ds = xr.open_dataset(nc_file)
            
            # Extract metadata
            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")
            
            # Create unique sensor identifier
            sensor_key = f"{site_name}_{sensor_height}_{sensor_id}"
            
            # Get temperature data
            temp_data = ds["temp_c"].dropna("datetime")
            
            if len(temp_data) == 0:
                print(f"No valid temperature data for {sensor_key}")
                continue
            
            # Skip data from before 2025
            if temp_data.datetime.min().values < pd.Timestamp("2025-01-01"):
                print(f"Skipping {sensor_key} - data from before 2025")
                continue
            
            # Apply deployment masking if available
            deployed_mask = None
            if use_csv_masking:
                csv_filename = find_matching_csv_filename(
                    sensor_id, site_name, sensor_height, csv_deployment_path
                )
                
                if csv_filename:
                    try:
                        deployed_mask = mask_from_csv_deployment_periods(
                            temp_data.values, 
                            temp_data.datetime.values, 
                            csv_filename, 
                            csv_deployment_path
                        )
                    except Exception as e:
                        print(f"Could not apply CSV masking for {sensor_key}: {e}")
            
            # Store sensor information
            sensor_data[sensor_key] = {
                "temperature": temp_data,
                "site_name": site_name,
                "sensor_height": sensor_height,
                "sensor_id": sensor_id,
                "deployed_mask": deployed_mask,
                "file": nc_file.name
            }
            
        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue
    
    return sensor_data


def create_temperature_matrix(sensor_data):
    """Create time-aligned temperature matrix with sensors as features"""
    
    if not sensor_data:
        return None, None, None
    
    # Find common time range across all sensors
    all_start_times = []
    all_end_times = []
    
    for sensor_key, data in sensor_data.items():
        temp_data = data["temperature"]
        all_start_times.append(temp_data.datetime.min().values)
        all_end_times.append(temp_data.datetime.max().values)
    
    print("Time range analysis:")
    print(f"  Earliest start: {min(all_start_times)}")
    print(f"  Latest start: {max(all_start_times)}")
    print(f"  Earliest end: {min(all_end_times)}")
    print(f"  Latest end: {max(all_end_times)}")
    
    # Filter out sensors that end before the latest start time
    latest_start = max(all_start_times)
    valid_sensors = {}
    
    for sensor_key, data in sensor_data.items():
        temp_data = data["temperature"]
        sensor_end = temp_data.datetime.max().values
        if sensor_end >= latest_start:
            valid_sensors[sensor_key] = data
        else:
            print(f"Excluding {sensor_key} - ends before latest start ({sensor_end} < {latest_start})")
    
    if not valid_sensors:
        print("No sensors with overlapping data!")
        return None, None, None
    
    # Recalculate time ranges with valid sensors only
    valid_starts = []
    valid_ends = []
    for sensor_key, data in valid_sensors.items():
        temp_data = data["temperature"]
        valid_starts.append(temp_data.datetime.min().values)
        valid_ends.append(temp_data.datetime.max().values)
    
    # Use overlapping time period
    common_start = max(valid_starts)
    common_end = min(valid_ends)
    
    print("Valid sensors time analysis:")
    print(f"  Common period: {common_start} to {common_end}")
    
    if common_start >= common_end:
        print("No overlapping time period found across valid sensors!")
        return None, None, None
    
    # Use valid sensors for matrix creation
    sensor_data = valid_sensors
    
    print(f"Common time range: {common_start} to {common_end}")
    
    # Create common time grid (hourly intervals)
    time_index = pd.date_range(common_start, common_end, freq="1H")
    
    # Initialize temperature matrix
    n_times = len(time_index)
    n_sensors = len(sensor_data)
    temp_matrix = np.full((n_times, n_sensors), np.nan)
    
    # Create sensor info dataframe
    sensor_info = []
    
    for i, (sensor_key, data) in enumerate(sensor_data.items()):
        # Interpolate to common time grid
        temp_data = data["temperature"]
        temp_interp = temp_data.interp(datetime=time_index, method="linear")
        
        # Apply deployment mask if available
        if data["deployed_mask"] is not None:
            # Create mask for common time grid
            deployed_interp = np.interp(
                time_index.astype(np.int64),
                temp_data.datetime.astype(np.int64),
                data["deployed_mask"].astype(float)
            ) > 0.5
            
            # Mask non-deployed periods
            temp_interp = temp_interp.where(deployed_interp)
        
        temp_matrix[:, i] = temp_interp.values
        
        # Store sensor metadata
        sensor_info.append({
            "sensor_key": sensor_key,
            "site_name": data["site_name"],
            "sensor_height": data["sensor_height"],
            "sensor_id": data["sensor_id"],
            "column_index": i
        })
    
    sensor_info_df = pd.DataFrame(sensor_info)
    
    return temp_matrix, sensor_info_df, time_index


def perform_pca_analysis(temp_matrix, sensor_info):
    """Perform comprehensive PCA analysis on temperature data"""
    
    print("\nPerforming PCA analysis...")
    
    # Handle missing values with imputation
    imputer = SimpleImputer(strategy='mean')
    temp_matrix_imputed = imputer.fit_transform(temp_matrix)
    
    # Standardize the data (important for PCA)
    scaler = StandardScaler()
    temp_matrix_scaled = scaler.fit_transform(temp_matrix_imputed)
    
    # Perform PCA
    n_components = min(temp_matrix_scaled.shape) - 1  # Keep all meaningful components
    pca = PCA(n_components=n_components)
    principal_components = pca.fit_transform(temp_matrix_scaled)
    
    # Calculate additional metrics
    explained_variance_ratio = pca.explained_variance_ratio_
    cumulative_variance = np.cumsum(explained_variance_ratio)
    
    # Get loadings (components)
    loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
    
    print("PCA Results:")
    print(f"  Number of components: {n_components}")
    print(f"  Variance explained by PC1: {explained_variance_ratio[0]:.1%}")
    print(f"  Variance explained by PC2: {explained_variance_ratio[1]:.1%}")
    print(f"  Cumulative variance (PC1+PC2): {cumulative_variance[1]:.1%}")
    
    # Find number of components explaining 95% of variance
    n_95_percent = np.argmax(cumulative_variance >= 0.95) + 1
    print(f"  Components for 95% variance: {n_95_percent}")
    
    return {
        "pca": pca,
        "principal_components": principal_components,
        "loadings": loadings,
        "explained_variance_ratio": explained_variance_ratio,
        "cumulative_variance": cumulative_variance,
        "temp_matrix_scaled": temp_matrix_scaled,
        "scaler": scaler,
        "imputer": imputer,
        "n_95_percent": n_95_percent
    }


def create_pca_visualizations(pca_results, sensor_info, time_index, output_dir):
    """Create comprehensive PCA visualizations"""
    
    print("\nCreating PCA visualizations...")
    
    # Extract results
    pc_scores = pca_results["principal_components"]
    loadings = pca_results["loadings"]
    explained_var = pca_results["explained_variance_ratio"]
    cumulative_var = pca_results["cumulative_variance"]
    
    # Create main figure with subplots
    plt.figure(figsize=(20, 16))
    
    # 1. Scree plot
    plt.subplot(2, 3, 1)
    n_components = len(explained_var)
    plt.plot(range(1, n_components + 1), explained_var * 100, 'bo-', linewidth=2, markersize=8)
    plt.plot(range(1, n_components + 1), cumulative_var * 100, 'ro-', linewidth=2, markersize=8)
    plt.axhline(y=95, color='gray', linestyle='--', alpha=0.7)
    plt.xlabel('Principal Component')
    plt.ylabel('Variance Explained (%)')
    plt.title('Scree Plot: Variance Explained by Each PC')
    plt.legend(['Individual', 'Cumulative', '95% Threshold'])
    plt.grid(True, alpha=0.3)
    
    # 2. PC1 vs PC2 score plot colored by site
    plt.subplot(2, 3, 2)
    sites = sensor_info['site_name'].unique()
    colors = cm.get_cmap('Set3')(np.linspace(0, 1, len(sites)))
    
    for i, site in enumerate(sites):
        site_mask = sensor_info['site_name'] == site
        site_indices = sensor_info[site_mask]['column_index'].values
        plt.scatter(pc_scores[site_indices, 0], pc_scores[site_indices, 1], 
                   c=[colors[i]], label=site, s=60, alpha=0.7)
    
    plt.xlabel(f'PC1 ({explained_var[0]:.1%} variance)')
    plt.ylabel(f'PC2 ({explained_var[1]:.1%} variance)')
    plt.title('PCA Score Plot: Sensors by Site')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, alpha=0.3)
    
    # 3. PC1 vs PC2 score plot colored by height
    plt.subplot(2, 3, 3)
    heights = sensor_info['sensor_height'].unique()
    height_colors = cm.get_cmap('viridis')(np.linspace(0, 1, len(heights)))
    
    for i, height in enumerate(heights):
        height_mask = sensor_info['sensor_height'] == height
        height_indices = sensor_info[height_mask]['column_index'].values
        plt.scatter(pc_scores[height_indices, 0], pc_scores[height_indices, 1],
                   c=[height_colors[i]], label=height, s=60, alpha=0.7)
    
    plt.xlabel(f'PC1 ({explained_var[0]:.1%} variance)')
    plt.ylabel(f'PC2 ({explained_var[1]:.1%} variance)')
    plt.title('PCA Score Plot: Sensors by Height')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    # 4. Loadings plot for PC1
    plt.subplot(2, 3, 4)
    sensor_labels = [f"{row['site_name']}_{row['sensor_height']}" for _, row in sensor_info.iterrows()]
    y_pos = np.arange(len(sensor_labels))
    
    colors_pc1 = ['red' if x > 0 else 'blue' for x in loadings[:, 0]]
    plt.barh(y_pos, loadings[:, 0], color=colors_pc1, alpha=0.7)
    plt.yticks(y_pos, sensor_labels, fontsize=8)
    plt.xlabel('PC1 Loading')
    plt.title('PC1 Loadings by Sensor')
    plt.grid(True, alpha=0.3)
    
    # 5. Loadings plot for PC2
    plt.subplot(2, 3, 5)
    colors_pc2 = ['red' if x > 0 else 'blue' for x in loadings[:, 1]]
    plt.barh(y_pos, loadings[:, 1], color=colors_pc2, alpha=0.7)
    plt.yticks(y_pos, sensor_labels, fontsize=8)
    plt.xlabel('PC2 Loading')
    plt.title('PC2 Loadings by Sensor')
    plt.grid(True, alpha=0.3)
    
    # 6. Biplot (PC1 vs PC2 with loadings vectors)
    plt.subplot(2, 3, 6)
    
    # Plot scores
    for i, site in enumerate(sites):
        site_mask = sensor_info['site_name'] == site
        site_indices = sensor_info[site_mask]['column_index'].values
        plt.scatter(pc_scores[site_indices, 0], pc_scores[site_indices, 1],
                   c=[colors[i]], label=site, s=40, alpha=0.6)
    
    # Plot loading vectors
    scale_factor = 3  # Scale loading vectors for visibility
    for i, (_, row) in enumerate(sensor_info.iterrows()):
        plt.arrow(0, 0, loadings[i, 0] * scale_factor, loadings[i, 1] * scale_factor,
                 head_width=0.05, head_length=0.05, fc='black', ec='black', alpha=0.5)
        plt.text(loadings[i, 0] * scale_factor * 1.1, loadings[i, 1] * scale_factor * 1.1,
                f"{row['site_name']}_{row['sensor_height']}", fontsize=6, ha='center')
    
    plt.xlabel(f'PC1 ({explained_var[0]:.1%} variance)')
    plt.ylabel(f'PC2 ({explained_var[1]:.1%} variance)')
    plt.title('PCA Biplot: Scores + Loadings')
    plt.grid(True, alpha=0.3)
    
    plt.tight_layout()
    plt.savefig(output_dir / "pca_comprehensive_analysis.png", dpi=300, bbox_inches='tight')
    plt.close()
    
    # Create additional detailed plots
    create_detailed_loadings_heatmap(loadings, sensor_info, explained_var, output_dir)
    create_pca_time_series(pca_results, sensor_info, output_dir)


def create_detailed_loadings_heatmap(loadings, sensor_info, explained_var, output_dir):
    """Create detailed heatmap of PCA loadings"""
    
    # Prepare data for heatmap
    n_components_to_show = min(10, loadings.shape[1])
    loadings_subset = loadings[:, :n_components_to_show]
    
    # Create labels
    sensor_labels = [f"{row['site_name']}_{row['sensor_height']}" 
                    for _, row in sensor_info.iterrows()]
    pc_labels = [f"PC{i+1}\n({explained_var[i]:.1%})" 
                for i in range(n_components_to_show)]
    
    # Create heatmap
    plt.figure(figsize=(12, max(8, len(sensor_labels) * 0.3)))
    sns.heatmap(loadings_subset, 
                xticklabels=pc_labels,
                yticklabels=sensor_labels,
                cmap='RdBu_r', 
                center=0,
                annot=True if len(sensor_labels) < 20 else False,
                fmt='.2f',
                cbar_kws={'label': 'Loading Value'})
    
    plt.title('PCA Loadings Heatmap: Sensor Contributions to Principal Components')
    plt.xlabel('Principal Components')
    plt.ylabel('Sensors')
    plt.tight_layout()
    plt.savefig(output_dir / "pca_loadings_heatmap.png", dpi=300, bbox_inches='tight')
    plt.close()


def create_pca_time_series(pca_results, sensor_info, output_dir):
    """Create time series plots of principal component scores"""
    
    # This would require the time index, which we'd need to pass through
    # For now, just create a placeholder showing this is where time series would go
    
    pc_scores = pca_results["principal_components"]
    explained_var = pca_results["explained_variance_ratio"]
    
    # Create time series plots for first few PCs
    fig, axes = plt.subplots(3, 1, figsize=(15, 10))
    
    # For demonstration, plot against index (would be time in real implementation)
    time_index = np.arange(pc_scores.shape[0])
    
    for i in range(3):
        axes[i].plot(time_index, pc_scores[:, i], linewidth=1, alpha=0.8)
        axes[i].set_ylabel(f'PC{i+1} Score')
        axes[i].set_title(f'PC{i+1} Time Series ({explained_var[i]:.1%} variance)')
        axes[i].grid(True, alpha=0.3)
    
    axes[-1].set_xlabel('Time Index')
    plt.suptitle('Principal Component Time Series')
    plt.tight_layout()
    plt.savefig(output_dir / "pca_time_series.png", dpi=300, bbox_inches='tight')
    plt.close()


def save_pca_results(pca_results, sensor_info, time_index, output_dir):
    """Save PCA results to CSV files"""
    
    print("\nSaving PCA results...")
    
    # Save explained variance
    variance_df = pd.DataFrame({
        'PC': [f'PC{i+1}' for i in range(len(pca_results['explained_variance_ratio']))],
        'Explained_Variance_Ratio': pca_results['explained_variance_ratio'],
        'Cumulative_Variance': pca_results['cumulative_variance']
    })
    variance_df.to_csv(output_dir / "pca_explained_variance.csv", index=False)
    
    # Save loadings with sensor information
    loadings_df = sensor_info.copy()
    for i in range(pca_results['loadings'].shape[1]):
        loadings_df[f'PC{i+1}_loading'] = pca_results['loadings'][:, i]
    loadings_df.to_csv(output_dir / "pca_loadings.csv", index=False)
    
    # Save principal component scores (would include time in real implementation)
    pc_scores_df = pd.DataFrame(pca_results['principal_components'])
    pc_scores_df.columns = [f'PC{i+1}' for i in range(pc_scores_df.shape[1])]
    pc_scores_df['time_index'] = range(len(pc_scores_df))  # Placeholder for time
    pc_scores_df.to_csv(output_dir / "pca_scores.csv", index=False)
    
    # Save summary statistics
    summary = {
        'total_sensors': len(sensor_info),
        'total_components': len(pca_results['explained_variance_ratio']),
        'pc1_variance': pca_results['explained_variance_ratio'][0],
        'pc2_variance': pca_results['explained_variance_ratio'][1],
        'pc1_pc2_cumulative': pca_results['cumulative_variance'][1],
        'components_95_percent': pca_results['n_95_percent']
    }
    
    summary_df = pd.DataFrame([summary])
    summary_df.to_csv(output_dir / "pca_summary.csv", index=False)
    
    print("PCA results saved:")
    print("  - Explained variance: pca_explained_variance.csv")
    print("  - Loadings: pca_loadings.csv") 
    print("  - Scores: pca_scores.csv")
    print("  - Summary: pca_summary.csv")


if __name__ == "__main__":
    main()