#!/usr/bin/env python3
"""
site_histogram_cluster_analysis.py

Comprehensive analysis comparing histogram shapes and performing cluster analysis
among temperature sensor sites.

Author: Generated by Claude Code
Created: 2025-07-28
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy.stats import pearsonr, ks_2samp, wasserstein_distance
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster
from scipy.spatial.distance import pdist, squareform
from sklearn.cluster import KMeans, DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
import warnings

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    guess_deployment_period,
    mask_from_csv_deployment_periods,
    apply_csv_deployment_mask,
    find_matching_csv_filename,
)


def main():
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    print("=== Site Histogram & Cluster Analysis ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - using automatic detection only")

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("No NetCDF files found!")
        return

    # Load and organize datasets by site
    site_data = load_site_data(netcdf_files, use_csv_masking, csv_deployment_path)
    
    if not site_data:
        print("No valid site data found!")
        return

    print(f"\nLoaded {len(site_data)} sites with valid temperature data")
    for site_name, data in site_data.items():
        print(f"  - {site_name}: {len(data['temp_deployed'])} deployed measurements")

    # Perform histogram shape analysis
    print("\n=== Histogram Shape Analysis ===")
    histogram_features = analyze_histogram_shapes(site_data)
    
    # Perform cluster analysis
    print("\n=== Cluster Analysis ===")
    cluster_results = perform_cluster_analysis(histogram_features)
    
    # Create visualizations
    print("\n=== Creating Visualizations ===")
    create_histogram_comparison_plot(site_data, histogram_features, output_dir)
    create_cluster_visualization_plot(histogram_features, cluster_results, output_dir)
    create_detailed_cluster_plot(site_data, cluster_results, output_dir)
    
    # Save results
    save_analysis_results(histogram_features, cluster_results, output_dir)
    
    print(f"\nAnalysis complete! Results saved to: {output_dir}")


def load_site_data(netcdf_files, use_csv_masking, csv_deployment_path):
    """Load and process temperature data from all sites"""
    
    site_data = {}
    
    for nc_file in tqdm(netcdf_files, desc="Loading site data"):
        try:
            ds = xr.open_dataset(nc_file)
            
            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")
            
            # Create unique site identifier
            if site_name != "Unknown":
                site_key = f"{site_name}_{sensor_height}"
            else:
                site_key = f"Sensor_{sensor_id}_{sensor_height}"
            
            # Get temperature data
            temp_data = ds["temp_c"].dropna("datetime")
            if len(temp_data) < 100:  # Skip sites with too little data
                continue
                
            times = temp_data.datetime.values
            temps = temp_data.values
            
            # Apply deployment masking if available
            if use_csv_masking:
                original_csv_filename = ds.attrs.get("original_filename", nc_file.name)
                csv_filename = find_matching_csv_filename(
                    sensor_id, site_name, sensor_height, csv_deployment_path
                )
                
                if csv_filename:
                    deployed_mask = mask_from_csv_deployment_periods(
                        temps, times, csv_filename, csv_deployment_path
                    )
                else:
                    # Fallback to automatic detection
                    deployed_period = guess_deployment_period(temps)
                    deployed_mask = np.zeros(len(temps), dtype=bool)
                    if deployed_period["start_idx"] is not None and deployed_period["end_idx"] is not None:
                        deployed_mask[deployed_period["start_idx"]:deployed_period["end_idx"]] = True
            else:
                # Use automatic detection
                deployed_period = guess_deployment_period(temps)
                deployed_mask = np.zeros(len(temps), dtype=bool)
                if deployed_period["start_idx"] is not None and deployed_period["end_idx"] is not None:
                    deployed_mask[deployed_period["start_idx"]:deployed_period["end_idx"]] = True
            
            # Store site data
            temp_deployed = temps[deployed_mask]
            if len(temp_deployed) > 50:  # Minimum deployed data requirement
                site_data[site_key] = {
                    "site_name": site_name,
                    "sensor_height": sensor_height,
                    "sensor_id": sensor_id,
                    "temp_all": temps,
                    "temp_deployed": temp_deployed,
                    "times_all": times,
                    "times_deployed": times[deployed_mask],
                    "deployed_mask": deployed_mask,
                    "elevation": ds.attrs.get("elevation", np.nan),
                    "latitude": ds.attrs.get("latitude", np.nan),
                    "longitude": ds.attrs.get("longitude", np.nan),
                }
                
        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue
    
    return site_data


def analyze_histogram_shapes(site_data):
    """Analyze histogram shapes and extract features for each site"""
    
    histogram_features = {}
    
    # Define common bin edges for all histograms
    all_temps = np.concatenate([data['temp_deployed'] for data in site_data.values()])
    temp_min, temp_max = np.percentile(all_temps, [1, 99])  # Use 1st-99th percentiles
    bin_edges = np.linspace(temp_min, temp_max, 51)  # 50 bins
    bin_centers = (bin_edges[:-1] + bin_edges[1:]) / 2
    
    print(f"Using temperature range: {temp_min:.1f}°C to {temp_max:.1f}°C with {len(bin_centers)} bins")
    
    for site_key, data in tqdm(site_data.items(), desc="Analyzing histogram shapes"):
        temp_deployed = data['temp_deployed']
        
        # Calculate histogram
        hist_counts, _ = np.histogram(temp_deployed, bins=bin_edges)
        hist_density = hist_counts / np.sum(hist_counts)  # Normalize to probability density
        
        # Calculate basic statistics
        temp_mean = np.mean(temp_deployed)
        temp_std = np.std(temp_deployed)
        temp_median = np.median(temp_deployed)
        temp_skew = calculate_skewness(temp_deployed)
        temp_kurtosis = calculate_kurtosis(temp_deployed)
        
        # Calculate percentiles
        temp_p10 = np.percentile(temp_deployed, 10)
        temp_p90 = np.percentile(temp_deployed, 90)
        temp_range = temp_p90 - temp_p10
        
        # Calculate histogram shape features
        peak_temp = bin_centers[np.argmax(hist_density)]  # Mode
        hist_width = calculate_histogram_width(bin_centers, hist_density)
        multimodality = calculate_multimodality_index(hist_density)
        
        # Calculate temperature gradient metrics
        daily_temp_range = calculate_daily_temperature_range(data['times_deployed'], temp_deployed)
        
        histogram_features[site_key] = {
            'site_name': data['site_name'],
            'sensor_height': data['sensor_height'],
            'elevation': data['elevation'],
            'latitude': data['latitude'],
            'longitude': data['longitude'],
            'n_measurements': len(temp_deployed),
            
            # Histogram data
            'bin_centers': bin_centers,
            'hist_density': hist_density,
            'hist_counts': hist_counts,
            
            # Basic statistics
            'mean_temp': temp_mean,
            'std_temp': temp_std,
            'median_temp': temp_median,
            'skewness': temp_skew,
            'kurtosis': temp_kurtosis,
            
            # Percentiles and range
            'p10_temp': temp_p10,
            'p90_temp': temp_p90,
            'temp_range_p10_p90': temp_range,
            
            # Shape features
            'mode_temp': peak_temp,
            'hist_width': hist_width,
            'multimodality_index': multimodality,
            
            # Temporal features
            'daily_temp_range_mean': np.mean(daily_temp_range) if len(daily_temp_range) > 0 else np.nan,
            'daily_temp_range_std': np.std(daily_temp_range) if len(daily_temp_range) > 0 else np.nan,
        }
    
    return histogram_features


def calculate_skewness(data):
    """Calculate skewness of temperature distribution"""
    mean_val = np.mean(data)
    std_val = np.std(data)
    if std_val == 0:
        return 0
    return np.mean(((data - mean_val) / std_val) ** 3)


def calculate_kurtosis(data):
    """Calculate kurtosis of temperature distribution"""
    mean_val = np.mean(data)
    std_val = np.std(data)
    if std_val == 0:
        return 0
    return np.mean(((data - mean_val) / std_val) ** 4) - 3


def calculate_histogram_width(bin_centers, hist_density):
    """Calculate effective width of histogram distribution"""
    # Find bins with >10% of peak density
    peak_density = np.max(hist_density)
    significant_bins = hist_density > 0.1 * peak_density
    
    if np.sum(significant_bins) == 0:
        return np.nan
    
    # Calculate width as span of significant bins
    min_temp = np.min(bin_centers[significant_bins])
    max_temp = np.max(bin_centers[significant_bins])
    return max_temp - min_temp


def calculate_multimodality_index(hist_density):
    """Calculate a simple multimodality index based on local maxima"""
    # Find local maxima (peaks)
    peaks = []
    for i in range(1, len(hist_density) - 1):
        if hist_density[i] > hist_density[i-1] and hist_density[i] > hist_density[i+1]:
            peaks.append(i)
    
    # Count significant peaks (>10% of global maximum)
    if len(peaks) == 0:
        return 0
    
    peak_heights = hist_density[peaks]
    max_height = np.max(hist_density)
    significant_peaks = np.sum(peak_heights > 0.1 * max_height)
    
    return significant_peaks


def calculate_daily_temperature_range(times, temps):
    """Calculate daily temperature ranges"""
    # Convert to pandas for easier date grouping
    df = pd.DataFrame({'datetime': pd.to_datetime(times), 'temp': temps})
    df.set_index('datetime', inplace=True)
    
    # Group by date and calculate daily range
    daily_stats = df.groupby(df.index.date)['temp'].agg(['min', 'max'])
    daily_ranges = daily_stats['max'] - daily_stats['min']
    
    return daily_ranges.values


def perform_cluster_analysis(histogram_features):
    """Perform cluster analysis on histogram features"""
    
    # Prepare feature matrix
    site_names = list(histogram_features.keys())
    
    # Select features for clustering
    feature_names = [
        'mean_temp', 'std_temp', 'skewness', 'kurtosis',
        'temp_range_p10_p90', 'hist_width', 'multimodality_index',
        'daily_temp_range_mean', 'daily_temp_range_std'
    ]
    
    # Extract feature matrix
    feature_matrix = []
    valid_sites = []
    
    for site_name in site_names:
        features = histogram_features[site_name]
        feature_vector = []
        
        # Check if all features are valid (not NaN)
        all_valid = True
        for feat_name in feature_names:
            val = features[feat_name]
            if np.isnan(val):
                all_valid = False
                break
            feature_vector.append(val)
        
        if all_valid:
            feature_matrix.append(feature_vector)
            valid_sites.append(site_name)
    
    feature_matrix = np.array(feature_matrix)
    print(f"Using {len(valid_sites)} sites with complete feature data")
    print(f"Feature matrix shape: {feature_matrix.shape}")
    
    if len(valid_sites) < 3:
        print("Insufficient valid sites for clustering")
        return None
    
    # Standardize features
    scaler = StandardScaler()
    feature_matrix_scaled = scaler.fit_transform(feature_matrix)
    
    # Perform PCA for dimensionality reduction
    pca = PCA()
    pca_features = pca.fit_transform(feature_matrix_scaled)
    
    # Perform hierarchical clustering
    linkage_matrix = linkage(feature_matrix_scaled, method='ward')
    
    # Determine optimal number of clusters using elbow method for k-means
    max_k = min(10, len(valid_sites) - 1)
    k_range = range(2, max_k + 1)
    inertias = []
    
    for k in k_range:
        kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
        kmeans.fit(feature_matrix_scaled)
        inertias.append(kmeans.inertia_)
    
    # Use elbow method to select k
    optimal_k = find_elbow_point(inertias) + 2  # +2 because range starts at 2
    
    # Perform final clustering
    kmeans = KMeans(n_clusters=optimal_k, random_state=42, n_init=10)
    kmeans_labels = kmeans.fit_predict(feature_matrix_scaled)
    
    # Try hierarchical clustering with same number of clusters
    hierarchical_labels = fcluster(linkage_matrix, optimal_k, criterion='maxclust') - 1
    
    # Try DBSCAN
    dbscan = DBSCAN(eps=0.5, min_samples=2)
    dbscan_labels = dbscan.fit_predict(feature_matrix_scaled)
    
    return {
        'site_names': valid_sites,
        'feature_matrix': feature_matrix,
        'feature_matrix_scaled': feature_matrix_scaled,
        'feature_names': feature_names,
        'scaler': scaler,
        'pca': pca,
        'pca_features': pca_features,
        'linkage_matrix': linkage_matrix,
        'optimal_k': optimal_k,
        'kmeans_labels': kmeans_labels,
        'hierarchical_labels': hierarchical_labels,
        'dbscan_labels': dbscan_labels,
        'inertias': inertias,
        'k_range': list(k_range),
    }


def find_elbow_point(inertias):
    """Find elbow point in k-means inertia curve"""
    if len(inertias) < 3:
        return 0
    
    # Calculate second derivatives
    second_derivs = []
    for i in range(1, len(inertias) - 1):
        second_deriv = inertias[i-1] - 2*inertias[i] + inertias[i+1]
        second_derivs.append(second_deriv)
    
    # Find point with maximum second derivative
    if len(second_derivs) == 0:
        return 0
    
    return np.argmax(second_derivs) + 1


def create_histogram_comparison_plot(site_data, histogram_features, output_dir):
    """Create comprehensive histogram comparison plot"""
    
    fig = plt.figure(figsize=(20, 16))
    gs = gridspec.GridSpec(3, 2, height_ratios=[2, 1, 1], hspace=0.3, wspace=0.2)
    
    # Plot 1: Overlaid histograms for all sites
    ax1 = fig.add_subplot(gs[0, :])
    
    colors = plt.cm.tab20(np.linspace(0, 1, len(histogram_features)))
    
    for i, (site_name, features) in enumerate(histogram_features.items()):
        ax1.plot(features['bin_centers'], features['hist_density'], 
                alpha=0.7, linewidth=1.5, label=site_name, color=colors[i])
    
    ax1.set_xlabel('Temperature (°C)')
    ax1.set_ylabel('Probability Density')
    ax1.set_title('Temperature Distribution Comparison Across All Sites')
    ax1.grid(True, alpha=0.3)
    ax1.legend(bbox_to_anchor=(1.05, 1), loc='upper left', ncol=2, fontsize=8)
    
    # Plot 2: Statistical summary comparison
    ax2 = fig.add_subplot(gs[1, 0])
    
    # Extract statistics for plotting
    sites = list(histogram_features.keys())
    means = [histogram_features[site]['mean_temp'] for site in sites]
    stds = [histogram_features[site]['std_temp'] for site in sites]
    elevations = [histogram_features[site]['elevation'] for site in sites]
    
    # Filter out sites with missing elevation data
    valid_elev = [(i, sites[i], means[i], stds[i], elevations[i]) 
                  for i in range(len(sites)) if not np.isnan(elevations[i])]
    
    if valid_elev:
        indices, site_names_elev, means_elev, stds_elev, elevs = zip(*valid_elev)
        scatter = ax2.scatter(means_elev, stds_elev, c=elevs, s=50, alpha=0.7, cmap='viridis')
        
        # Add site labels
        for i, (mean, std, site) in enumerate(zip(means_elev, stds_elev, site_names_elev)):
            ax2.annotate(site, (mean, std), xytext=(5, 5), textcoords='offset points', 
                        fontsize=6, alpha=0.7)
        
        ax2.set_xlabel('Mean Temperature (°C)')
        ax2.set_ylabel('Temperature Std Dev (°C)')
        ax2.set_title('Temperature Statistics vs Elevation')
        ax2.grid(True, alpha=0.3)
        
        cbar = plt.colorbar(scatter, ax=ax2)
        cbar.set_label('Elevation (m)')
    
    # Plot 3: Shape characteristics
    ax3 = fig.add_subplot(gs[1, 1])
    
    skewness = [histogram_features[site]['skewness'] for site in sites]
    kurtosis = [histogram_features[site]['kurtosis'] for site in sites]
    
    ax3.scatter(skewness, kurtosis, alpha=0.7, s=50)
    
    for i, site in enumerate(sites):
        ax3.annotate(site, (skewness[i], kurtosis[i]), xytext=(5, 5), 
                    textcoords='offset points', fontsize=6, alpha=0.7)
    
    ax3.axvline(x=0, color='gray', linestyle='--', alpha=0.5)
    ax3.axhline(y=0, color='gray', linestyle='--', alpha=0.5)
    ax3.set_xlabel('Skewness')
    ax3.set_ylabel('Kurtosis')
    ax3.set_title('Distribution Shape Characteristics')
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Daily temperature range analysis
    ax4 = fig.add_subplot(gs[2, 0])
    
    daily_ranges_mean = [histogram_features[site]['daily_temp_range_mean'] for site in sites]
    temp_ranges = [histogram_features[site]['temp_range_p10_p90'] for site in sites]
    
    # Filter out NaN values
    valid_ranges = [(site, daily_ranges_mean[i], temp_ranges[i]) 
                   for i, site in enumerate(sites) 
                   if not np.isnan(daily_ranges_mean[i]) and not np.isnan(temp_ranges[i])]
    
    if valid_ranges:
        site_names_range, daily_means, overall_ranges = zip(*valid_ranges)
        ax4.scatter(daily_means, overall_ranges, alpha=0.7, s=50)
        
        for i, site in enumerate(site_names_range):
            ax4.annotate(site, (daily_means[i], overall_ranges[i]), xytext=(5, 5), 
                        textcoords='offset points', fontsize=6, alpha=0.7)
        
        ax4.set_xlabel('Mean Daily Temperature Range (°C)')
        ax4.set_ylabel('Overall Temperature Range P10-P90 (°C)')
        ax4.set_title('Temperature Variability Comparison')
        ax4.grid(True, alpha=0.3)
    
    # Plot 5: Histogram width vs multimodality
    ax5 = fig.add_subplot(gs[2, 1])
    
    hist_widths = [histogram_features[site]['hist_width'] for site in sites]
    multimodality = [histogram_features[site]['multimodality_index'] for site in sites]
    
    # Filter out NaN values
    valid_shape = [(site, hist_widths[i], multimodality[i]) 
                   for i, site in enumerate(sites) 
                   if not np.isnan(hist_widths[i]) and not np.isnan(multimodality[i])]
    
    if valid_shape:
        site_names_shape, widths, multi_indices = zip(*valid_shape)
        ax5.scatter(widths, multi_indices, alpha=0.7, s=50)
        
        for i, site in enumerate(site_names_shape):
            ax5.annotate(site, (widths[i], multi_indices[i]), xytext=(5, 5), 
                        textcoords='offset points', fontsize=6, alpha=0.7)
        
        ax5.set_xlabel('Histogram Width (°C)')
        ax5.set_ylabel('Multimodality Index')
        ax5.set_title('Distribution Shape Analysis')
        ax5.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    output_file = output_dir / "site_histogram_comparison.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Histogram comparison plot saved: {output_file}")


def create_cluster_visualization_plot(histogram_features, cluster_results, output_dir):
    """Create cluster analysis visualization plot"""
    
    if cluster_results is None:
        print("No cluster results to plot")
        return
    
    fig = plt.figure(figsize=(20, 12))
    gs = gridspec.GridSpec(2, 3, hspace=0.3, wspace=0.3)
    
    site_names = cluster_results['site_names']
    feature_matrix_scaled = cluster_results['feature_matrix_scaled']
    pca_features = cluster_results['pca_features']
    
    # Plot 1: PCA visualization
    ax1 = fig.add_subplot(gs[0, 0])
    
    colors = plt.cm.tab10(cluster_results['kmeans_labels'])
    ax1.scatter(pca_features[:, 0], pca_features[:, 1], c=colors, alpha=0.7, s=50)
    
    for i, site in enumerate(site_names):
        ax1.annotate(site, (pca_features[i, 0], pca_features[i, 1]), 
                    xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)
    
    ax1.set_xlabel(f'PC1 ({cluster_results["pca"].explained_variance_ratio_[0]:.1%} variance)')
    ax1.set_ylabel(f'PC2 ({cluster_results["pca"].explained_variance_ratio_[1]:.1%} variance)')
    ax1.set_title('PCA - K-means Clusters')
    ax1.grid(True, alpha=0.3)
    
    # Plot 2: Hierarchical clustering dendrogram
    ax2 = fig.add_subplot(gs[0, 1])
    
    dendrogram(cluster_results['linkage_matrix'], labels=site_names, 
               orientation='top', ax=ax2, leaf_rotation=90, leaf_font_size=8)
    ax2.set_title('Hierarchical Clustering Dendrogram')
    ax2.set_ylabel('Distance')
    
    # Plot 3: K-means elbow plot
    ax3 = fig.add_subplot(gs[0, 2])
    
    k_range = cluster_results['k_range']
    inertias = cluster_results['inertias']
    
    ax3.plot(k_range, inertias, 'bo-', linewidth=2, markersize=6)
    ax3.axvline(x=cluster_results['optimal_k'], color='red', linestyle='--', 
                label=f'Optimal k = {cluster_results["optimal_k"]}')
    ax3.set_xlabel('Number of Clusters (k)')
    ax3.set_ylabel('Within-cluster Sum of Squares')
    ax3.set_title('K-means Elbow Plot')
    ax3.legend()
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Feature importance (PCA loadings)
    ax4 = fig.add_subplot(gs[1, 0])
    
    feature_names = cluster_results['feature_names']
    loadings = cluster_results['pca'].components_[:2].T  # First 2 components
    
    ax4.scatter(loadings[:, 0], loadings[:, 1], alpha=0.7, s=50)
    
    for i, feature in enumerate(feature_names):
        ax4.annotate(feature, (loadings[i, 0], loadings[i, 1]), 
                    xytext=(5, 5), textcoords='offset points', fontsize=8)
    
    ax4.set_xlabel('PC1 Loading')
    ax4.set_ylabel('PC2 Loading')
    ax4.set_title('Feature Loadings in PCA Space')
    ax4.grid(True, alpha=0.3)
    ax4.axhline(y=0, color='gray', linestyle='-', alpha=0.3)
    ax4.axvline(x=0, color='gray', linestyle='-', alpha=0.3)
    
    # Plot 5: Cluster comparison (K-means vs Hierarchical)
    ax5 = fig.add_subplot(gs[1, 1])
    
    kmeans_labels = cluster_results['kmeans_labels']
    hierarchical_labels = cluster_results['hierarchical_labels']
    
    # Create confusion matrix-style comparison
    unique_kmeans = np.unique(kmeans_labels)
    unique_hierarchical = np.unique(hierarchical_labels)
    
    confusion_matrix = np.zeros((len(unique_kmeans), len(unique_hierarchical)))
    
    for k_label in unique_kmeans:
        for h_label in unique_hierarchical:
            count = np.sum((kmeans_labels == k_label) & (hierarchical_labels == h_label))
            confusion_matrix[k_label, h_label] = count
    
    im = ax5.imshow(confusion_matrix, cmap='Blues', aspect='auto')
    ax5.set_xticks(range(len(unique_hierarchical)))
    ax5.set_yticks(range(len(unique_kmeans)))
    ax5.set_xticklabels([f'H{i}' for i in unique_hierarchical])
    ax5.set_yticklabels([f'K{i}' for i in unique_kmeans])
    ax5.set_xlabel('Hierarchical Clusters')
    ax5.set_ylabel('K-means Clusters')
    ax5.set_title('Cluster Method Comparison')
    
    # Add text annotations
    for i in range(len(unique_kmeans)):
        for j in range(len(unique_hierarchical)):
            text = ax5.text(j, i, int(confusion_matrix[i, j]), 
                           ha="center", va="center", color="white" if confusion_matrix[i, j] > confusion_matrix.max()/2 else "black")
    
    plt.colorbar(im, ax=ax5)
    
    # Plot 6: DBSCAN results
    ax6 = fig.add_subplot(gs[1, 2])
    
    dbscan_labels = cluster_results['dbscan_labels']
    unique_dbscan = np.unique(dbscan_labels)
    colors_dbscan = plt.cm.tab10(dbscan_labels)
    
    # Handle noise points (label -1) differently
    noise_mask = dbscan_labels == -1
    cluster_mask = dbscan_labels != -1
    
    if np.any(cluster_mask):
        ax6.scatter(pca_features[cluster_mask, 0], pca_features[cluster_mask, 1], 
                   c=colors_dbscan[cluster_mask], alpha=0.7, s=50, label='Clustered')
    
    if np.any(noise_mask):
        ax6.scatter(pca_features[noise_mask, 0], pca_features[noise_mask, 1], 
                   c='gray', alpha=0.5, s=30, marker='x', label='Noise')
    
    for i, site in enumerate(site_names):
        ax6.annotate(site, (pca_features[i, 0], pca_features[i, 1]), 
                    xytext=(5, 5), textcoords='offset points', fontsize=8, alpha=0.7)
    
    ax6.set_xlabel(f'PC1 ({cluster_results["pca"].explained_variance_ratio_[0]:.1%} variance)')
    ax6.set_ylabel(f'PC2 ({cluster_results["pca"].explained_variance_ratio_[1]:.1%} variance)')
    ax6.set_title(f'DBSCAN Clusters (n_clusters: {len(unique_dbscan[unique_dbscan >= 0])})')
    ax6.legend()
    ax6.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    output_file = output_dir / "cluster_analysis_visualization.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Cluster visualization plot saved: {output_file}")


def create_detailed_cluster_plot(site_data, cluster_results, output_dir):
    """Create detailed plot showing cluster characteristics"""
    
    if cluster_results is None:
        print("No cluster results to plot")
        return
    
    site_names = cluster_results['site_names']
    kmeans_labels = cluster_results['kmeans_labels']
    
    # Group sites by cluster
    clusters = {}
    for i, site_name in enumerate(site_names):
        cluster_id = kmeans_labels[i]
        if cluster_id not in clusters:
            clusters[cluster_id] = []
        clusters[cluster_id].append(site_name)
    
    n_clusters = len(clusters)
    fig, axes = plt.subplots(n_clusters, 2, figsize=(16, 4 * n_clusters))
    
    if n_clusters == 1:
        axes = axes.reshape(1, -1)
    
    colors = plt.cm.tab10(range(n_clusters))
    
    for cluster_id in sorted(clusters.keys()):
        row_idx = cluster_id
        cluster_sites = clusters[cluster_id]
        
        # Plot 1: Overlaid histograms for sites in this cluster
        ax1 = axes[row_idx, 0]
        
        for site_name in cluster_sites:
            if site_name in site_data:
                temp_data = site_data[site_name]['temp_deployed']
                ax1.hist(temp_data, bins=30, alpha=0.5, density=True, 
                        label=site_name, color=colors[cluster_id])
        
        ax1.set_xlabel('Temperature (°C)')
        ax1.set_ylabel('Density')
        ax1.set_title(f'Cluster {cluster_id} - Temperature Distributions')
        ax1.legend(fontsize=8)
        ax1.grid(True, alpha=0.3)
        
        # Plot 2: Time series for sites in this cluster
        ax2 = axes[row_idx, 1]
        
        for site_name in cluster_sites:
            if site_name in site_data:
                times = site_data[site_name]['times_deployed']
                temp_data = site_data[site_name]['temp_deployed']
                
                # Subsample for plotting if too many points
                if len(times) > 1000:
                    indices = np.linspace(0, len(times)-1, 1000, dtype=int)
                    times = times[indices]
                    temp_data = temp_data[indices]
                
                ax2.plot(times, temp_data, alpha=0.7, linewidth=1, 
                        label=site_name, color=colors[cluster_id])
        
        ax2.set_xlabel('Time')
        ax2.set_ylabel('Temperature (°C)')
        ax2.set_title(f'Cluster {cluster_id} - Time Series')
        ax2.legend(fontsize=8)
        ax2.grid(True, alpha=0.3)
        
        # Rotate x-axis labels
        ax2.tick_params(axis='x', rotation=45)
    
    plt.tight_layout()
    
    output_file = output_dir / "detailed_cluster_characteristics.png"
    plt.savefig(output_file, dpi=300, bbox_inches='tight')
    plt.close()
    
    print(f"Detailed cluster plot saved: {output_file}")


def save_analysis_results(histogram_features, cluster_results, output_dir):
    """Save analysis results to CSV files"""
    
    # Save histogram features
    features_df = pd.DataFrame(histogram_features).T
    
    # Remove non-serializable columns (arrays)
    columns_to_drop = ['bin_centers', 'hist_density', 'hist_counts']
    for col in columns_to_drop:
        if col in features_df.columns:
            features_df = features_df.drop(columns=[col])
    
    features_file = output_dir / "histogram_features.csv"
    features_df.to_csv(features_file)
    print(f"Histogram features saved: {features_file}")
    
    # Save cluster assignments
    if cluster_results is not None:
        cluster_df = pd.DataFrame({
            'site_name': cluster_results['site_names'],
            'kmeans_cluster': cluster_results['kmeans_labels'],
            'hierarchical_cluster': cluster_results['hierarchical_labels'],
            'dbscan_cluster': cluster_results['dbscan_labels'],
        })
        
        cluster_file = output_dir / "cluster_assignments.csv"
        cluster_df.to_csv(cluster_file, index=False)
        print(f"Cluster assignments saved: {cluster_file}")
        
        # Save feature importance (PCA loadings)
        loadings_df = pd.DataFrame(
            cluster_results['pca'].components_.T,
            columns=[f'PC{i+1}' for i in range(cluster_results['pca'].n_components_)],
            index=cluster_results['feature_names']
        )
        
        loadings_file = output_dir / "pca_feature_loadings.csv"
        loadings_df.to_csv(loadings_file)
        print(f"PCA feature loadings saved: {loadings_file}")


if __name__ == "__main__":
    main()