#!/usr/bin/env python3
"""
temperature_difference_analysis.py

Detailed analysis of temperature differences between 2m and 1m sensors.

Author: Generated by Claude Code
Created: 2025-07-27
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.gridspec as gridspec
import matplotlib.cm as cm
from matplotlib.colors import Normalize
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy.stats import pearsonr

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    guess_deployment_period,
    mask_from_csv_deployment_periods,
    apply_csv_deployment_mask,
    find_matching_csv_filename,
    _calculate_autocorr_metric,
    _calculate_gradient_metric,
    _calculate_variance_metric,
    _calculate_wosa_metric,
)


def main():
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    print("=== Temperature Difference Analysis ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - using automatic detection only")

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("No NetCDF files found!")
        return

    # Load and organize datasets by site
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)

            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            if site_key not in site_data:
                site_data[site_key] = {}

            if sensor_height in ["1m", "2m"]:
                # Try to reconstruct original CSV filename from NetCDF metadata
                original_csv_filename = None
                if hasattr(ds, "attrs") and "original_filename" in ds.attrs:
                    original_csv_filename = ds.attrs["original_filename"]
                else:
                    # Fall back to pattern matching with available CSV files
                    # This will be handled in the masking function
                    original_csv_filename = nc_file.name

                site_data[site_key][sensor_height] = {
                    "dataset": ds,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                    "original_csv_filename": original_csv_filename,
                }

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    # Filter sites that have both 1m and 2m sensors
    sites_with_both = {}
    for site_name, sensors in site_data.items():
        if "1m" in sensors and "2m" in sensors:
            sites_with_both[site_name] = sensors

    print(f"\nFound {len(sites_with_both)} sites with both 1m and 2m sensors:")
    for site_name in sites_with_both.keys():
        print(f"  - {site_name}")

    # Create temperature difference plots for each site
    for site_name, sensors in tqdm(
        sites_with_both.items(), desc="Creating difference plots"
    ):
        create_temperature_difference_plot(
            site_name, sensors, output_dir, csv_deployment_path, use_csv_masking
        )

    print(f"\nTemperature difference plots saved to: {output_dir}")
    print("Analysis complete!")


def create_temperature_difference_plot(
    site_name, sensors, output_dir, csv_deployment_path, use_csv_masking
):
    """Create detailed temperature difference analysis plot for a site"""

    # Extract datasets
    ds_1m = sensors["1m"]["dataset"]
    ds_2m = sensors["2m"]["dataset"]
    sensor_id_1m = sensors["1m"]["sensor_id"]
    sensor_id_2m = sensors["2m"]["sensor_id"]
    filename_1m = sensors["1m"]["file"]
    filename_2m = sensors["2m"]["file"]

    # Get temperature data
    temp_1m = ds_1m["temp_c"].dropna("datetime")
    temp_2m = ds_2m["temp_c"].dropna("datetime")

    # Find overlapping time period
    start_time = max(temp_2m.datetime.min().values, temp_1m.datetime.min().values)
    end_time = min(temp_2m.datetime.max().values, temp_1m.datetime.max().values)

    if start_time >= end_time:
        print(f"No overlapping data for site {site_name}")
        return

    # Create common time grid (10-minute intervals)
    common_times = pd.date_range(start_time, end_time, freq="10min")

    # Interpolate both to common time grid
    temp_2m_interp = temp_2m.interp(datetime=common_times, method="linear")
    temp_1m_interp = temp_1m.interp(datetime=common_times, method="linear")

    # Drop NaN values
    valid_mask = ~(np.isnan(temp_2m_interp.values) | np.isnan(temp_1m_interp.values))
    times_valid = common_times[valid_mask]
    temp_2m_valid = temp_2m_interp.values[valid_mask]
    temp_1m_valid = temp_1m_interp.values[valid_mask]

    if len(times_valid) == 0:
        print(f"No valid overlapping data for site {site_name}")
        return

    # Calculate temperature difference (2m - 1m)
    temp_diff = temp_2m_valid - temp_1m_valid

    # Apply deployment masking (CSV-based if available, otherwise automatic detection)
    if use_csv_masking:
        # Find matching CSV filenames using metadata
        site_name_2m = ds_2m.attrs.get("site_name", "Unknown")
        site_name_1m = ds_1m.attrs.get("site_name", "Unknown")
        height_2m = ds_2m.attrs.get("sensor_height", "Unknown")
        height_1m = ds_1m.attrs.get("sensor_height", "Unknown")

        csv_filename_2m = find_matching_csv_filename(
            sensor_id_2m, site_name_2m, height_2m, csv_deployment_path
        )
        csv_filename_1m = find_matching_csv_filename(
            sensor_id_1m, site_name_1m, height_1m, csv_deployment_path
        )

        print(f"  Applying CSV masking for {site_name}:")
        print(f"    2m: {csv_filename_2m}")
        print(f"    1m: {csv_filename_1m}")

        if csv_filename_2m and csv_filename_1m:
            # Get CSV-based deployment masks
            deployed_2m = mask_from_csv_deployment_periods(
                temp_2m_valid, times_valid, csv_filename_2m, csv_deployment_path
            )
            deployed_1m = mask_from_csv_deployment_periods(
                temp_1m_valid, times_valid, csv_filename_1m, csv_deployment_path
            )

            print(
                f"    CSV masking results: 2m={np.sum(deployed_2m)}/{len(deployed_2m)} deployed, 1m={np.sum(deployed_1m)}/{len(deployed_1m)} deployed"
            )
        else:
            print(
                "    Warning: Could not find CSV filenames, falling back to automatic detection"
            )
            use_csv_masking = False

    # Combined deployment mask (both sensors must be deployed)
    deployed_both = deployed_2m & deployed_1m

    print(
        f"  Site {site_name}: {np.sum(deployed_both) / len(deployed_both) * 100:.1f}% of data during deployment"
    )

    # Create figure with gridspec layout
    fig = plt.figure(figsize=(20, 16))
    gs = gridspec.GridSpec(3, 2, height_ratios=[1, 1, 1], hspace=0.3, wspace=0.3)

    deployed_pct = np.sum(deployed_both) / len(deployed_both) * 100
    masking_method = "CSV-based" if use_csv_masking else "Automatic detection"
    fig.suptitle(
        f"Temperature Difference Analysis: {site_name}\n"
        f"2m Sensor: {sensor_id_2m} | 1m Sensor: {sensor_id_1m}\n"
        f"Deployment Masking ({masking_method}): {deployed_pct:.1f}% of data during field deployment",
        fontsize=16,
        fontweight="bold",
    )

    # Define subplots using gridspec
    ax_timeseries = fig.add_subplot(gs[0, :])  # Row 1, both columns
    ax_histogram = fig.add_subplot(gs[1, 0])  # Row 2, column 1
    ax_correlation = fig.add_subplot(gs[1, 1])  # Row 2, column 2
    ax_detrended = fig.add_subplot(gs[2, 0])  # Row 3, column 1
    ax_raw = fig.add_subplot(gs[2, 1])  # Row 3, column 2

    # Plot 1: Temperature difference timeseries with correlation on second axis
    ax_timeseries.plot(
        times_valid,
        temp_diff,
        color="blue",
        alpha=0.7,
        linewidth=0.5,
        label="Temp Difference",
    )
    ax_timeseries.axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)
    ax_timeseries.fill_between(
        times_valid,
        temp_diff,
        0,
        where=(temp_diff > 0),
        alpha=0.3,
        color="grey",
        label="Inverted (2m > 1m)",
    )
    ax_timeseries.set_ylabel("Temperature Difference (°C)", color="blue")
    ax_timeseries.set_ylim(-5, 5)
    ax_timeseries.grid(True, alpha=0.3)
    ax_timeseries.tick_params(axis="y", labelcolor="blue")

    # Highlight non-deployed periods
    non_deployed = ~deployed_both
    if np.any(non_deployed):
        # Find continuous non-deployed periods
        non_deployed_diff = np.diff(
            np.concatenate(([False], non_deployed, [False])).astype(int)
        )
        starts = np.where(non_deployed_diff == 1)[0]
        ends = np.where(non_deployed_diff == -1)[0]

        for i, (start, end) in enumerate(zip(starts, ends)):
            ax_timeseries.axvspan(
                times_valid[start],
                times_valid[end - 1] if end < len(times_valid) else times_valid[-1],
                alpha=0.2,
                color="orange",
                label="Likely not deployed" if i == 0 else "",
            )

    # Create second y-axis for correlation
    ax_corr = ax_timeseries.twinx()
    corr_times, corr_values = calculate_rolling_correlation(
        times_valid, temp_2m_valid, temp_1m_valid
    )
    ax_corr.plot(
        corr_times,
        corr_values,
        color="red",
        alpha=0.8,
        linewidth=1.5,
        label="Rolling Correlation (24h)",
    )
    ax_corr.axhline(y=1.0, color="red", linestyle=":", alpha=0.5, linewidth=1)
    ax_corr.set_ylabel("Correlation Coefficient", color="red")
    ax_corr.set_ylim(0, 1)
    ax_corr.tick_params(axis="y", labelcolor="red")

    # Combined title and legends
    ax_timeseries.set_title(
        "Temperature Difference & Correlation Time Series (2m - 1m)"
    )

    # Combine legends from both axes
    lines1, labels1 = ax_timeseries.get_legend_handles_labels()
    lines2, labels2 = ax_corr.get_legend_handles_labels()
    ax_timeseries.legend(lines1 + lines2, labels1 + labels2, loc="upper right")

    # Format x-axis
    ax_timeseries.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    ax_timeseries.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
    ax_timeseries.tick_params(axis="x", rotation=45)

    # Plot 2: Histogram of temperature differences (deployed periods only)
    temp_diff_deployed = temp_diff[deployed_both]

    # Calculate bins with 0.1°C width
    if len(temp_diff_deployed) > 0:
        data_min = np.min(temp_diff_deployed)
        data_max = np.max(temp_diff_deployed)
        n_bins = int((data_max - data_min) / 0.1) + 1
        bins = np.linspace(data_min, data_min + n_bins * 0.1, n_bins + 1)

        # # Plot overall deployed data histogram in light gray
        # ax_histogram.hist(
        #     temp_diff_deployed,
        #     bins=bins,
        #     alpha=0.6,
        #     color="lightgray",
        #     density=True,
        #     edgecolor="gray",
        #     linewidth=0.5,
        #     label=f"Deployed data (n={len(temp_diff_deployed)})",
        # )

        # Separate inverted and stable conditions (using deployed data only)
        inverted_mask = temp_diff_deployed > 0  # 2m > 1m (temperature inversion)
        stable_mask = temp_diff_deployed <= 0  # 2m <= 1m (stable/normal lapse rate)

        temp_diff_inverted = temp_diff_deployed[inverted_mask]
        temp_diff_stable = temp_diff_deployed[stable_mask]

        # Plot inverted conditions (temperature inversions) in red
        if len(temp_diff_inverted) > 0:
            ax_histogram.hist(
                temp_diff_inverted,
                bins=bins,
                alpha=0.4,
                color="red",
                density=True,
                edgecolor="darkred",
                linewidth=0.5,
                label=f"Inverted (n={len(temp_diff_inverted)})",
            )

        # Plot stable conditions in blue
        if len(temp_diff_stable) > 0:
            ax_histogram.hist(
                temp_diff_stable,
                bins=bins,
                alpha=0.4,
                color="blue",
                density=True,
                edgecolor="darkblue",
                linewidth=0.5,
                label=f"Stable (n={len(temp_diff_stable)})",
            )

    ax_histogram.axvline(x=0, color="black", linestyle="--", alpha=0.8, linewidth=1)

    # Statistics for deployed data
    if len(temp_diff_deployed) > 0:
        ax_histogram.axvline(
            x=np.mean(temp_diff_deployed),
            color="red",
            linestyle="-",
            alpha=0.8,
            linewidth=2,
            label=f"Mean (deployed): {np.mean(temp_diff_deployed):.2f}°C",
        )
        ax_histogram.axvline(
            x=np.median(temp_diff_deployed),
            color="green",
            linestyle="-",
            alpha=0.8,
            linewidth=2,
            label=f"Median (deployed): {np.median(temp_diff_deployed):.2f}°C",
        )
    ax_histogram.set_title("Temperature Difference Distribution")
    ax_histogram.set_xlabel("Temperature Difference (°C)")
    ax_histogram.set_ylabel("Density")
    ax_histogram.grid(True, alpha=0.3)
    ax_histogram.legend(loc="upper right")

    # Extract deployed data for analysis
    times_deployed = times_valid[deployed_both]
    temp_2m_deployed = temp_2m_valid[deployed_both]
    temp_1m_deployed = temp_1m_valid[deployed_both]

    # Plot 3: Hourly correlation scatterplot (deployed periods only)
    if len(times_deployed) > 100:  # Need sufficient deployed data
        hourly_correlation_data = calculate_hourly_correlations(
            times_deployed, temp_2m_deployed, temp_1m_deployed
        )
        if hourly_correlation_data is not None:
            plot_hourly_correlations(ax_correlation, hourly_correlation_data)

    # Plot 4 & 5: Daily cycles (deployed periods only)
    if len(times_deployed) > 100:  # Need sufficient deployed data
        daily_analysis_detrended = analyze_daily_cycles(
            times_deployed, temp_2m_deployed, temp_1m_deployed, subtract_mean=True
        )
        daily_analysis_raw = analyze_daily_cycles(
            times_deployed, temp_2m_deployed, temp_1m_deployed, subtract_mean=False
        )
    else:
        # Fall back to all data if insufficient deployed data
        daily_analysis_detrended = analyze_daily_cycles(
            times_valid, temp_2m_valid, temp_1m_valid, subtract_mean=True
        )
        daily_analysis_raw = analyze_daily_cycles(
            times_valid, temp_2m_valid, temp_1m_valid, subtract_mean=False
        )

    # Calculate consistent y-axis range based on raw data
    y_range = None
    if daily_analysis_raw is not None:
        all_raw_values = np.concatenate(
            [
                daily_analysis_raw["mean_2m"],
                daily_analysis_raw["mean_1m"],
                daily_analysis_raw["mean_2m"] + daily_analysis_raw["std_2m"],
                daily_analysis_raw["mean_2m"] - daily_analysis_raw["std_2m"],
                daily_analysis_raw["mean_1m"] + daily_analysis_raw["std_1m"],
                daily_analysis_raw["mean_1m"] - daily_analysis_raw["std_1m"],
            ]
        )
        y_min, y_max = np.min(all_raw_values), np.max(all_raw_values)
        y_range = y_max - y_min

    if daily_analysis_detrended is not None:
        plot_daily_cycles(
            ax_detrended,
            daily_analysis_detrended,
            "Daily Temperature Cycles (Mean Subtracted)",
            y_range,
        )

    if daily_analysis_raw is not None:
        plot_daily_cycles(
            ax_raw, daily_analysis_raw, "Daily Temperature Cycles (Raw)", None
        )

    # Save plot
    safe_site_name = "".join(
        c for c in site_name if c.isalnum() or c in (" ", "-", "_")
    ).rstrip()
    output_file = output_dir / f"{safe_site_name}_temperature_difference.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()


def calculate_rolling_correlation(times, temp_2m, temp_1m, window_hours=24):
    """Calculate rolling correlation between 2m and 1m sensors over time"""

    # Convert to pandas for easier manipulation
    df = pd.DataFrame({"datetime": times, "temp_2m": temp_2m, "temp_1m": temp_1m})
    df.set_index("datetime", inplace=True)

    # Calculate rolling correlation with specified window
    window_size = f"{window_hours}H"
    rolling_corr = (
        df["temp_2m"].rolling(window=window_size, min_periods=10).corr(df["temp_1m"])
    )

    # Return valid correlations and their times
    valid_mask = ~np.isnan(rolling_corr)
    return rolling_corr.index[valid_mask], rolling_corr.values[valid_mask]


def calculate_hourly_correlations(times, temp_2m, temp_1m):
    """Calculate correlations vs inversion strength for each hour of the day"""

    # Convert to pandas for easier manipulation
    df = pd.DataFrame({"datetime": times, "temp_2m": temp_2m, "temp_1m": temp_1m})
    df.set_index("datetime", inplace=True)

    # Calculate temperature difference (inversion strength)
    df["temp_diff"] = df["temp_2m"] - df["temp_1m"]

    # Find noon times (12:00) for splitting days
    all_noons = []
    start_date = df.index[0].date()
    end_date = df.index[-1].date()

    current_date = start_date
    while current_date <= end_date:
        noon_time = pd.Timestamp(
            year=current_date.year,
            month=current_date.month,
            day=current_date.day,
            hour=12,
            minute=0,
        )
        if noon_time >= df.index[0] and noon_time <= df.index[-1]:
            all_noons.append(noon_time)
        current_date = current_date + pd.Timedelta(days=1)

    if len(all_noons) < 2:
        return None

    # Split data into noon-to-noon periods and calculate correlations
    hourly_correlations = []
    hourly_inversion_strength = []
    hourly_hours = []

    for i in range(len(all_noons) - 1):
        start_noon = all_noons[i]
        end_noon = all_noons[i + 1]

        # Extract 24-hour period
        day_data = df[(df.index >= start_noon) & (df.index < end_noon)].copy()

        if len(day_data) < 10:  # Skip days with too little data
            continue

        # Calculate hours from noon
        day_data["hours_from_noon"] = (
            day_data.index - start_noon
        ).total_seconds() / 3600

        # Bin data into hourly intervals and calculate correlation for each hour
        for hour in range(24):
            hour_data = day_data[
                (day_data["hours_from_noon"] >= hour)
                & (day_data["hours_from_noon"] < hour + 1)
            ]

            if len(hour_data) >= 3:  # Need at least 3 points for correlation
                try:
                    corr, _ = pearsonr(hour_data["temp_2m"], hour_data["temp_1m"])
                    mean_inversion = hour_data["temp_diff"].mean()
                    if not np.isnan(corr) and not np.isnan(mean_inversion):
                        hourly_correlations.append(corr)
                        hourly_inversion_strength.append(mean_inversion)
                        hourly_hours.append(hour)
                except:
                    continue

    if len(hourly_correlations) == 0:
        return None

    return {
        "hours": np.array(hourly_hours),
        "correlations": np.array(hourly_correlations),
        "inversion_strength": np.array(hourly_inversion_strength),
    }


def plot_hourly_correlations(ax, correlation_data):
    """Plot correlation vs inversion strength colored by time of day"""

    hours = correlation_data["hours"]
    correlations = correlation_data["correlations"]
    inversion_strength = correlation_data["inversion_strength"]

    # Create colors based on time of day (hours from noon)
    # Use a circular colormap to represent the 24-hour cycle
    hour_colors = cm.twilight(hours / 24.0)

    # Create scatter plot
    ax.scatter(inversion_strength, correlations, c=hour_colors, alpha=0.5, s=10)

    # Add reference lines
    ax.axhline(
        y=1.0,
        color="red",
        linestyle="--",
        alpha=0.8,
        linewidth=1,
        label="Perfect Correlation",
    )
    ax.axhline(y=0.0, color="black", linestyle="--", alpha=0.5, linewidth=1)
    ax.axvline(
        x=0.0,
        color="black",
        linestyle="--",
        alpha=0.5,
        linewidth=1,
        label="No Inversion",
    )

    # Formatting
    ax.set_title("Temperature Correlation vs Inversion Strength")
    ax.set_xlabel("Inversion Strength (2m - 1m, °C)")
    ax.set_ylabel("Correlation Coefficient")
    ax.set_ylim(-1, 1)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower right")

    # Add colorbar for time of day
    sm = cm.ScalarMappable(cmap="twilight", norm=Normalize(vmin=0, vmax=24))
    sm.set_array([])
    cbar = plt.colorbar(sm, ax=ax, shrink=0.6)
    cbar.set_label("Hours from Noon", rotation=270, labelpad=15)
    cbar.set_ticks([0, 6, 12, 18, 24])
    cbar.set_ticklabels(["Noon", "6PM", "Midnight", "6AM", "Noon"])


def analyze_daily_cycles(times, temp_2m, temp_1m, subtract_mean=True):
    """Analyze daily temperature cycles from noon to noon"""

    # Convert to pandas for easier manipulation
    df = pd.DataFrame({"datetime": times, "temp_2m": temp_2m, "temp_1m": temp_1m})
    df.set_index("datetime", inplace=True)

    # Find noon times (12:00) for splitting days
    all_noons = []
    start_date = df.index[0].date()
    end_date = df.index[-1].date()

    current_date = start_date
    while current_date <= end_date:
        noon_time = pd.Timestamp(
            year=current_date.year,
            month=current_date.month,
            day=current_date.day,
            hour=12,
            minute=0,
        )
        if noon_time >= df.index[0] and noon_time <= df.index[-1]:
            all_noons.append(noon_time)
        current_date = current_date + pd.Timedelta(days=1)

    if len(all_noons) < 2:
        return None

    # Split data into noon-to-noon periods
    daily_data = []
    for i in range(len(all_noons) - 1):
        start_noon = all_noons[i]
        end_noon = all_noons[i + 1]

        # Extract 24-hour period
        day_data = df[(df.index >= start_noon) & (df.index < end_noon)].copy()

        if len(day_data) < 10:  # Skip days with too little data
            continue

        # Calculate hours from noon
        day_data["hours_from_noon"] = (
            day_data.index - start_noon
        ).total_seconds() / 3600

        # Subtract daily mean if requested
        if subtract_mean:
            # Use pooled mean of both sensors
            pooled_mean = pd.concat([day_data["temp_2m"], day_data["temp_1m"]]).mean()
            day_data["temp_2m_detrended"] = day_data["temp_2m"] - pooled_mean
            day_data["temp_1m_detrended"] = day_data["temp_1m"] - pooled_mean
        else:
            day_data["temp_2m_detrended"] = day_data["temp_2m"]
            day_data["temp_1m_detrended"] = day_data["temp_1m"]

        daily_data.append(day_data)

    if len(daily_data) == 0:
        return None

    # Create common hourly grid (0-24 hours from noon)
    hour_grid = np.arange(0, 24, 0.25)  # 15-minute intervals

    # Interpolate each day to common grid
    interpolated_2m = []
    interpolated_1m = []

    for day_data in daily_data:
        # Interpolate to hour grid
        temp_2m_interp = np.interp(
            hour_grid, day_data["hours_from_noon"], day_data["temp_2m_detrended"]
        )
        temp_1m_interp = np.interp(
            hour_grid, day_data["hours_from_noon"], day_data["temp_1m_detrended"]
        )

        interpolated_2m.append(temp_2m_interp)
        interpolated_1m.append(temp_1m_interp)

    # Convert to arrays
    interpolated_2m = np.array(interpolated_2m)
    interpolated_1m = np.array(interpolated_1m)

    # Calculate statistics
    mean_2m = np.mean(interpolated_2m, axis=0)
    mean_1m = np.mean(interpolated_1m, axis=0)
    median_2m = np.median(interpolated_2m, axis=0)
    median_1m = np.median(interpolated_1m, axis=0)
    std_2m = np.std(interpolated_2m, axis=0)
    std_1m = np.std(interpolated_1m, axis=0)

    return {
        "hour_grid": hour_grid,
        "mean_2m": mean_2m,
        "mean_1m": mean_1m,
        "median_2m": median_2m,
        "median_1m": median_1m,
        "std_2m": std_2m,
        "std_1m": std_1m,
        "n_days": len(daily_data),
    }


def plot_daily_cycles(ax, analysis_data, title, y_range=None):
    """Plot the daily cycle analysis results"""

    hour_grid = analysis_data["hour_grid"]
    mean_2m = analysis_data["mean_2m"]
    mean_1m = analysis_data["mean_1m"]
    std_2m = analysis_data["std_2m"]
    std_1m = analysis_data["std_1m"]
    n_days = analysis_data["n_days"]

    # Plot mean curves
    ax.plot(
        hour_grid, mean_2m, color="red", linewidth=2, label=f"2m Mean (n={n_days} days)"
    )
    ax.plot(
        hour_grid,
        mean_1m,
        color="blue",
        linewidth=2,
        label=f"1m Mean (n={n_days} days)",
    )

    # Plot standard deviation as lines instead of shaded areas
    ax.plot(
        hour_grid,
        mean_2m + std_2m,
        color="red",
        linewidth=1,
        linestyle=":",
        alpha=0.7,
        label="2m +1σ",
    )
    ax.plot(
        hour_grid,
        mean_2m - std_2m,
        color="red",
        linewidth=1,
        linestyle=":",
        alpha=0.7,
        label="2m -1σ",
    )
    ax.plot(
        hour_grid,
        mean_1m + std_1m,
        color="blue",
        linewidth=1,
        linestyle=":",
        alpha=0.7,
        label="1m +1σ",
    )
    ax.plot(
        hour_grid,
        mean_1m - std_1m,
        color="blue",
        linewidth=1,
        linestyle=":",
        alpha=0.7,
        label="1m -1σ",
    )

    # Shade areas where 2m > 1m (temperature inversion)
    inversion_mask = mean_2m > mean_1m
    if np.any(inversion_mask):
        ax.fill_between(
            hour_grid,
            mean_1m,
            mean_2m,
            where=inversion_mask,
            alpha=0.3,
            color="grey",
            label="Inverted (2m > 1m)",
        )

    # Add 0-degree reference line
    ax.axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)

    # Set consistent y-axis range if provided
    if y_range is not None:
        # Center the y-axis around the data range
        current_min = min(np.min(mean_2m - std_2m), np.min(mean_1m - std_1m))
        current_max = max(np.max(mean_2m + std_2m), np.max(mean_1m + std_1m))
        current_center = (current_min + current_max) / 2

        # Set new range with same magnitude as raw data
        new_min = current_center - y_range / 2
        new_max = current_center + y_range / 2
        ax.set_ylim(new_min, new_max)

    # Formatting
    ax.set_title(title)
    ax.set_xlabel("Hours from Noon")
    ax.set_ylabel("Temperature (°C)")
    ax.set_xlim(0, 24)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right", fontsize=8)

    # Set x-axis ticks
    ax.set_xticks([0, 6, 12, 18, 24])
    ax.set_xticklabels(["Noon", "6PM", "Midnight", "6AM", "Noon"])


def create_deployment_qc_plots(
    site_name,
    sensor_id_2m,
    sensor_id_1m,
    temp_2m,
    temp_1m,
    times,
    deployed_2m,
    deployed_1m,
    output_dir,
    method_2m="variance",
    method_1m="variance",
    threshold_2m=0.1,
    threshold_1m=0.1,
    window_hours_2m=6.0,
    window_hours_1m=6.0,
    min_deployment_hours=3.0,
):
    """Create and save QC plots showing deployment detection metrics."""

    # Calculate metrics for both sensors to show on plots
    # Use the same methods as used for deployment detection

    # Calculate 2m sensor metric
    ts_2m = pd.Series(temp_2m, index=times)
    if method_2m == "variance":
        metric_2m = _calculate_variance_metric(ts_2m, window_hours_2m)
    elif method_2m == "wosa":
        metric_2m = _calculate_wosa_metric(ts_2m, window_hours_2m)
    elif method_2m == "autocorr":
        metric_2m = _calculate_autocorr_metric(ts_2m, window_hours_2m, 2.0)
    elif method_2m == "gradient":
        metric_2m = _calculate_gradient_metric(ts_2m, window_hours_2m)
    else:
        raise ValueError(f"Unknown method: {method_2m}")

    # Calculate 1m sensor metric
    ts_1m = pd.Series(temp_1m, index=times)
    if method_1m == "variance":
        metric_1m = _calculate_variance_metric(ts_1m, window_hours_1m)
    elif method_1m == "wosa":
        metric_1m = _calculate_wosa_metric(ts_1m, window_hours_1m)
    elif method_1m == "autocorr":
        metric_1m = _calculate_autocorr_metric(ts_1m, window_hours_1m, 2.0)
    elif method_1m == "gradient":
        metric_1m = _calculate_gradient_metric(ts_1m, window_hours_1m)
    else:
        raise ValueError(f"Unknown method: {method_1m}")

    # Calculate raw deployment masks (before morphological cleaning) for comparison
    raw_deployed_2m = metric_2m > threshold_2m
    raw_deployed_1m = metric_1m > threshold_1m

    # Debug output
    print(
        f"  Debug - 2m {method_2m} metric range: {metric_2m.min():.4f} to {metric_2m.max():.4f}"
    )
    print(
        f"  Debug - 1m {method_1m} metric range: {metric_1m.min():.4f} to {metric_1m.max():.4f}"
    )
    print(
        f"  Debug - metric_2m has {metric_2m.count()} non-NaN values out of {len(metric_2m)}"
    )
    print(
        f"  Debug - metric_1m has {metric_1m.count()} non-NaN values out of {len(metric_1m)}"
    )
    print(f"  Debug - Raw vs cleaned deployment detection:")
    print(
        f"    2m: {np.sum(raw_deployed_2m)}/{len(raw_deployed_2m)} raw → {np.sum(deployed_2m)}/{len(deployed_2m)} cleaned"
    )
    print(
        f"    1m: {np.sum(raw_deployed_1m)}/{len(raw_deployed_1m)} raw → {np.sum(deployed_1m)}/{len(deployed_1m)} cleaned"
    )

    # Create figure with 4 subplots
    fig, axes = plt.subplots(2, 2, figsize=(16, 12))
    fig.suptitle(
        f"Deployment Detection QC: {site_name}\n"
        f"2m Sensor: {sensor_id_2m} | 1m Sensor: {sensor_id_1m}",
        fontsize=14,
        fontweight="bold",
    )

    # Plot 1: 2m sensor temperature with deployment periods
    ax = axes[0, 0]
    ax.plot(times, temp_2m, "b-", alpha=0.7, linewidth=0.8, label="2m Temperature")

    # Highlight non-deployed periods
    non_deployed_2m = ~deployed_2m
    if np.any(non_deployed_2m):
        non_deployed_diff = np.diff(
            np.concatenate(([False], non_deployed_2m, [False])).astype(int)
        )
        starts = np.where(non_deployed_diff == 1)[0]
        ends = np.where(non_deployed_diff == -1)[0]

        for i, (start, end) in enumerate(zip(starts, ends)):
            ax.axvspan(
                times[start],
                times[end - 1] if end < len(times) else times[-1],
                alpha=0.3,
                color="red",
                label="Not deployed" if i == 0 else "",
            )

    ax.set_title("2m Sensor Temperature & Deployment")
    ax.set_ylabel("Temperature (°C)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Plot 2: 1m sensor temperature with deployment periods
    ax = axes[0, 1]
    ax.plot(times, temp_1m, "g-", alpha=0.7, linewidth=0.8, label="1m Temperature")

    # Highlight non-deployed periods
    non_deployed_1m = ~deployed_1m
    if np.any(non_deployed_1m):
        non_deployed_diff = np.diff(
            np.concatenate(([False], non_deployed_1m, [False])).astype(int)
        )
        starts = np.where(non_deployed_diff == 1)[0]
        ends = np.where(non_deployed_diff == -1)[0]

        for i, (start, end) in enumerate(zip(starts, ends)):
            ax.axvspan(
                times[start],
                times[end - 1] if end < len(times) else times[-1],
                alpha=0.3,
                color="red",
                label="Not deployed" if i == 0 else "",
            )

    ax.set_title("1m Sensor Temperature & Deployment")
    ax.set_ylabel("Temperature (°C)")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Plot 3: 2m sensor metric with threshold
    ax = axes[1, 0]
    ax.plot(
        metric_2m.index,
        metric_2m.values,
        "b-",
        alpha=0.8,
        linewidth=1,
        label=f"{method_2m.title()} Metric",
    )
    ax.axhline(
        threshold_2m,
        color="r",
        linestyle="--",
        alpha=0.7,
        linewidth=2,
        label=f"Threshold ({threshold_2m})",
    )
    # Show raw deployment periods in light green
    ax.fill_between(
        metric_2m.index,
        metric_2m.values,
        threshold_2m,
        where=np.array(raw_deployed_2m),
        alpha=0.2,
        color="lightgreen",
        label="Raw Deployed",
    )

    # Show cleaned deployment periods in darker green
    ax.fill_between(
        metric_2m.index,
        metric_2m.values,
        threshold_2m,
        where=np.array(deployed_2m),
        alpha=0.4,
        color="green",
        label="Cleaned Deployed",
    )

    # Set appropriate y-axis label based on method
    ylabel_2m = _get_ylabel_for_method(method_2m)
    ax.set_title(f"2m Sensor: {method_2m.title()} Metric")
    ax.set_ylabel(ylabel_2m)
    ax.set_xlabel("Time")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Plot 4: 1m sensor metric with threshold
    ax = axes[1, 1]
    ax.plot(
        metric_1m.index,
        metric_1m.values,
        "g-",
        alpha=0.8,
        linewidth=1,
        label=f"{method_1m.title()} Metric",
    )
    ax.axhline(
        threshold_1m,
        color="r",
        linestyle="--",
        alpha=0.7,
        linewidth=2,
        label=f"Threshold ({threshold_1m})",
    )
    # Show raw deployment periods in light green
    ax.fill_between(
        metric_1m.index,
        metric_1m.values,
        threshold_1m,
        where=np.array(raw_deployed_1m),
        alpha=0.2,
        color="lightgreen",
        label="Raw Deployed",
    )

    # Show cleaned deployment periods in darker green
    ax.fill_between(
        metric_1m.index,
        metric_1m.values,
        threshold_1m,
        where=np.array(deployed_1m),
        alpha=0.4,
        color="green",
        label="Cleaned Deployed",
    )

    # Set appropriate y-axis label based on method
    ylabel_1m = _get_ylabel_for_method(method_1m)
    ax.set_title(f"1m Sensor: {method_1m.title()} Metric")
    ax.set_ylabel(ylabel_1m)
    ax.set_xlabel("Time")
    ax.legend()
    ax.grid(True, alpha=0.3)

    # Format x-axis for all plots
    for ax in axes.flat:
        ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
        ax.tick_params(axis="x", rotation=45)

    plt.tight_layout()

    # Save QC plot
    safe_site_name = "".join(
        c for c in site_name if c.isalnum() or c in (" ", "-", "_")
    ).rstrip()
    qc_output_file = output_dir / f"{safe_site_name}_deployment_qc.png"
    plt.savefig(qc_output_file, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"  QC plot saved: {qc_output_file}")


def _get_ylabel_for_method(method):
    """Get appropriate y-axis label for each metric method."""
    labels = {
        "variance": "Temperature Std Dev (°C)",
        "wosa": "High-Freq RMS Variability (°C)",
        "autocorr": "Inverted Autocorrelation",
        "gradient": "Gradient Std Dev (°C/timestep)",
    }
    return labels.get(method, "Metric Value")


if __name__ == "__main__":
    main()
