#!/usr/bin/env python3
"""
two_site_lapse_rate_comparison.py

Compare temperature lapse rates and correlations between two sites with 1m and 2m sensors.
Creates comprehensive visualization including lapse rate analysis, inter-site correlations,
and temperature difference comparisons.

Author: Generated by Claude Code
Created: 2025-07-30
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.gridspec as gridspec
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy.stats import pearsonr
from sklearn.linear_model import HuberRegressor

warnings.filterwarnings("ignore")

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    print("=== Two-Site Lapse Rate Comparison - All Site Combinations ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - using automatic detection only")

    # Load site elevation data
    site_elevations = load_site_elevations(csv_deployment_path)

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("No NetCDF files found!")
        return

    # Load and organize datasets by site
    site_data = load_site_data(netcdf_files)

    # Filter sites that have both 1m and 2m sensors
    sites_with_both = {}
    required_heights = ["1m", "2m"]

    for site_name, sensors in site_data.items():
        if all(height in sensors for height in required_heights):
            sites_with_both[site_name] = sensors

    print(f"\nFound {len(sites_with_both)} sites with both 1m and 2m sensors:")
    for site_name in sorted(sites_with_both.keys()):
        elevation = site_elevations.get(site_name, "Unknown")
        print(f"  - {site_name} ({elevation}m)")

    if len(sites_with_both) < 2:
        print("Need at least 2 sites with both sensors for comparison!")
        return

    # Generate all unique site combinations
    site_names = sorted(sites_with_both.keys())
    combinations = []

    for i in range(len(site_names)):
        for j in range(i + 1, len(site_names)):
            site1 = site_names[i]
            site2 = site_names[j]

            # Order by elevation (higher elevation first for consistent lapse rate calculation)
            elev1 = site_elevations.get(site1, 0)
            elev2 = site_elevations.get(site2, 0)

            if elev1 >= elev2:
                combinations.append((site1, site2))
            else:
                combinations.append((site2, site1))

    print(f"\nGenerating {len(combinations)} site comparison plots:")

    successful_plots = 0
    failed_plots = 0

    for i, (site1_name, site2_name) in enumerate(combinations, 1):
        print(f"\n[{i}/{len(combinations)}] Comparing {site1_name} vs {site2_name}")

        try:
            # Create comprehensive comparison plot
            success = create_two_site_comparison_plot(
                site1_name,
                sites_with_both[site1_name],
                site2_name,
                sites_with_both[site2_name],
                site_elevations,
                output_dir,
                csv_deployment_path,
                use_csv_masking,
            )

            if success:
                successful_plots += 1
            else:
                failed_plots += 1

        except Exception as e:
            print(f"  Error creating plot for {site1_name} vs {site2_name}: {e}")
            failed_plots += 1

    print(f"\n=== Analysis Complete ===")
    print(f"Successfully created: {successful_plots} plots")
    print(f"Failed: {failed_plots} plots")
    print(f"Output directory: {output_dir}")


def resample_to_hourly(times, temp_arrays, deployed_mask):
    """Resample temperature data to 1-hour averages"""

    # Create DataFrame with all data
    df = pd.DataFrame(
        {
            "datetime": times,
            "temp1_1m": temp_arrays[0],
            "temp1_2m": temp_arrays[1],
            "temp2_1m": temp_arrays[2],
            "temp2_2m": temp_arrays[3],
            "deployed": deployed_mask,
        }
    )
    df.set_index("datetime", inplace=True)

    # Only use deployed data for resampling
    df_deployed = df[df["deployed"]].drop(columns=["deployed"])

    if len(df_deployed) == 0:
        return None, None, None

    # Resample to hourly averages
    df_hourly = (
        df_deployed.resample("1H")
        .agg(
            {
                "temp1_1m": "mean",
                "temp1_2m": "mean",
                "temp2_1m": "mean",
                "temp2_2m": "mean",
            }
        )
        .dropna()
    )

    if len(df_hourly) == 0:
        return None, None, None

    # Extract hourly data
    times_hourly = df_hourly.index.values
    temp_arrays_hourly = [
        df_hourly["temp1_1m"].values,
        df_hourly["temp1_2m"].values,
        df_hourly["temp2_1m"].values,
        df_hourly["temp2_2m"].values,
    ]
    deployed_mask_hourly = np.ones(len(times_hourly), dtype=bool)

    return times_hourly, temp_arrays_hourly, deployed_mask_hourly


def load_site_elevations(csv_deployment_path):
    """Load site elevation data from deployment CSV"""
    elevations = {}
    if csv_deployment_path.exists():
        df = pd.read_csv(csv_deployment_path)
        for _, row in df.iterrows():
            site = row["site"]
            elevation = row["site_elevation"]
            if pd.notna(site) and pd.notna(elevation):
                elevations[site] = float(elevation)
    return elevations


def load_site_data(netcdf_files):
    """Load and organize NetCDF datasets by site"""
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)

            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            if site_key not in site_data:
                site_data[site_key] = {}

            if sensor_height in ["1m", "2m"]:
                # Store original CSV filename for deployment masking
                original_csv_filename = None
                if hasattr(ds, "attrs") and "original_filename" in ds.attrs:
                    original_csv_filename = ds.attrs["original_filename"]
                else:
                    original_csv_filename = nc_file.name

                site_data[site_key][sensor_height] = {
                    "dataset": ds,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                    "original_csv_filename": original_csv_filename,
                }

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    return site_data


def create_two_site_comparison_plot(
    site1_name,
    site1_sensors,
    site2_name,
    site2_sensors,
    site_elevations,
    output_dir,
    csv_deployment_path,
    use_csv_masking,
):
    """Create comprehensive two-site comparison visualization"""

    # Extract datasets
    ds1_1m = site1_sensors["1m"]["dataset"]
    ds1_2m = site1_sensors["2m"]["dataset"]
    ds2_1m = site2_sensors["1m"]["dataset"]
    ds2_2m = site2_sensors["2m"]["dataset"]

    # Get temperature data
    temp1_1m = ds1_1m["temp_c"].dropna("datetime")
    temp1_2m = ds1_2m["temp_c"].dropna("datetime")
    temp2_1m = ds2_1m["temp_c"].dropna("datetime")
    temp2_2m = ds2_2m["temp_c"].dropna("datetime")

    # Find overlapping time period for all sensors
    start_time = max(
        temp1_1m.datetime.min().values,
        temp1_2m.datetime.min().values,
        temp2_1m.datetime.min().values,
        temp2_2m.datetime.min().values,
    )
    end_time = min(
        temp1_1m.datetime.max().values,
        temp1_2m.datetime.max().values,
        temp2_1m.datetime.max().values,
        temp2_2m.datetime.max().values,
    )

    if start_time >= end_time:
        print(f"  No overlapping data between sites {site1_name} and {site2_name}")
        return False

    print(f"Overlapping period: {start_time} to {end_time}")

    # Create common time grid (10-minute intervals)
    common_times = pd.date_range(start_time, end_time, freq="1H")

    # Interpolate all sensors to common time grid
    temp1_1m_interp = temp1_1m.interp(datetime=common_times, method="linear")
    temp1_2m_interp = temp1_2m.interp(datetime=common_times, method="linear")
    temp2_1m_interp = temp2_1m.interp(datetime=common_times, method="linear")
    temp2_2m_interp = temp2_2m.interp(datetime=common_times, method="linear")

    # Drop NaN values
    valid_mask = ~(
        np.isnan(temp1_1m_interp.values)
        | np.isnan(temp1_2m_interp.values)
        | np.isnan(temp2_1m_interp.values)
        | np.isnan(temp2_2m_interp.values)
    )

    times_valid = common_times[valid_mask]
    temp1_1m_valid = temp1_1m_interp.values[valid_mask]
    temp1_2m_valid = temp1_2m_interp.values[valid_mask]
    temp2_1m_valid = temp2_1m_interp.values[valid_mask]
    temp2_2m_valid = temp2_2m_interp.values[valid_mask]

    if len(times_valid) == 0:
        print(
            f"  No valid overlapping data between sites {site1_name} and {site2_name}"
        )
        return False

    print(f"Valid overlapping data points: {len(times_valid)}")

    # Apply deployment masking if available
    if use_csv_masking:
        deployed_mask = apply_deployment_masking(
            [ds1_1m, ds1_2m, ds2_1m, ds2_2m],
            [
                site1_sensors["1m"],
                site1_sensors["2m"],
                site2_sensors["1m"],
                site2_sensors["2m"],
            ],
            times_valid,
            [temp1_1m_valid, temp1_2m_valid, temp2_1m_valid, temp2_2m_valid],
            csv_deployment_path,
            site1_name,
            site2_name,
        )
    else:
        deployed_mask = np.ones(len(times_valid), dtype=bool)

    # Resample to hourly averages for lapse rate calculations
    temp_arrays = [temp1_1m_valid, temp1_2m_valid, temp2_1m_valid, temp2_2m_valid]
    times_hourly, temp_arrays_hourly, deployed_mask_hourly = resample_to_hourly(
        times_valid, temp_arrays, deployed_mask
    )

    if times_hourly is None:
        print(f"  No valid hourly data for sites {site1_name} and {site2_name}")
        return False

    # Extract hourly temperature data
    temp1_1m_hourly, temp1_2m_hourly, temp2_1m_hourly, temp2_2m_hourly = (
        temp_arrays_hourly
    )

    # Calculate temperature differences for hourly data
    temp_diff1_hourly = temp1_2m_hourly - temp1_1m_hourly  # Site 1: 2m - 1m
    temp_diff2_hourly = temp2_2m_hourly - temp2_1m_hourly  # Site 2: 2m - 1m

    # Calculate lapse rate between sites using hourly 2m sensors
    elevation1 = site_elevations.get(site1_name, 0)
    elevation2 = site_elevations.get(site2_name, 0)
    elevation_diff_km = abs(elevation1 - elevation2) / 1000.0  # Convert to km

    if elevation_diff_km > 0:
        # Lapse rate: temperature difference per km of elevation
        # Higher elevation should be colder, so we calculate appropriately
        if elevation1 > elevation2:
            lapse_rate_hourly = (temp1_2m_hourly - temp2_2m_hourly) / elevation_diff_km
        else:
            lapse_rate_hourly = (temp2_2m_hourly - temp1_2m_hourly) / elevation_diff_km
    else:
        print("Warning: No elevation difference between sites!")
        lapse_rate_hourly = np.zeros_like(temp1_2m_hourly)

    print(f"Hourly data points for analysis: {len(times_hourly)}")

    # Create figure with 2x3 subplot layout
    fig = plt.figure(figsize=(24, 16))
    gs = gridspec.GridSpec(2, 3, hspace=0.3, wspace=0.3)

    deployed_pct = np.sum(deployed_mask) / len(deployed_mask) * 100
    masking_method = "CSV-based" if use_csv_masking else "Automatic detection"

    fig.suptitle(
        f"Two-Site Lapse Rate Comparison: {site1_name} ({elevation1}m) vs {site2_name} ({elevation2}m)\n"
        f"Elevation Difference: {abs(elevation1 - elevation2):.0f}m | "
        f"Deployment Masking ({masking_method}): {deployed_pct:.1f}% of data during field deployment",
        fontsize=16,
        fontweight="bold",
    )

    # Define subplot positions
    ax_lapse_time = fig.add_subplot(gs[0, 0])  # Lapse rate over time
    ax_lapse_hist = fig.add_subplot(gs[0, 1])  # Lapse rate histogram
    ax_corr_time = fig.add_subplot(gs[0, 2])  # Rolling correlation
    ax_corr_hourly = fig.add_subplot(gs[1, 0])  # Correlation by hour
    ax_temp_diff = fig.add_subplot(gs[1, 1])  # Temperature differences
    ax_diff_corr = fig.add_subplot(gs[1, 2])  # Temp diff correlation

    # Get deployment period limits for timeseries x-axis
    deployed_times = times_valid[deployed_mask]
    if len(deployed_times) > 0:
        deploy_start = deployed_times[0]
        deploy_end = deployed_times[-1]
    else:
        deploy_start = times_valid[0]
        deploy_end = times_valid[-1]

    # Plot 1: Lapse rate over time (hourly data)
    plot_lapse_rate_timeseries(
        ax_lapse_time,
        times_hourly,
        lapse_rate_hourly,
        deployed_mask_hourly,
        site1_name,
        site2_name,
        elevation_diff_km,
        deploy_start,
        deploy_end,
    )

    # Plot 2: Lapse rate histogram binned by temperature (hourly data)
    plot_lapse_rate_histogram(
        ax_lapse_hist,
        lapse_rate_hourly,
        temp1_2m_hourly,
        temp2_2m_hourly,
        deployed_mask_hourly,
        site1_name,
        site2_name,
    )

    # Plot 3: Rolling correlation between sites (10-min data for smoothness)
    plot_rolling_correlation(
        ax_corr_time,
        times_valid,
        temp1_2m_valid,
        temp2_2m_valid,
        deployed_mask,
        site1_name,
        site2_name,
        deploy_start,
        deploy_end,
    )

    # Plot 4: Correlation by time of day with std dev
    plot_correlation_by_hour_with_std(
        ax_corr_hourly,
        times_valid,
        temp1_2m_valid,
        temp2_2m_valid,
        deployed_mask,
        site1_name,
        site2_name,
    )

    # Plot 5: Temperature regression between sites (2m and 1m sensors)
    plot_temperature_regression(
        ax_temp_diff,
        temp1_1m_hourly,
        temp1_2m_hourly,
        temp2_1m_hourly,
        temp2_2m_hourly,
        deployed_mask_hourly,
        site1_name,
        site2_name,
    )

    # Plot 6: Temperature difference correlation with Huber regression
    plot_temp_diff_correlation_huber(
        ax_diff_corr,
        temp_diff1_hourly,
        temp_diff2_hourly,
        deployed_mask_hourly,
        site1_name,
        site2_name,
    )

    # Save plot
    output_file = output_dir / f"{site1_name}_vs_{site2_name}_lapse_rate_comparison.png"
    plt.savefig(output_file, dpi=300, bbox_inches="tight")
    plt.close()

    print(f"  Comparison plot saved: {output_file}")
    return True


def apply_deployment_masking(
    datasets,
    sensor_info,
    times_valid,
    temp_arrays,
    csv_deployment_path,
    site1_name,
    site2_name,
):
    """Apply deployment masking to all sensors"""

    print(f"  Applying CSV masking for {site1_name} vs {site2_name}:")

    deployed_masks = []
    for ds, sensor_info_item, temp_array in zip(datasets, sensor_info, temp_arrays):
        site_name = ds.attrs.get("site_name", "Unknown")
        height = ds.attrs.get("sensor_height", "Unknown")
        sensor_id = ds.attrs.get("sensor_id", "Unknown")

        csv_filename = find_matching_csv_filename(
            sensor_id, site_name, height, csv_deployment_path
        )

        print(f"    {site_name} {height}: {csv_filename}")

        if csv_filename:
            deployed = mask_from_csv_deployment_periods(
                temp_array, times_valid, csv_filename, csv_deployment_path
            )
            deployed_masks.append(deployed)
        else:
            # Fall back to all True if no CSV match
            deployed_masks.append(np.ones(len(times_valid), dtype=bool))

    # Combined mask: all sensors must be deployed
    combined_mask = np.all(deployed_masks, axis=0)

    print(
        f"    Combined deployment: {np.sum(combined_mask)}/{len(combined_mask)} points"
    )

    return combined_mask


def plot_lapse_rate_timeseries(
    ax,
    times,
    lapse_rate,
    deployed_mask,
    site1_name,
    site2_name,
    elevation_diff_km,
    deploy_start,
    deploy_end,
):
    """Plot lapse rate over time"""

    # Since we're using hourly data, all data should be deployed
    # Plot hourly lapse rate data
    ax.plot(
        times,
        lapse_rate,
        color="blue",
        alpha=0.8,
        linewidth=0.8,
        label="Hourly lapse rate",
    )

    # Add reference lines
    ax.axhline(y=0, color="black", linestyle="--", alpha=0.8, linewidth=1)
    ax.axhline(
        y=-6.5,
        color="red",
        linestyle=":",
        alpha=0.8,
        linewidth=1,
        label="Standard lapse rate (-6.5°C/km)",
    )

    # Hourly data is already filtered to deployed periods only

    ax.set_title(
        f"Lapse Rate: {site1_name} vs {site2_name} (Δz={elevation_diff_km:.1f}km)"
    )
    ax.set_ylabel("Lapse Rate (°C/km)")
    ax.set_ylim(-20, 20)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right")

    # Format x-axis and limit to deployment period
    ax.set_xlim(deploy_start, deploy_end)
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
    ax.tick_params(axis="x", rotation=45)


def plot_lapse_rate_histogram(
    ax, lapse_rate, temp1_2m, temp2_2m, deployed_mask, site1_name, site2_name
):
    """Plot histogram of lapse rates with 0.1°C bin width"""

    # Use deployed data only (hourly data is already filtered)
    lapse_deployed = lapse_rate[deployed_mask]

    if len(lapse_deployed) == 0:
        ax.text(
            0.5,
            0.5,
            "No deployed data",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        return

    # Calculate bins with 0.1°C/km width
    data_min = np.floor(np.min(lapse_deployed) * 1) / 1  # Round down to nearest 0.1
    data_max = np.ceil(np.max(lapse_deployed) * 1) / 1  # Round up to nearest 0.1
    bins = np.arange(data_min, data_max + 1e-8, 1)

    # Plot single histogram without temperature groupings
    ax.hist(
        lapse_deployed,
        bins=bins,
        alpha=0.7,
        color="blue",
        density=True,
        edgecolor="darkblue",
        linewidth=0.5,
        label=f"All data (n={len(lapse_deployed)})",
    )

    # Add reference lines
    ax.axvline(
        x=0,
        color="black",
        linestyle="--",
        alpha=0.8,
        linewidth=1,
        label="Zero lapse rate",
    )
    ax.axvline(
        x=-6.5,
        color="red",
        linestyle=":",
        alpha=0.8,
        linewidth=2,
        label="Standard lapse rate (-6.5°C/km)",
    )

    # Statistics
    if len(lapse_deployed) > 0:
        ax.axvline(
            x=np.mean(lapse_deployed),
            color="darkred",
            linestyle="-",
            alpha=0.8,
            linewidth=2,
            label=f"Mean: {np.mean(lapse_deployed):.1f}°C/km",
        )
        ax.axvline(
            x=np.median(lapse_deployed),
            color="green",
            linestyle="-",
            alpha=0.8,
            linewidth=2,
            label=f"Median: {np.median(lapse_deployed):.1f}°C/km",
        )

    ax.set_title("Lapse Rate Distribution (0.1°C/km bins)")
    ax.set_xlabel("Lapse Rate (°C/km)")
    ax.set_ylabel("Density")
    ax.set_xlim(-20, 20)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="upper right", fontsize=8)


def plot_rolling_correlation(
    ax,
    times,
    temp1_2m,
    temp2_2m,
    deployed_mask,
    site1_name,
    site2_name,
    deploy_start,
    deploy_end,
):
    """Plot rolling correlation between sites over time"""

    # Calculate rolling correlation
    df = pd.DataFrame(
        {
            "datetime": times,
            "temp1": temp1_2m,
            "temp2": temp2_2m,
            "deployed": deployed_mask,
        }
    )
    df.set_index("datetime", inplace=True)

    # Calculate rolling correlation with 24-hour window
    window_size = "24H"
    rolling_corr = (
        df["temp1"].rolling(window=window_size, min_periods=10).corr(df["temp2"])
    )

    # Plot correlation
    valid_mask = ~np.isnan(rolling_corr)
    ax.plot(
        rolling_corr.index[valid_mask],
        rolling_corr.values[valid_mask],
        color="blue",
        alpha=0.8,
        linewidth=1.5,
        label="24h Rolling Correlation",
    )

    # Reference lines
    ax.axhline(y=1.0, color="red", linestyle="--", alpha=0.8, linewidth=1)
    ax.axhline(y=0.8, color="orange", linestyle=":", alpha=0.8, linewidth=1)

    ax.set_title(f"Temperature Correlation: {site1_name} vs {site2_name} (2m sensors)")
    ax.set_ylabel("Correlation Coefficient")
    ax.set_ylim(0, 1)
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower right")

    # Format x-axis and limit to deployment period
    ax.set_xlim(deploy_start, deploy_end)
    ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
    ax.tick_params(axis="x", rotation=45)


def plot_correlation_by_hour_with_std(
    ax, times, temp1_2m, temp2_2m, deployed_mask, site1_name, site2_name
):
    """Plot correlation by time of day"""

    # Use deployed data only
    times_deployed = times[deployed_mask]
    temp1_deployed = temp1_2m[deployed_mask]
    temp2_deployed = temp2_2m[deployed_mask]

    if len(times_deployed) < 100:
        ax.text(
            0.5,
            0.5,
            "Insufficient deployed data",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        return

    # Convert to pandas for easier manipulation
    df = pd.DataFrame(
        {"datetime": times_deployed, "temp1": temp1_deployed, "temp2": temp2_deployed}
    )
    df.set_index("datetime", inplace=True)
    df["hour"] = pd.to_datetime(df.index).hour

    # Calculate correlation and within-hour std dev for each hour
    hourly_corr = []
    hourly_std1 = []  # Site 1 within-hour std dev
    hourly_std2 = []  # Site 2 within-hour std dev
    hours = range(24)

    for hour in hours:
        hour_data = df[df["hour"] == hour]
        if len(hour_data) >= 10:  # Need minimum data points
            try:
                corr, _ = pearsonr(hour_data["temp1"].values, hour_data["temp2"].values)
                std1 = df.loc[
                    df.datetime.dt.hour == hour, "temp1"
                ].std()  # Within-hour variability for site 1
                std2 = df.loc[
                    df.datetime.dt.hour == hour, "temp2"
                ].std()  # Within-hour variability for site 2

                if not np.isnan(corr) and not np.isnan(std1) and not np.isnan(std2):
                    hourly_corr.append(corr)
                    hourly_std1.append(std1)
                    hourly_std2.append(std2)
                else:
                    hourly_corr.append(np.nan)
                    hourly_std1.append(np.nan)
                    hourly_std2.append(np.nan)
            except Exception:
                hourly_corr.append(np.nan)
                hourly_std1.append(np.nan)
                hourly_std2.append(np.nan)
        else:
            hourly_corr.append(np.nan)
            hourly_std1.append(np.nan)
            hourly_std2.append(np.nan)

    # Plot correlation by hour
    valid_hours = [h for h, c in zip(hours, hourly_corr) if not np.isnan(c)]
    valid_corr = [c for c in hourly_corr if not np.isnan(c)]
    valid_std1 = [hourly_std1[h] for h in valid_hours]
    valid_std2 = [hourly_std2[h] for h in valid_hours]

    if len(valid_corr) > 0:
        # Plot correlation on primary axis
        ax.plot(
            valid_hours,
            valid_corr,
            "black",
            alpha=0.8,
            linewidth=3,
            markersize=6,
            label="Correlation",
        )

        # Create second y-axis for standard deviations
        ax2 = ax.twinx()
        ax2.plot(
            valid_hours,
            valid_std1,
            "r^-",
            alpha=0.7,
            linewidth=1,
            markersize=4,
            label=f"{site1_name} Within-Hour Std",
        )
        ax2.plot(
            valid_hours,
            valid_std2,
            "g^-",
            alpha=0.7,
            linewidth=1,
            markersize=4,
            label=f"{site2_name} Within-Hour Std",
        )
        ax2.set_ylabel("Temperature Std Dev (°C)", color="red")
        ax2.tick_params(axis="y", labelcolor="red")

    # Reference lines
    ax.axhline(y=1.0, color="red", linestyle="--", alpha=0.8, linewidth=1)
    ax.axhline(y=0.8, color="orange", linestyle=":", alpha=0.8, linewidth=1)

    ax.set_title(
        f"Hourly Correlation & Within-Hour Variability: {site1_name} vs {site2_name}"
    )
    ax.set_xlabel("Hour of Day")
    ax.set_ylabel("Correlation Coefficient", color="blue")
    ax.tick_params(axis="y", labelcolor="blue")
    ax.set_xlim(-0.5, 23.5)
    ax.set_ylim(0, 1)
    ax.set_xticks(range(0, 24, 4))
    ax.set_xticklabels(["00:00", "04:00", "08:00", "12:00", "16:00", "20:00"])
    ax.grid(True, alpha=0.3)

    # Combined legend
    if len(valid_corr) > 0:
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, loc="upper right", fontsize=8)


def plot_temperature_regression(
    ax, temp1_1m, temp1_2m, temp2_1m, temp2_2m, deployed_mask, site1_name, site2_name
):
    """Plot temperature regression between sites for 2m and 1m sensors"""

    # Use deployed data only
    temp1_1m_deployed = temp1_1m[deployed_mask]
    temp1_2m_deployed = temp1_2m[deployed_mask]
    temp2_1m_deployed = temp2_1m[deployed_mask]
    temp2_2m_deployed = temp2_2m[deployed_mask]

    if len(temp1_2m_deployed) == 0:
        ax.text(
            0.5,
            0.5,
            "No deployed data",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        return

    # Create scatter plots for 2m and 1m sensors
    ax.scatter(
        temp1_2m_deployed,
        temp2_2m_deployed,
        alpha=0.3,
        s=1,
        color="blue",
        label="2m sensors",
    )
    ax.scatter(
        temp1_1m_deployed,
        temp2_1m_deployed,
        alpha=0.3,
        s=1,
        color="red",
        label="1m sensors",
    )

    # Calculate and plot Huber regression for 2m sensors
    if len(temp1_2m_deployed) > 10:
        try:
            # Fit Huber regression for 2m sensors
            huber_2m = HuberRegressor(epsilon=1.35, max_iter=100)
            X_2m = temp1_2m_deployed.reshape(-1, 1)
            huber_2m.fit(X_2m, temp2_2m_deployed)

            # Calculate correlation for 2m
            corr_2m, p_val_2m = pearsonr(temp1_2m_deployed, temp2_2m_deployed)

            # Plot regression line for 2m
            x_range_2m = np.linspace(
                temp1_2m_deployed.min(), temp1_2m_deployed.max(), 100
            )
            y_pred_2m = huber_2m.predict(x_range_2m.reshape(-1, 1))
            ax.plot(
                x_range_2m,
                y_pred_2m,
                "b--",
                alpha=0.8,
                linewidth=2,
                label=f"2m Huber fit (r={corr_2m:.3f})",
            )

        except Exception:
            pass

    # Calculate and plot Huber regression for 1m sensors
    if len(temp1_1m_deployed) > 10:
        try:
            # Fit Huber regression for 1m sensors
            huber_1m = HuberRegressor(epsilon=1.35, max_iter=100)
            X_1m = temp1_1m_deployed.reshape(-1, 1)
            huber_1m.fit(X_1m, temp2_1m_deployed)

            # Calculate correlation for 1m
            corr_1m, p_val_1m = pearsonr(temp1_1m_deployed, temp2_1m_deployed)

            # Plot regression line for 1m
            x_range_1m = np.linspace(
                temp1_1m_deployed.min(), temp1_1m_deployed.max(), 100
            )
            y_pred_1m = huber_1m.predict(x_range_1m.reshape(-1, 1))
            ax.plot(
                x_range_1m,
                y_pred_1m,
                "r--",
                alpha=0.8,
                linewidth=2,
                label=f"1m Huber fit (r={corr_1m:.3f})",
            )

        except Exception:
            pass

    # Reference lines
    ax.axhline(y=0, color="black", linestyle="-", alpha=0.5, linewidth=1)
    ax.axvline(x=0, color="black", linestyle="-", alpha=0.5, linewidth=1)

    # 1:1 line
    lims = [
        np.min([ax.get_xlim(), ax.get_ylim()]),
        np.max([ax.get_xlim(), ax.get_ylim()]),
    ]
    ax.plot(lims, lims, "k:", alpha=0.5, linewidth=1, label="1:1 line")

    ax.set_title(f"Temperature Regression: {site1_name} vs {site2_name}")
    ax.set_xlabel(f"{site1_name} Temperature (°C)")
    ax.set_ylabel(f"{site2_name} Temperature (°C)")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower right", fontsize=8)

    # Make axes equal
    ax.set_aspect("equal", adjustable="box")


def plot_temp_diff_correlation_huber(
    ax, temp_diff1, temp_diff2, deployed_mask, site1_name, site2_name
):
    """Plot correlation of temperature differences between sites"""

    # Use deployed data only
    diff1_deployed = temp_diff1[deployed_mask]
    diff2_deployed = temp_diff2[deployed_mask]

    if len(diff1_deployed) == 0:
        ax.text(
            0.5,
            0.5,
            "No deployed data",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        return

    # Create scatter plot
    ax.scatter(diff1_deployed, diff2_deployed, alpha=0.3, s=1, color="blue")

    # Calculate correlation and Huber regression
    if len(diff1_deployed) > 10:
        try:
            # Calculate correlation
            corr, p_value = pearsonr(diff1_deployed, diff2_deployed)

            # Fit Huber regression
            huber = HuberRegressor(epsilon=1.35, max_iter=100)
            X = diff1_deployed.reshape(-1, 1)
            huber.fit(X, diff2_deployed)

            if not np.isnan(corr):
                ax.text(
                    0.05,
                    0.95,
                    f"r = {corr:.3f}\np = {p_value:.3e}\nn = {len(diff1_deployed)}",
                    transform=ax.transAxes,
                    verticalalignment="top",
                    bbox=dict(boxstyle="round", facecolor="white", alpha=0.8),
                )

                # Add Huber regression line
                x_range = np.linspace(diff1_deployed.min(), diff1_deployed.max(), 100)
                y_pred = huber.predict(x_range.reshape(-1, 1))
                ax.plot(
                    x_range,
                    y_pred,
                    "r--",
                    alpha=0.8,
                    linewidth=2,
                    label="Huber regression",
                )
        except Exception:
            pass

    # Reference lines
    ax.axhline(y=0, color="black", linestyle="-", alpha=0.5, linewidth=1)
    ax.axvline(x=0, color="black", linestyle="-", alpha=0.5, linewidth=1)

    # 1:1 line
    lims = [
        np.min([ax.get_xlim(), ax.get_ylim()]),
        np.max([ax.get_xlim(), ax.get_ylim()]),
    ]
    ax.plot(lims, lims, "k:", alpha=0.5, linewidth=1, label="1:1 line")

    ax.set_title(f"Temperature Difference Correlation\n{site1_name} vs {site2_name}")
    ax.set_xlabel(f"{site1_name} Temp Diff (2m - 1m) [°C]")
    ax.set_ylabel(f"{site2_name} Temp Diff (2m - 1m) [°C]")
    ax.grid(True, alpha=0.3)
    ax.legend(loc="lower right")

    # Make axes equal
    ax.set_aspect("equal", adjustable="box")


if __name__ == "__main__":
    main()
