#!/usr/bin/env python3
"""
within_group_lapse_rate_analysis.py

Analyze lapse rates and correlations between sites within the same letter group
(e.g., A01/A03, B01/B02/B03, D01/D02/D04) and custom site sequences.
Creates comprehensive visualizations including:
1. Mean temperature vs elevation scatterplots (all-times, day, night)
2. Lapse rate histograms for multiple temporal resolutions
3. Temporal lapse rate analysis and pairwise covariance

Author: Generated by Claude Code
Created: 2025-07-30
Updated: 2025-07-30
"""

import pandas as pd
import numpy as np
import xarray as xr
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import matplotlib.gridspec as gridspec
from pathlib import Path
from tqdm import tqdm
import warnings
from scipy.stats import linregress
from itertools import combinations

# Add src to path so we can import jiflr
import sys
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from jiflr.plotting import (
    apply_plot_styling, format_axes_list, save_publication_figure,
    get_color_palette, setup_basic_axes
)

warnings.filterwarnings("ignore")

# ========== CONFIGURATION ==========

# Custom site sequences to analyze (in addition to automatic letter groups)
CUSTOM_SEQUENCES = [
    ["D04", "D02", "D01", "A03", "TKG4"],  # Elevation transect example
    # Add more custom sequences here as needed
    # ['B01', 'B02', 'B03', 'C02'],  # Another example
]

# Time period definitions (hours in 24-hour format)
TIME_PERIODS = {
    "all_times": (0, 24),  # 24-hour
    "daytime": (4, 20),  # 4am-8pm
    "nighttime": (20, 4),  # 8pm-4am (wraps around midnight)
}

# Temporal resolutions for lapse rate analysis
TEMPORAL_RESOLUTIONS = ["10min", "1H", "3H"]

# ========== END CONFIGURATION ==========

from jiflr import ROOT
from jiflr.utils import (
    mask_from_csv_deployment_periods,
    find_matching_csv_filename,
)


def main():
    # Define paths
    processed_dir = Path(ROOT) / "data" / "2025" / "processed"
    output_dir = Path(__file__).parent / "output"
    csv_deployment_path = Path(ROOT) / "deployment_periods.csv"

    print("=== Within-Group Lapse Rate Analysis ===")
    print(f"Processed directory: {processed_dir}")
    print(f"Output directory: {output_dir}")
    print(f"CSV deployment periods: {csv_deployment_path}")

    # Check if CSV deployment file exists
    use_csv_masking = csv_deployment_path.exists()
    if use_csv_masking:
        print("Found deployment periods CSV - using CSV-based masking")
    else:
        print("No deployment periods CSV found - using automatic detection only")

    # Load site elevation data
    site_elevations = load_site_elevations(csv_deployment_path)

    # Get all NetCDF files
    netcdf_files = list(processed_dir.glob("*.nc"))
    print(f"\nFound {len(netcdf_files)} NetCDF files")

    if not netcdf_files:
        print("No NetCDF files found!")
        return

    # Load and organize datasets by site
    site_data = load_site_data(netcdf_files)

    # Filter sites that have both 1m and 2m sensors
    sites_with_both = {}
    required_heights = ["1m", "2m"]

    for site_name, sensors in site_data.items():
        if all(height in sensors for height in required_heights):
            sites_with_both[site_name] = sensors

    print(f"\nFound {len(sites_with_both)} sites with both 1m and 2m sensors:")
    for site_name in sorted(sites_with_both.keys()):
        elevation = site_elevations.get(site_name, "Unknown")
        print(f"  - {site_name} ({elevation}m)")

    # Group sites by letter prefix and add custom sequences
    site_groups = group_sites_by_prefix(sites_with_both, site_elevations)
    custom_groups = process_custom_sequences(sites_with_both, site_elevations)
    site_groups.update(custom_groups)

    print(f"\nIdentified {len(site_groups)} site groups:")
    for group_name, group_info in site_groups.items():
        sites_str = ", ".join(
            [
                f"{site}({group_info['elevations'][site]}m)"
                for site in group_info["sites"]
            ]
        )
        print(f"  - {group_name}: {sites_str}")

    if len(site_groups) == 0:
        print("No site groups with 2+ sites found!")
        return

    # Generate analysis for each group
    successful_groups = 0
    failed_groups = 0

    for group_name, group_info in site_groups.items():
        print(f"\n=== Analyzing {group_name} Group ===")

        try:
            success = create_group_analysis_plot(
                group_name,
                group_info,
                sites_with_both,
                site_elevations,
                output_dir,
                csv_deployment_path,
                use_csv_masking,
            )

            if success:
                successful_groups += 1
            else:
                failed_groups += 1

        except Exception as e:
            print(f"  Error analyzing {group_name} group: {e}")
            failed_groups += 1

    print(f"\n=== Analysis Complete ===")
    print(f"Successfully analyzed: {successful_groups} groups")
    print(f"Failed: {failed_groups} groups")
    print(f"Output directory: {output_dir}")


def load_site_elevations(csv_deployment_path):
    """Load site elevation data from deployment CSV"""
    elevations = {}
    if csv_deployment_path.exists():
        df = pd.read_csv(csv_deployment_path)
        for _, row in df.iterrows():
            site = row["site"]
            elevation = row["site_elevation"]
            if pd.notna(site) and pd.notna(elevation):
                elevations[site] = float(elevation)
    return elevations


def load_site_data(netcdf_files):
    """Load and organize NetCDF datasets by site"""
    site_data = {}

    for nc_file in tqdm(netcdf_files, desc="Loading datasets"):
        try:
            ds = xr.open_dataset(nc_file)

            site_name = ds.attrs.get("site_name", "Unknown")
            sensor_height = ds.attrs.get("sensor_height", "Unknown")
            sensor_id = ds.attrs.get("sensor_id", "Unknown")

            site_key = site_name if site_name != "Unknown" else f"Sensor_{sensor_id}"

            if site_key not in site_data:
                site_data[site_key] = {}

            if sensor_height in ["1m", "2m"]:
                # Store original CSV filename for deployment masking
                original_csv_filename = None
                if hasattr(ds, "attrs") and "original_filename" in ds.attrs:
                    original_csv_filename = ds.attrs["original_filename"]
                else:
                    original_csv_filename = nc_file.name

                site_data[site_key][sensor_height] = {
                    "dataset": ds,
                    "sensor_id": sensor_id,
                    "file": nc_file.name,
                    "original_csv_filename": original_csv_filename,
                }

        except Exception as e:
            print(f"Error loading {nc_file}: {e}")
            continue

    return site_data


def group_sites_by_prefix(sites_with_both, site_elevations):
    """Group sites by their letter prefix (A, B, D, etc.)"""

    groups = {}

    for site_name in sites_with_both.keys():
        # Extract letter prefix (e.g., 'A' from 'A01', 'TKG' from 'TKG4')
        if site_name[0].isalpha():
            # Handle cases like 'TKG4' - take all leading letters
            prefix = ""
            for char in site_name:
                if char.isalpha():
                    prefix += char
                else:
                    break
        else:
            continue  # Skip sites that don't start with letter

        if prefix not in groups:
            groups[prefix] = {"sites": [], "elevations": {}}

        groups[prefix]["sites"].append(site_name)
        groups[prefix]["elevations"][site_name] = site_elevations.get(site_name, 0)

    # Filter groups with 2+ sites and sort by elevation
    filtered_groups = {}
    for prefix, group_info in groups.items():
        if len(group_info["sites"]) >= 2:
            # Sort sites by elevation (ascending)
            sorted_sites = sorted(
                group_info["sites"], key=lambda x: group_info["elevations"][x]
            )
            group_info["sites"] = sorted_sites
            filtered_groups[prefix] = group_info

    return filtered_groups


def process_custom_sequences(sites_with_both, site_elevations):
    """Process custom site sequences defined in CUSTOM_SEQUENCES"""

    custom_groups = {}

    for i, sequence in enumerate(CUSTOM_SEQUENCES):
        # Check if all sites in sequence are available
        available_sites = [site for site in sequence if site in sites_with_both]

        if len(available_sites) >= 2:  # Need at least 2 sites for analysis
            group_name = f"Custom_{i + 1}"

            # Create group info structure
            group_info = {"sites": available_sites, "elevations": {}}

            # Add elevation info for each site
            for site in available_sites:
                group_info["elevations"][site] = site_elevations.get(site, 0)

            # Sort sites by elevation (ascending) - maintain elevation order
            sorted_sites = sorted(
                available_sites, key=lambda x: group_info["elevations"][x]
            )
            group_info["sites"] = sorted_sites

            custom_groups[group_name] = group_info

            print(f"  Added custom sequence {group_name}: {sequence}")
            if len(available_sites) < len(sequence):
                missing_sites = [
                    site for site in sequence if site not in sites_with_both
                ]
                print(f"    Note: Missing sites {missing_sites}")
        else:
            missing_sites = [site for site in sequence if site not in sites_with_both]
            print(
                f"  Skipping custom sequence {sequence} - insufficient available sites"
            )
            print(f"    Available: {available_sites}, Missing: {missing_sites}")

    return custom_groups


def create_group_analysis_plot(
    group_name,
    group_info,
    sites_with_both,
    site_elevations,
    output_dir,
    csv_deployment_path,
    use_csv_masking,
):
    """Create comprehensive analysis plot for a site group"""

    sites = group_info["sites"]
    print(f"  Analyzing {len(sites)} sites: {', '.join(sites)}")

    # Collect all site combinations within the group
    site_combinations = list(combinations(sites, 2))
    print(f"  Processing {len(site_combinations)} site pairs")

    # Data collection for group analysis
    group_data = {
        "site_pairs": [],
        "lapse_rates": [],
        "correlations": [],
        "temp_diffs": [],
        "times": [],
        "elevations": [],
    }

    # Process each site pair
    valid_pairs = 0
    for site1, site2 in site_combinations:
        print(f"    Processing {site1} vs {site2}")

        try:
            pair_data = process_site_pair(
                site1,
                sites_with_both[site1],
                site2,
                sites_with_both[site2],
                site_elevations,
                csv_deployment_path,
                use_csv_masking,
            )

            if pair_data:
                group_data["site_pairs"].append(f"{site1}-{site2}")
                group_data["lapse_rates"].append(pair_data["lapse_rate"])
                group_data["correlations"].append(pair_data["correlation"])
                group_data["temp_diffs"].append(pair_data["temp_diffs"])
                group_data["times"].append(pair_data["times"])
                group_data["elevations"].append(pair_data["elevation_diff"])
                valid_pairs += 1

        except Exception as e:
            print(f"      Error processing {site1} vs {site2}: {e}")
            continue

    if valid_pairs == 0:
        print(f"  No valid site pairs found for {group_name} group")
        return False

    print(f"  Successfully processed {valid_pairs} site pairs")

    # Calculate mean temperatures by time period for each site
    site_temp_data = calculate_site_temperature_data(
        sites, sites_with_both, site_elevations, csv_deployment_path, use_csv_masking
    )

    # Create comprehensive group visualization
    success = create_group_visualization(
        group_name,
        group_data,
        sites,
        site_elevations,
        site_temp_data,
        sites_with_both,
        csv_deployment_path,
        use_csv_masking,
        output_dir,
    )

    return success


def process_site_pair(
    site1_name,
    site1_sensors,
    site2_name,
    site2_sensors,
    site_elevations,
    csv_deployment_path,
    use_csv_masking,
):
    """Process a single site pair and return analysis data"""

    # Extract datasets
    ds1_1m = site1_sensors["1m"]["dataset"]
    ds1_2m = site1_sensors["2m"]["dataset"]
    ds2_1m = site2_sensors["1m"]["dataset"]
    ds2_2m = site2_sensors["2m"]["dataset"]

    # Get temperature data
    temp1_1m = ds1_1m["temp_c"].dropna("datetime")
    temp1_2m = ds1_2m["temp_c"].dropna("datetime")
    temp2_1m = ds2_1m["temp_c"].dropna("datetime")
    temp2_2m = ds2_2m["temp_c"].dropna("datetime")

    # Find overlapping time period
    start_time = max(
        temp1_1m.datetime.min().values,
        temp1_2m.datetime.min().values,
        temp2_1m.datetime.min().values,
        temp2_2m.datetime.min().values,
    )
    end_time = min(
        temp1_1m.datetime.max().values,
        temp1_2m.datetime.max().values,
        temp2_1m.datetime.max().values,
        temp2_2m.datetime.max().values,
    )

    if start_time >= end_time:
        return None

    # Create common time grid
    common_times = pd.date_range(start_time, end_time, freq="10min")

    # Interpolate all sensors to common time grid
    temp1_1m_interp = temp1_1m.interp(datetime=common_times, method="linear")
    temp1_2m_interp = temp1_2m.interp(datetime=common_times, method="linear")
    temp2_1m_interp = temp2_1m.interp(datetime=common_times, method="linear")
    temp2_2m_interp = temp2_2m.interp(datetime=common_times, method="linear")

    # Drop NaN values
    valid_mask = ~(
        np.isnan(temp1_1m_interp.values)
        | np.isnan(temp1_2m_interp.values)
        | np.isnan(temp2_1m_interp.values)
        | np.isnan(temp2_2m_interp.values)
    )

    times_valid = common_times[valid_mask]
    temp1_1m_valid = temp1_1m_interp.values[valid_mask]
    temp1_2m_valid = temp1_2m_interp.values[valid_mask]
    temp2_1m_valid = temp2_1m_interp.values[valid_mask]
    temp2_2m_valid = temp2_2m_interp.values[valid_mask]

    if len(times_valid) == 0:
        return None

    # Apply deployment masking if available
    if use_csv_masking:
        deployed_mask = apply_deployment_masking(
            [ds1_1m, ds1_2m, ds2_1m, ds2_2m],
            [
                site1_sensors["1m"],
                site1_sensors["2m"],
                site2_sensors["1m"],
                site2_sensors["2m"],
            ],
            times_valid,
            [temp1_1m_valid, temp1_2m_valid, temp2_1m_valid, temp2_2m_valid],
            csv_deployment_path,
            site1_name,
            site2_name,
        )
    else:
        deployed_mask = np.ones(len(times_valid), dtype=bool)

    # Resample to hourly averages
    temp_arrays = [temp1_1m_valid, temp1_2m_valid, temp2_1m_valid, temp2_2m_valid]
    times_hourly, temp_arrays_hourly, deployed_mask_hourly = resample_to_hourly(
        times_valid, temp_arrays, deployed_mask
    )

    if times_hourly is None:
        return None

    # Extract hourly temperature data
    temp1_1m_hourly, temp1_2m_hourly, temp2_1m_hourly, temp2_2m_hourly = (
        temp_arrays_hourly
    )

    # Calculate lapse rate
    elevation1 = site_elevations.get(site1_name, 0)
    elevation2 = site_elevations.get(site2_name, 0)
    elevation_diff_km = abs(elevation1 - elevation2) / 1000.0

    if elevation_diff_km > 0:
        if elevation1 > elevation2:
            lapse_rate_hourly = (temp1_2m_hourly - temp2_2m_hourly) / elevation_diff_km
        else:
            lapse_rate_hourly = (temp2_2m_hourly - temp1_2m_hourly) / elevation_diff_km
    else:
        lapse_rate_hourly = np.zeros_like(temp1_2m_hourly)

    # Calculate correlation
    correlation = np.corrcoef(temp1_2m_hourly, temp2_2m_hourly)[0, 1]

    # Calculate temperature differences
    temp_diff1 = temp1_2m_hourly - temp1_1m_hourly
    temp_diff2 = temp2_2m_hourly - temp2_1m_hourly

    return {
        "lapse_rate": lapse_rate_hourly,
        "correlation": correlation,
        "temp_diffs": (temp_diff1, temp_diff2),
        "times": times_hourly,
        "elevation_diff": elevation_diff_km,
        "temps": (temp1_1m_hourly, temp1_2m_hourly, temp2_1m_hourly, temp2_2m_hourly),
    }


def resample_to_hourly(times, temp_arrays, deployed_mask):
    """Resample temperature data to 1-hour averages"""

    df = pd.DataFrame(
        {
            "datetime": times,
            "temp1_1m": temp_arrays[0],
            "temp1_2m": temp_arrays[1],
            "temp2_1m": temp_arrays[2],
            "temp2_2m": temp_arrays[3],
            "deployed": deployed_mask,
        }
    )
    df.set_index("datetime", inplace=True)

    # Only use deployed data for resampling
    df_deployed = df[df["deployed"]].drop(columns=["deployed"])

    if len(df_deployed) == 0:
        return None, None, None

    # Resample to hourly averages
    df_hourly = (
        df_deployed.resample("1H")
        .agg(
            {
                "temp1_1m": "mean",
                "temp1_2m": "mean",
                "temp2_1m": "mean",
                "temp2_2m": "mean",
            }
        )
        .dropna()
    )

    if len(df_hourly) == 0:
        return None, None, None

    # Extract hourly data
    times_hourly = df_hourly.index.values
    temp_arrays_hourly = [
        df_hourly["temp1_1m"].values,
        df_hourly["temp1_2m"].values,
        df_hourly["temp2_1m"].values,
        df_hourly["temp2_2m"].values,
    ]
    deployed_mask_hourly = np.ones(len(times_hourly), dtype=bool)

    return times_hourly, temp_arrays_hourly, deployed_mask_hourly


def apply_deployment_masking(
    datasets,
    sensor_info,
    times_valid,
    temp_arrays,
    csv_deployment_path,
    site1_name,
    site2_name,
):
    """Apply deployment masking to all sensors"""

    deployed_masks = []
    for ds, sensor_info_item, temp_array in zip(datasets, sensor_info, temp_arrays):
        site_name = ds.attrs.get("site_name", "Unknown")
        height = ds.attrs.get("sensor_height", "Unknown")
        sensor_id = ds.attrs.get("sensor_id", "Unknown")

        csv_filename = find_matching_csv_filename(
            sensor_id, site_name, height, csv_deployment_path
        )

        if csv_filename:
            deployed = mask_from_csv_deployment_periods(
                temp_array, times_valid, csv_filename, csv_deployment_path
            )
            deployed_masks.append(deployed)
        else:
            deployed_masks.append(np.ones(len(times_valid), dtype=bool))

    # Combined mask: all sensors must be deployed
    combined_mask = np.all(deployed_masks, axis=0)
    return combined_mask


def calculate_site_temperature_data(
    sites, sites_with_both, site_elevations, csv_deployment_path, use_csv_masking
):
    """Calculate mean temperatures by time period for all sites in the group"""

    site_temp_data = {}

    for site_name in sites:
        if site_name not in sites_with_both:
            continue

        try:
            # Get sensor data
            ds_1m = sites_with_both[site_name]["1m"]["dataset"]
            ds_2m = sites_with_both[site_name]["2m"]["dataset"]

            # Get temperature data
            temp_1m = ds_1m["temp_c"].dropna("datetime")
            temp_2m = ds_2m["temp_c"].dropna("datetime")

            # Find overlapping time period
            start_time = max(
                temp_1m.datetime.min().values, temp_2m.datetime.min().values
            )
            end_time = min(temp_1m.datetime.max().values, temp_2m.datetime.max().values)

            if start_time >= end_time:
                continue

            # Create common time grid (10-minute resolution)
            common_times = pd.date_range(start_time, end_time, freq="10min")

            # Interpolate to common time grid
            temp_1m_interp = temp_1m.interp(datetime=common_times, method="linear")
            temp_2m_interp = temp_2m.interp(datetime=common_times, method="linear")

            # Remove NaN values
            valid_mask = ~(
                np.isnan(temp_1m_interp.values) | np.isnan(temp_2m_interp.values)
            )

            if not np.any(valid_mask):
                continue

            times_valid = common_times[valid_mask]
            temp_1m_valid = temp_1m_interp.values[valid_mask]
            temp_2m_valid = temp_2m_interp.values[valid_mask]

            # Apply deployment masking if available
            if use_csv_masking:
                deployed_mask = apply_deployment_masking(
                    [ds_1m, ds_2m],
                    [
                        sites_with_both[site_name]["1m"],
                        sites_with_both[site_name]["2m"],
                    ],
                    times_valid,
                    [temp_1m_valid, temp_2m_valid],
                    csv_deployment_path,
                    site_name,
                    site_name,
                )
            else:
                deployed_mask = np.ones(len(times_valid), dtype=bool)

            # Filter to deployed periods only
            if not np.any(deployed_mask):
                continue

            times_deployed = times_valid[deployed_mask]
            temp_1m_deployed = temp_1m_valid[deployed_mask]
            temp_2m_deployed = temp_2m_valid[deployed_mask]

            # Calculate mean temperatures and standard deviations by time period
            temp_means = {}
            temp_stds = {}

            for period_name, (start_hour, end_hour) in TIME_PERIODS.items():
                if period_name == "nighttime" and end_hour < start_hour:
                    # Handle wrap-around for nighttime (20:00 to 04:00)
                    time_mask = (pd.Series(times_deployed).dt.hour >= start_hour) | (
                        pd.Series(times_deployed).dt.hour < end_hour
                    )
                else:
                    # Normal time range
                    time_mask = (pd.Series(times_deployed).dt.hour >= start_hour) & (
                        pd.Series(times_deployed).dt.hour < end_hour
                    )

                if np.any(time_mask):
                    temp_means[period_name] = {
                        "1m": np.mean(temp_1m_deployed[time_mask]),
                        "2m": np.mean(temp_2m_deployed[time_mask]),
                    }
                    temp_stds[period_name] = {
                        "1m": np.std(temp_1m_deployed[time_mask], ddof=1),
                        "2m": np.std(temp_2m_deployed[time_mask], ddof=1),
                    }
                else:
                    temp_means[period_name] = {"1m": np.nan, "2m": np.nan}
                    temp_stds[period_name] = {"1m": np.nan, "2m": np.nan}

            site_temp_data[site_name] = {
                "elevation": site_elevations.get(site_name, 0),
                "temp_means": temp_means,
                "temp_stds": temp_stds,
            }

        except Exception as e:
            print(f"    Error processing {site_name} temperature data: {e}")
            continue

    return site_temp_data


def calculate_lapse_rates_multiple_resolutions(
    sites, sites_with_both, site_elevations, csv_deployment_path, use_csv_masking
):
    """Calculate lapse rates for multiple temporal resolutions"""

    lapse_rate_data = {res: [] for res in TEMPORAL_RESOLUTIONS}

    # Process all site pairs
    site_pairs = list(combinations(sites, 2))

    for site1, site2 in site_pairs:
        if site1 not in sites_with_both or site2 not in sites_with_both:
            continue

        try:
            # Process the site pair for different resolutions
            pair_data = process_site_pair_multiple_resolutions(
                site1,
                sites_with_both[site1],
                site2,
                sites_with_both[site2],
                site_elevations,
                csv_deployment_path,
                use_csv_masking,
            )

            if pair_data:
                for resolution in TEMPORAL_RESOLUTIONS:
                    if resolution in pair_data:
                        lapse_rate_data[resolution].extend(pair_data[resolution])

        except Exception as e:
            print(f"    Error processing {site1}-{site2} for multiple resolutions: {e}")
            continue

    return lapse_rate_data


def process_site_pair_multiple_resolutions(
    site1_name,
    site1_sensors,
    site2_name,
    site2_sensors,
    site_elevations,
    csv_deployment_path,
    use_csv_masking,
):
    """Process site pair for multiple temporal resolutions"""

    # Extract datasets
    ds1_1m = site1_sensors["1m"]["dataset"]
    ds1_2m = site1_sensors["2m"]["dataset"]
    ds2_1m = site2_sensors["1m"]["dataset"]
    ds2_2m = site2_sensors["2m"]["dataset"]

    # Get temperature data
    temp1_1m = ds1_1m["temp_c"].dropna("datetime")
    temp1_2m = ds1_2m["temp_c"].dropna("datetime")
    temp2_1m = ds2_1m["temp_c"].dropna("datetime")
    temp2_2m = ds2_2m["temp_c"].dropna("datetime")

    # Find overlapping time period
    start_time = max(
        temp1_1m.datetime.min().values,
        temp1_2m.datetime.min().values,
        temp2_1m.datetime.min().values,
        temp2_2m.datetime.min().values,
    )
    end_time = min(
        temp1_1m.datetime.max().values,
        temp1_2m.datetime.max().values,
        temp2_1m.datetime.max().values,
        temp2_2m.datetime.max().values,
    )

    if start_time >= end_time:
        return None

    # Calculate elevation difference
    elevation1 = site_elevations.get(site1_name, 0)
    elevation2 = site_elevations.get(site2_name, 0)
    elevation_diff_km = abs(elevation1 - elevation2) / 1000.0

    if elevation_diff_km == 0:
        return None

    result_data = {}

    # Process each temporal resolution
    for resolution in TEMPORAL_RESOLUTIONS:
        try:
            # Create time grid for this resolution
            common_times = pd.date_range(start_time, end_time, freq=resolution)

            # Interpolate all sensors to common time grid
            temp1_1m_interp = temp1_1m.interp(datetime=common_times, method="linear")
            temp1_2m_interp = temp1_2m.interp(datetime=common_times, method="linear")
            temp2_1m_interp = temp2_1m.interp(datetime=common_times, method="linear")
            temp2_2m_interp = temp2_2m.interp(datetime=common_times, method="linear")

            # Drop NaN values
            valid_mask = ~(
                np.isnan(temp1_1m_interp.values)
                | np.isnan(temp1_2m_interp.values)
                | np.isnan(temp2_1m_interp.values)
                | np.isnan(temp2_2m_interp.values)
            )

            if not np.any(valid_mask):
                continue

            times_valid = common_times[valid_mask]
            temp1_2m_valid = temp1_2m_interp.values[valid_mask]
            temp2_2m_valid = temp2_2m_interp.values[valid_mask]

            # Apply deployment masking if available
            if use_csv_masking:
                deployed_mask = apply_deployment_masking(
                    [ds1_1m, ds1_2m, ds2_1m, ds2_2m],
                    [
                        site1_sensors["1m"],
                        site1_sensors["2m"],
                        site2_sensors["1m"],
                        site2_sensors["2m"],
                    ],
                    times_valid,
                    [temp1_2m_valid, temp1_2m_valid, temp2_2m_valid, temp2_2m_valid],
                    csv_deployment_path,
                    site1_name,
                    site2_name,
                )
            else:
                deployed_mask = np.ones(len(times_valid), dtype=bool)

            if not np.any(deployed_mask):
                continue

            # Filter to deployed periods
            temp1_2m_deployed = temp1_2m_valid[deployed_mask]
            temp2_2m_deployed = temp2_2m_valid[deployed_mask]

            # Calculate lapse rates
            if elevation1 > elevation2:
                lapse_rates = (
                    temp1_2m_deployed - temp2_2m_deployed
                ) / elevation_diff_km
            else:
                lapse_rates = (
                    temp2_2m_deployed - temp1_2m_deployed
                ) / elevation_diff_km

            result_data[resolution] = lapse_rates.tolist()

        except Exception as e:
            print(f"      Error processing resolution {resolution}: {e}")
            continue

    return result_data


def create_group_visualization(
    group_name,
    group_data,
    sites,
    site_elevations,
    site_temp_data,
    sites_with_both,
    csv_deployment_path,
    use_csv_masking,
    output_dir,
):
    """Create comprehensive visualization for the site group"""

    if len(group_data["site_pairs"]) == 0:
        return False

    # Calculate lapse rates for multiple resolutions
    print(f"  Calculating lapse rates for multiple resolutions...")
    try:
        lapse_rate_data = calculate_lapse_rates_multiple_resolutions(
            sites,
            sites_with_both,
            site_elevations,
            csv_deployment_path,
            use_csv_masking,
        )
    except Exception as e:
        print(f"    Error calculating multi-resolution lapse rates: {e}")
        lapse_rate_data = {res: [] for res in TEMPORAL_RESOLUTIONS}

    # Create figure with 2x2 subplot layout
    fig = plt.figure(figsize=(16, 12))
    gs = gridspec.GridSpec(2, 2, hspace=0.35, wspace=0.25)

    # Title with site information
    sites_str = ", ".join(
        [f"{site}({site_elevations.get(site, '?')}m)" for site in sites]
    )
    fig.suptitle(
        f"{group_name} Site Group Lapse Rate Analysis\n"
        f"Sites: {sites_str} | {len(group_data['site_pairs'])} site pairs analyzed",
        fontsize=16,
        fontweight="bold",
    )

    # Define subplot positions for 2x2 layout
    ax_temp_elev = fig.add_subplot(gs[0, 0])  # Mean temp vs elevation scatterplot
    ax_lapse_hist = fig.add_subplot(
        gs[0, 1]
    )  # Lapse rate histograms (multi-resolution)
    ax_lapse_time = fig.add_subplot(gs[1, 0])  # Temporal lapse rates by time period
    ax_correlation = fig.add_subplot(gs[1, 1])  # Pairwise correlation matrix

    # Plot 1: Mean temperature vs elevation with regression lines
    plot_temp_elevation_relationships(ax_temp_elev, site_temp_data, group_name)

    # Plot 2: Lapse rate histograms for multiple resolutions
    plot_lapse_rate_histograms(
        ax_lapse_hist, lapse_rate_data, site_temp_data, group_name
    )

    # Plot 3: Temporal lapse rates by time period (day/night/all-time)
    plot_temporal_lapse_analysis(ax_lapse_time, group_data, site_temp_data, group_name)

    # Plot 4: Sensor height lapse rate comparison
    plot_sensor_height_lapse_comparison(
        ax_correlation,
        sites,
        sites_with_both,
        site_elevations,
        csv_deployment_path,
        use_csv_masking,
        group_name,
    )

    # Apply standardized styling to all axes in one place
    axes_list = [ax_temp_elev, ax_lapse_hist, ax_lapse_time, ax_correlation]
    setup_basic_axes(axes_list)
    
    # Save using standardized function
    output_filename = f"{group_name}_sites_lapse_rate_analysis"
    save_publication_figure(fig, output_filename, output_dir=output_dir, 
                          formats=['png'], dpi=300)
    plt.close()

    print(f"  Group analysis saved: {output_dir / (output_filename + '.png')}")
    return True


def plot_temp_elevation_relationships(ax, site_temp_data, group_name):
    """Plot mean temperature vs elevation with regression lines and confidence intervals"""

    if not site_temp_data:
        ax.text(
            0.5,
            0.5,
            "No temperature data available",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        ax.set_title(f"{group_name}: Temperature vs Elevation")
        return

    # Extract data for plotting
    elevations = []
    temp_all = []
    temp_day = []
    temp_night = []
    std_all = []
    std_day = []
    std_night = []
    site_names = []

    for site_name, data in site_temp_data.items():
        elevations.append(data["elevation"])
        site_names.append(site_name)

        # Use 2m sensor data for comparison
        temp_all.append(data["temp_means"]["all_times"]["2m"])
        temp_day.append(data["temp_means"]["daytime"]["2m"])
        temp_night.append(data["temp_means"]["nighttime"]["2m"])

        # Get standard deviations for each time period
        std_all.append(data["temp_stds"]["all_times"]["2m"])
        std_day.append(data["temp_stds"]["daytime"]["2m"])
        std_night.append(data["temp_stds"]["nighttime"]["2m"])

    elevations = np.array(elevations)
    temp_all = np.array(temp_all)
    temp_day = np.array(temp_day)
    temp_night = np.array(temp_night)
    std_all = np.array(std_all)
    std_day = np.array(std_day)
    std_night = np.array(std_night)

    # Remove NaN values for each time period
    valid_all = ~np.isnan(temp_all)
    valid_day = ~np.isnan(temp_day)
    valid_night = ~np.isnan(temp_night)

    colors = {"all_times": "blue", "daytime": "orange", "nighttime": "purple"}

    # Function to add regression line with regression standard error
    def add_regression_line(x_vals, y_vals, std_vals, valid_mask, color, label, marker):
        if np.sum(valid_mask) >= 2:  # Need at least 2 points for regression
            x_valid = x_vals[valid_mask]
            y_valid = y_vals[valid_mask]

            # Perform linear regression
            slope, intercept, r_value, _, _ = linregress(x_valid, y_valid)

            # Calculate lapse rate (°C/km)
            lapse_rate = slope * 1000  # Convert from °C/m to °C/km

            # Plot data points first
            ax.plot(
                x_valid, y_valid, marker, color=color, markersize=6, linestyle="None"
            )

            # Plot regression line
            y_pred = slope * x_valid + intercept
            ax.plot(
                x_valid,
                y_pred,
                "-",
                color=color,
                linewidth=2,
                label=f"{label}: {lapse_rate:.1f}°C/km (R²={r_value**2:.3f})",
            )

            # Calculate regression standard error for confidence interval
            residuals = y_valid - y_pred
            residual_std = np.std(residuals, ddof=2)  # ddof=2 for slope and intercept

            # Plot ±1 standard error confidence interval based on regression residuals
            ax.fill_between(
                x_valid,
                y_pred - residual_std,
                y_pred + residual_std,
                color=color,
                alpha=0.2,
            )

    # Add regression lines for each time period
    add_regression_line(
        elevations, temp_all, std_all, valid_all, colors["all_times"], "All times", "o"
    )
    add_regression_line(
        elevations,
        temp_day,
        std_day,
        valid_day,
        colors["daytime"],
        "Daytime (4am-8pm)",
        "s",
    )
    add_regression_line(
        elevations,
        temp_night,
        std_night,
        valid_night,
        colors["nighttime"],
        "Nighttime (8pm-4am)",
        "^",
    )

    # Add site labels
    for i, (elev, temp, site) in enumerate(zip(elevations, temp_all, site_names)):
        if not np.isnan(temp):
            ax.annotate(
                site,
                (elev, temp),
                xytext=(5, 5),
                textcoords="offset points",
                fontsize=8,
                alpha=0.7,
            )

    # Consolidate all styling at the end
    ax.set_xlabel("Elevation (m)")
    ax.set_ylabel("Mean Temperature (°C)")
    ax.set_title(f"{group_name}: Temperature vs Elevation")
    ax.legend(loc="best")
    apply_plot_styling(ax, style_type='default')


def plot_lapse_rate_histograms(ax, lapse_rate_data, site_temp_data, group_name):
    """Plot lapse rate histograms for 1H averaged data only"""

    if (
        not lapse_rate_data
        or "1H" not in lapse_rate_data
        or len(lapse_rate_data["1H"]) == 0
    ):
        ax.text(
            0.5,
            0.5,
            "No 1H lapse rate data available",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        ax.set_title(f"{group_name}: Lapse Rate Distributions (1H averaged)")
        return

    # Only show 1H data
    resolution = "1H"
    color = "green"
    alpha_val = 0.7

    # Standardized bins: +/- 20°C/km with 0.5°C/km width
    bins = np.arange(-20.0, 21, 1)

    lapse_rates = np.array(lapse_rate_data[resolution])

    # Filter out extreme values
    lapse_rates = lapse_rates[(lapse_rates >= -50) & (lapse_rates <= 50)]

    if len(lapse_rates) > 0:
        # Plot histogram
        ax.hist(
            lapse_rates,
            bins=bins,
            alpha=alpha_val,
            color=color,
            density=True,
            edgecolor="black",
            linewidth=0.3,
        )

        # Calculate statistics
        mean_lr = np.mean(lapse_rates)
        median_lr = np.median(lapse_rates)

        # Add vertical line for mean
        ax.axvline(
            x=mean_lr,
            color=color,
            linestyle="-",
            linewidth=2,
            alpha=0.8,
        )

        # Create legend entry with mean and median
        legend_entry = f"{resolution}: μ={mean_lr:.1f}, M={median_lr:.1f}"

    # Reference lines
    ax.axvline(x=0, color="black", linestyle="-", alpha=1.0, linewidth=2)
    ax.axvline(x=-6.5, color="black", linestyle="--", alpha=0.8, linewidth=2)

    # Create legend with statistics
    if len(lapse_rates) > 0:
        ax.legend([legend_entry], loc="upper right", fontsize=8)
    else:
        ax.text(
            0.5,
            0.5,
            "No valid 1H lapse rate data",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
    
    # Consolidate all styling at the end
    ax.set_xlim(-20, 20)
    ax.set_xlabel("Lapse Rate (°C/km)")
    ax.set_ylabel("Density")
    ax.set_title(f"{group_name}: Lapse Rate Distributions (1H averaged)")
    apply_plot_styling(ax, style_type='default')


def plot_temporal_lapse_analysis(ax, group_data, site_temp_data, group_name):
    """Plot temporal lapse rates by time period using existing group data"""

    if not group_data["lapse_rates"] or not group_data["times"]:
        ax.text(
            0.5,
            0.5,
            "No lapse rate time series available",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        ax.set_title(f"{group_name}: Temporal Lapse Rate Analysis")
        return

    # Collect all lapse rates and timestamps
    all_times = []
    all_lapse_rates = []

    for pair_times, pair_lapse_rates in zip(
        group_data["times"], group_data["lapse_rates"]
    ):
        all_times.extend(pair_times)
        all_lapse_rates.extend(pair_lapse_rates)

    if not all_times:
        ax.text(
            0.5,
            0.5,
            "No temporal data available",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        ax.set_title(f"{group_name}: Temporal Lapse Rate Analysis")
        return

    # Create DataFrame
    df = pd.DataFrame(
        {"datetime": pd.to_datetime(all_times), "lapse_rate": all_lapse_rates}
    )
    df.set_index("datetime", inplace=True)

    # Filter by time periods and aggregate hourly lapse rates to daily means
    period_data = {}

    for period_name, (start_hour, end_hour) in TIME_PERIODS.items():
        if period_name == "nighttime" and end_hour < start_hour:
            # Handle wrap-around for nighttime (20:00 to 04:00)
            time_mask = (df.index.hour >= start_hour) | (df.index.hour < end_hour)
        else:
            # Normal time range
            time_mask = (df.index.hour >= start_hour) & (df.index.hour < end_hour)

        period_df = df[time_mask]
        if len(period_df) > 0:
            # Take daily means of the hourly lapse rate values
            daily_means = period_df.resample("1D").mean().dropna()
            if len(daily_means) > 0:
                period_data[period_name] = daily_means

    # Define colors and markers for each time period
    colors = {"all_times": "blue", "daytime": "orange", "nighttime": "purple"}
    markers = {"all_times": "o", "daytime": "s", "nighttime": "^"}
    labels = {
        "all_times": "All times",
        "daytime": "Daytime (4am-8pm)",
        "nighttime": "Nighttime (8pm-4am)",
    }

    # Plot each time period
    for period_name in ["all_times", "daytime", "nighttime"]:
        if period_name in period_data:
            daily_data = period_data[period_name]
            ax.plot(
                daily_data.index,
                daily_data["lapse_rate"],
                color=colors[period_name],
                marker=markers[period_name],
                linewidth=2,
                markersize=4,
                alpha=0.8,
                label=f"{labels[period_name]} (n={len(daily_data)})",
            )

    # Reference lines
    ax.axhline(y=0, color="black", linestyle="-", alpha=1.0, linewidth=2)
    ax.axhline(y=-6.5, color="black", linestyle="--", alpha=0.8, linewidth=2)

    ax.set_ylabel("Daily Mean Lapse Rate (°C/km)")
    ax.set_title(f"{group_name}: Temporal Lapse Rate Analysis (1H → daily aggregated)")
    ax.legend(loc="best", fontsize=8)
    ax.grid(True, alpha=0.3)
    ax.set_ylim(-20, 20)

    # Format x-axis with 7-day major locator and daily minor locator
    if period_data:
        ax.xaxis.set_major_locator(mdates.WeekdayLocator(interval=1))  # Every 7 days
        ax.xaxis.set_minor_locator(mdates.DayLocator())  # Every day
        ax.xaxis.set_major_formatter(mdates.DateFormatter("%m/%d"))
        ax.tick_params(axis="x", rotation=45)
        ax.grid(True, which="minor", alpha=0.2)  # Daily grid lines


def plot_sensor_height_lapse_comparison(
    ax,
    sites,
    sites_with_both,
    site_elevations,
    csv_deployment_path,
    use_csv_masking,
    group_name,
):
    """Plot 2m vs 1m temperature scatter plot with site-specific colors and regression lines"""

    # Calculate mean temperature data for all sites
    site_temp_data_2m = {}
    site_temp_data_1m = {}
    site_names = []

    for site_name in sites:
        if site_name not in sites_with_both:
            continue

        try:
            # Get both sensor datasets
            ds_2m = sites_with_both[site_name]["2m"]["dataset"]
            ds_1m = sites_with_both[site_name]["1m"]["dataset"]
            
            temp_2m = ds_2m["temp_c"].dropna("datetime")
            temp_1m = ds_1m["temp_c"].dropna("datetime")

            # Convert to pandas and calculate means
            temp_2m_df = temp_2m.to_pandas()
            temp_1m_df = temp_1m.to_pandas()
            
            # Calculate mean temperatures
            mean_temp_2m = temp_2m_df.mean()
            mean_temp_1m = temp_1m_df.mean()
            
            if not (np.isnan(mean_temp_2m) or np.isnan(mean_temp_1m)):
                site_temp_data_2m[site_name] = mean_temp_2m
                site_temp_data_1m[site_name] = mean_temp_1m
                site_names.append(site_name)

        except Exception as e:
            print(f"    Error processing {site_name} for sensor height comparison: {e}")
            continue

    if len(site_temp_data_2m) < 2:
        ax.text(
            0.5,
            0.5,
            "Insufficient data for sensor height comparison",
            transform=ax.transAxes,
            ha="center",
            va="center",
        )
        ax.set_title(f"{group_name}: 2m vs 1m Temperature Comparison")
        return

    # Convert to arrays for analysis
    temps_2m = np.array([site_temp_data_2m[site] for site in site_names])
    temps_1m = np.array([site_temp_data_1m[site] for site in site_names])

    # Generate distinct colors for each site
    import matplotlib.cm as cm
    colors = cm.Set1(np.linspace(0, 1, len(site_names)))
    
    # Plot each site with distinct color and individual regression line
    for i, site_name in enumerate(site_names):
        temp_1m_site = temps_1m[i]
        temp_2m_site = temps_2m[i]
        color = colors[i]
        
        # Plot the data point for this site
        ax.scatter(
            temp_1m_site, temp_2m_site, 
            color=color, s=80, alpha=0.8, 
            label=f"{site_name} ({site_elevations[site_name]:.0f}m)",
            edgecolors='black', linewidth=0.5
        )
        
        # Add site label next to point
        ax.annotate(
            site_name,
            (temp_1m_site, temp_2m_site),
            xytext=(5, 5),
            textcoords="offset points",
            fontsize=9,
            fontweight='bold',
            color=color,
            alpha=0.9,
        )

    # Overall regression line for all sites combined
    if len(temps_1m) >= 2:
        slope, intercept, r_value, _, _ = linregress(temps_1m, temps_2m)
        
        # Create smooth line for regression
        x_range = np.linspace(temps_1m.min(), temps_1m.max(), 100)
        y_pred = slope * x_range + intercept
        
        ax.plot(
            x_range, y_pred, 
            '--', color='black', linewidth=2, alpha=0.7,
            label=f'Overall Fit: R²={r_value**2:.3f}'
        )
        
        # Add 1:1 reference line (where 2m = 1m temperatures)
        temp_min = min(temps_1m.min(), temps_2m.min())
        temp_max = max(temps_1m.max(), temps_2m.max())
        ax.plot(
            [temp_min, temp_max], [temp_min, temp_max], 
            ':', color='gray', linewidth=1.5, alpha=0.6,
            label='1:1 Reference'
        )

    # Set labels and title
    ax.set_xlabel("1m Sensor Temperature (°C)", fontsize=11)
    ax.set_ylabel("2m Sensor Temperature (°C)", fontsize=11)
    ax.set_title(f"{group_name}: 2m vs 1m Sensor Temperature Comparison", fontsize=12, fontweight='bold')
    
    # Customize legend for better visual clarity
    legend = ax.legend(loc='upper left', bbox_to_anchor=(0.02, 0.98), frameon=True, 
                      fancybox=True, shadow=True, fontsize=8)
    legend.get_frame().set_facecolor('white')
    legend.get_frame().set_alpha(0.9)
    
    # Add grid for better readability
    ax.grid(True, alpha=0.3, linestyle='-', linewidth=0.5)
    
    # Equal aspect ratio and tight layout
    ax.set_aspect('equal', adjustable='box')
    
    # Add text box with temperature difference statistics
    temp_diff = temps_2m - temps_1m
    mean_diff = np.mean(temp_diff)
    std_diff = np.std(temp_diff)
    
    textstr = f'2m - 1m Difference:\nMean: {mean_diff:.3f}°C\nStd: {std_diff:.3f}°C'
    props = dict(boxstyle='round', facecolor='lightblue', alpha=0.7)
    ax.text(0.98, 0.02, textstr, transform=ax.transAxes, fontsize=8,
            verticalalignment='bottom', horizontalalignment='right', bbox=props)


def plot_placeholder(ax, group_name, placeholder_title):
    """Plot placeholder for future analysis"""

    ax.text(
        0.5,
        0.5,
        f"{group_name}\n{placeholder_title}\n(Available for Future Analysis)",
        transform=ax.transAxes,
        ha="center",
        va="center",
        fontsize=12,
    )
    ax.set_title(f"{group_name}: {placeholder_title}")
    ax.set_xticks([])
    ax.set_yticks([])


if __name__ == "__main__":
    main()
